import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync,existsSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawn} from 'node:child_process';import {once} from 'node:events';import net from 'node:net';
import {openDatabase} from '../server/storage.mjs';import {setAccount,verifyPassword} from '../server/accounts.mjs';
// Production Node build is a required gate; do not silently skip this integration test.
test('独立服务器：公司登录、禁止伪造身份、岗位隔离、出库销售和Excel导出',async()=>{
 assert.ok(existsSync('dist-node/server/index.js'),'Run pnpm build:server before tests');const root=mkdtempSync(join(tmpdir(),'lj-http-')),sqlite=openDatabase(join(root,'business.sqlite')).sqlite,password='test-only-'+crypto.randomUUID();
 for(const [id,role] of [['admin','管理员'],['sales','销售'],['supply','供应链'],['finance','财务']])setAccount(sqlite,{id,email:`${id}@example.test`,name:id,role,site:role==='销售'?'印尼':null,password});sqlite.prepare('INSERT INTO sku_settings(sku,name,updated_at) VALUES (?,?,?)').run('HTTP-BAG','bag',new Date().toISOString());for(const ch of ['TikTok','Shopee'])sqlite.prepare('INSERT INTO inventory_balances(site,channel,sku,qty,updated_at) VALUES (?,?,?,?,?)').run('印尼',ch,'HTTP-BAG',10,new Date().toISOString());assert.ok(!sqlite.prepare('SELECT password_hash FROM local_accounts').get().password_hash.includes(password));sqlite.close();
 const free=net.createServer();free.listen(0,'127.0.0.1');await once(free,'listening');const port=free.address().port;await new Promise(r=>free.close(r));const origin=`http://127.0.0.1:${port}`;let logs='';const child=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,NODE_ENV:'production',LOONGJUMP_DATA_DIR:root,LOONGJUMP_ORIGIN:origin,LOONGJUMP_ALLOW_HTTP:'1',PORT:String(port),HOST:'127.0.0.1'},stdio:['ignore','pipe','pipe']});child.stdout.on('data',b=>logs+=b);child.stderr.on('data',b=>logs+=b);
 try{await new Promise((res,rej)=>{const timer=setTimeout(()=>rej(Error('Server startup timeout: '+logs)),15000);child.stdout.on('data',b=>{if(String(b).includes('ready at')){clearTimeout(timer);res()}});child.once('exit',code=>{clearTimeout(timer);rej(Error(`Server exited ${code}: ${logs}`))})});
 const forged=await fetch(origin+'/api/system',{headers:{'oai-authenticated-user-id':'admin','oai-authenticated-user-email':'admin@example.test','x-local-test-user':'admin'}});assert.equal(forged.status,401);
 const login=async (who,remember=false)=>{const page=await fetch(origin+'/signin-with-chatgpt'),html=await page.text(),csrf=html.match(/name="csrf" value="([a-f0-9]+)"/)[1],pre=page.headers.getSetCookie()[0].split(';')[0];const r=await fetch(origin+'/signin-with-chatgpt',{method:'POST',redirect:'manual',headers:{origin,'content-type':'application/x-www-form-urlencoded',cookie:pre},body:new URLSearchParams({csrf,email:`${who}@example.test`,password,remember:remember?'1':'0'})});assert.equal(r.status,303,await r.text());const session=r.headers.getSetCookie().find(c=>c.startsWith('lj_session='));assert.match(session,new RegExp('Max-Age='+(remember?2592000:28800)));assert.match(session,/HttpOnly/);return session.split(';')[0]};
 const health=await fetch(origin+'/healthz');assert.equal(health.status,200);assert.deepEqual(await health.json(),{ok:true,release:'local'});
 const cookies={};for(const who of ['admin','sales','supply','finance'])cookies[who]=await login(who,who==='sales');
 const request=async(who,path,payload)=>{const r=await fetch(origin+path,{method:payload?'POST':'GET',headers:{cookie:cookies[who],origin,...(payload?{'content-type':'application/json'}:{})},...(payload?{body:JSON.stringify({...payload,operationId:crypto.randomUUID()})}:{})});const text=await r.text();let body;try{body=JSON.parse(text)}catch{body=text}return {status:r.status,body}};
 const system=await request('admin','/api/system');assert.equal(system.status,200,JSON.stringify(system.body));const page=await fetch(origin+'/',{headers:{cookie:cookies.admin}});assert.equal(page.status,200);assert.ok((await page.text()).includes('LOONG'));
 assert.equal((await fetch(origin+'/api/inventory-baseline')).status,401);
 assert.equal((await fetch(origin+'/admin/inventory-baseline',{headers:{cookie:cookies.admin}})).status,200);
 assert.equal((await request('sales','/api/inventory-baseline',{action:'status'})).status,403);
 assert.deepEqual((await request('admin','/api/inventory-baseline',{action:'status'})).body,{active:false});
 assert.equal((await fetch(origin+'/api/inventory-baseline',{method:'POST',headers:{cookie:cookies.admin,origin:'https://attacker.test','content-type':'application/json'},body:JSON.stringify({action:'apply'})})).status,403);
 // Account creation must work through the real company login and production router.
 assert.equal((await fetch(origin+'/api/users')).status,401);
 assert.deepEqual((await request('admin','/api/users')).body,{canCreate:true,loginMode:'company'});
 assert.equal((await request('sales','/api/users')).status,403);
 const employee={name:'网页新增运营',email:' Newops@Example.Test ',password,role:'运营',site:'马来西亚',channel:'Shopee',responsibilityUnit:'运营团队',active:true};
 for(const who of ['sales','supply','finance'])assert.equal((await request(who,'/api/users',employee)).status,403);
 const crossSite=await fetch(origin+'/api/users',{method:'POST',headers:{origin:'https://attacker.test',cookie:cookies.admin,'content-type':'application/json'},body:JSON.stringify(employee)});assert.equal(crossSite.status,403);
 const malformed=await fetch(origin+'/api/users',{method:'POST',headers:{origin,cookie:cookies.admin,'content-type':'application/json'},body:'null'});assert.equal(malformed.status,400);
 const oversized=await fetch(origin+'/api/users',{method:'POST',headers:{origin,cookie:cookies.admin,'content-type':'application/json'},body:JSON.stringify({...employee,name:'x'.repeat(9000)})});assert.equal(oversized.status,413);
 assert.equal((await request('admin','/api/users',{...employee,password:'short'})).status,400);
 assert.equal((await request('admin','/api/users',{...employee,site:''})).status,400);
 const [created,repeated]=await Promise.all([request('admin','/api/users',employee),request('admin','/api/users',employee)]);
 assert.deepEqual([created.status,repeated.status].sort(),[201,409]);
 const accountResult=created.status===201?created:repeated;
 assert.ok(accountResult.body.userId);assert.ok(!JSON.stringify(accountResult.body).includes(password));
 cookies.newops=await login('newops');
 const employeeView=await request('newops','/api/system');assert.equal(employeeView.status,200);
 assert.equal(employeeView.body.actor.id,accountResult.body.userId);assert.equal(employeeView.body.actor.role,'运营');
 assert.equal(employeeView.body.actor.site,'马来西亚');assert.equal(employeeView.body.actor.channel,'Shopee');
 assert.ok(employeeView.body.inventory.every(row=>row.site==='马来西亚'&&row.channel==='Shopee'));
 assert.equal((await request('newops','/api/users',{...employee,email:'forbidden@example.test'})).status,403);
 { // After-sales routes require authentication, protect draft evidence and enforce ownership.
 const afterMonth=new Date(Date.now()+8*3600000).toISOString().slice(0,7);
 assert.equal((await fetch(origin+'/api/after-sales?month='+afterMonth)).status,401);
 assert.equal((await request('finance','/api/after-sales?month='+afterMonth)).status,403);
 const afterCreated=await request('newops','/api/after-sales',{action:'create',businessDate:afterMonth+'-01',caseNo:'HTTP-AFTER-1',orderNo:'HTTP-ORDER-1',sku:'HTTP-SKU',qty:1,reason:'商品质量问题',description:'客户反馈拉链损坏',refundAmount:'5.25'});
 assert.equal(afterCreated.status,200,JSON.stringify(afterCreated.body));const afterId=afterCreated.body.id;
 assert.equal((await request('admin','/api/after-sales?history='+afterId)).status,404);
 const form=new FormData();form.append('recordId',afterId);form.append('file',new File([new Uint8Array([255,216,255,1])],'proof.jpg',{type:'image/jpeg'}));
 const uploaded=await fetch(origin+'/api/after-sales/files',{method:'POST',headers:{origin,cookie:cookies.newops},body:form});assert.equal(uploaded.status,200);const proof=await uploaded.json();
 assert.equal((await request('admin','/api/after-sales/files?id='+proof.id)).status,404);
 assert.equal((await request('newops','/api/after-sales/files?id='+proof.id)).status,200);
 const afterRows=await request('newops','/api/after-sales?month='+afterMonth);const afterRow=afterRows.body.records.find(r=>r.id===afterId);
 const crossAfter=await fetch(origin+'/api/after-sales',{method:'POST',headers:{origin:'https://attacker.test',cookie:cookies.newops,'content-type':'application/json'},body:JSON.stringify({action:'submit',id:afterId,version:afterRow.version})});assert.equal(crossAfter.status,403);
 assert.equal((await request('newops','/api/after-sales',{action:'submit',id:afterId,version:afterRow.version})).status,200);
 assert.equal((await request('admin','/api/after-sales/files?id='+proof.id)).status,200);
 assert.equal((await request('finance','/api/after-sales/files?id='+proof.id)).status,403);
 }

 let updatedUsers=await request('admin','/api/system');
 assert.equal(updatedUsers.body.users.find(user=>user.id===accountResult.body.userId).responsibility_unit,'运营团队');
 const creationAudit=updatedUsers.body.audit.find(row=>row.entity_id===accountResult.body.userId);
 assert.equal(creationAudit.action,'新增用户');assert.ok(!JSON.stringify(updatedUsers.body).includes(password));assert.ok(!JSON.stringify(updatedUsers.body).includes('password_hash'));
 assert.equal((await request('admin','/api/system',{action:'assignUser',userId:accountResult.body.userId,role:'运营',site:'马来西亚',channel:'Shopee',active:false})).status,200);
 assert.equal((await request('newops','/api/system')).status,401);
 updatedUsers=await request('admin','/api/system');assert.equal(updatedUsers.body.users.find(user=>user.id===accountResult.body.userId).active,0);
 assert.equal((await request('admin','/api/system',{action:'assignUser',userId:accountResult.body.userId,role:'运营',site:'马来西亚',channel:'Shopee',active:true})).status,200);
 cookies.newops=await login('newops');assert.equal((await request('newops','/api/system')).status,200);
 // Bulk imports are authenticated and atomic through the production HTTP router.
 const importMeta={fileName:'http-stock.csv',fileHash:'c'.repeat(64)};
 const stockRows=[{site:'马来西亚',channel:'Shopee',sku:'HTTP-IMPORT',name:'导入库存',countedQty:12,reason:'期初库存核对'}];
 assert.equal((await request('finance','/api/system',{action:'bulkImport',kind:'inventory',rows:stockRows,...importMeta})).status,403);
 const bulk=await request('admin','/api/system',{action:'bulkImport',kind:'inventory',rows:stockRows,...importMeta});assert.equal(bulk.status,200,JSON.stringify(bulk.body));assert.equal(bulk.body.imported,1);
 assert.equal((await request('admin','/api/system',{action:'bulkImport',kind:'inventory',rows:stockRows,...importMeta})).status,409);
 const opsCount=await request('newops','/api/system',{action:'bulkImport',kind:'inventory',rows:[{...stockRows[0],countedQty:9}],...importMeta});assert.equal(opsCount.status,200,JSON.stringify(opsCount.body));
 assert.equal((await request('newops','/api/system')).body.inventory.find(r=>r.sku==='HTTP-IMPORT').qty,12);
 assert.equal((await request('newops','/api/system',{action:'bulkImport',kind:'inventory',rows:[{...stockRows[0],site:'印尼',countedQty:2}],...importMeta})).status,403);
 const importedReceipt={receiptNo:'HTTP-RCV-1',sku:'HTTP-RCV',site:'印尼',channel:'TikTok',qty:3,proofRef:'仓库签收001'};
 assert.equal((await request('admin','/api/system',{action:'bulkImport',kind:'inbound',rows:[importedReceipt],...importMeta})).status,200);
 const invalidBatch=await request('admin','/api/system',{action:'bulkImport',kind:'inbound',rows:[{...importedReceipt,receiptNo:'HTTP-RCV-2'},importedReceipt],...importMeta});assert.equal(invalidBatch.status,409);
 const afterImport=await request('admin','/api/system');assert.ok(!afterImport.body.receipts.some(r=>r.receipt_no==='HTTP-RCV-2'));
 const salesImport={action:'salesImport',site:'马来西亚',channel:'Shopee',businessDate:new Date(Date.now()+8*3600000).toISOString().slice(0,10),sourceBatchRef:'HTTP-SALES-001',importKey:'http-file-sales-001',rows:[{sku:'HTTP-IMPORT',qty:2}],fileName:'sales.csv'};
 assert.equal((await request('newops','/api/system',salesImport)).status,200);
 assert.equal((await request('newops','/api/system',salesImport)).status,409);
 assert.equal((await request('newops','/api/system')).body.inventory.find(r=>r.sku==='HTTP-IMPORT').qty,10);
 const confirmDay={action:'confirmSalesDay',site:'马来西亚',channel:'Shopee',businessDate:salesImport.businessDate,confirmed:true,note:'HTTP核对平台整日销量'};
 assert.equal((await request('finance','/api/system',confirmDay)).status,403);
 assert.equal((await request('newops','/api/system',{...confirmDay,site:'印尼'})).status,403);
 assert.equal((await request('newops','/api/system',confirmDay)).status,200);
 assert.equal((await request('newops','/api/system')).body.salesScopeStatus[0].updatedToday,true);

 // Sales dashboard retains authentication and site scope through the actual router.
 assert.equal((await fetch(origin+'/api/sales-dashboard')).status,401);
 for(const who of ['sales','finance'])assert.equal((await request(who,'/api/sales-dashboard')).status,403);
 assert.equal((await request('newops','/api/sales-dashboard?site='+encodeURIComponent('印尼'))).status,403);
 const performance=await request('newops','/api/system',{...salesImport,sourceBatchRef:'HTTP-PRICE-002',importKey:'http-file-price-002',rows:[{sku:'HTTP-IMPORT',qty:2,amount:50.25,adCost:10,currency:'MYR'},{sku:'HTTP-AD-ONLY',qty:0,adCost:5,currency:'MYR'}]});assert.equal(performance.status,200,JSON.stringify(performance.body));
 const dashboard=await request('newops','/api/sales-dashboard');assert.equal(dashboard.status,200,JSON.stringify(dashboard.body));assert.equal(dashboard.body.totalQty,4);assert.equal(dashboard.body.currencies[0].revenue,50.25);assert.equal(dashboard.body.currencies[0].roas,null);assert.equal(dashboard.body.roiRanking.find(r=>r.sku==='HTTP-AD-ONLY').roas,0);
 assert.ok(dashboard.body.scopes.every(r=>r.site==='马来西亚'&&r.channel==='Shopee'));
 assert.equal((await request('newops','/api/sales-dashboard?from=2026-02-30')).status,400);
 const reversal=await request('admin','/api/system',{action:'reverseSalesImport',importId:performance.body.importId,reason:'接口测试纠正重复报表'});assert.equal(reversal.status,200,JSON.stringify(reversal.body));
 assert.equal((await request('newops','/api/sales-dashboard')).body.totalQty,2);
 const crossImport=await fetch(origin+'/api/system',{method:'POST',headers:{cookie:cookies.admin,origin:'https://attacker.test','content-type':'application/json'},body:JSON.stringify({action:'bulkImport',kind:'inventory',rows:stockRows,...importMeta})});assert.equal(crossImport.status,403);
 const c=await request('sales','/api/wholesale',{action:'customerCreate',name:'HTTP客户',contact:'Sari',phone:'08123456',city:'Jakarta',address:'Warehouse 1'});assert.equal(c.status,200,JSON.stringify(c.body));const day=new Date(Date.now()+7*3600000).toISOString().slice(0,10);
 // Field workspace uses the real production router, authentication and file storage.
 assert.equal((await fetch(origin+'/api/field-sales')).status,401);
 assert.equal((await request('supply','/api/field-sales')).status,200);
 const field=await request('sales','/api/field-sales',{action:'create',kind:'visit',customerId:c.body.id,businessDate:day,visitType:'cold',note:'Discussed wholesale products in the shop.'});assert.equal(field.status,200,JSON.stringify(field.body));
 const fieldId=field.body.id,png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aB5sAAAAASUVORK5CYII=','base64');
 const upload=async who=>{const body=new FormData();body.set('recordId',fieldId);body.set('file',new File([png],'shop.png',{type:'image/png'}));return fetch(origin+'/api/field-sales/files',{method:'POST',headers:{cookie:cookies[who],origin},body})};
 assert.equal((await upload('finance')).status,403);const uploaded=await upload('sales');assert.equal(uploaded.status,200);const fileId=(await uploaded.json()).id;
 const image=await fetch(origin+'/api/field-sales/files?id='+fileId,{headers:{cookie:cookies.sales}});assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/svg+xml');assert.match(await image.text(),/Uploaded \/ Waktu unggah: .* WIB/);
 assert.equal((await fetch(origin+'/api/field-sales/files?id='+fileId)).status,401);assert.equal((await fetch(origin+'/api/field-sales/files?id='+fileId,{headers:{cookie:cookies.supply}})).status,200);
 let fieldView=await request('sales','/api/field-sales');assert.equal(fieldView.body.records[0].version,2);assert.equal((await request('sales','/api/field-sales',{action:'submit',id:fieldId,version:2,location:{latitude:-6.2,longitude:106.8,accuracy:15,capturedAt:Date.now()}})).status,200);
 assert.equal((await upload('sales')).status,409);fieldView=await request('finance','/api/field-sales');assert.equal(fieldView.body.records[0].status,'valid');assert.equal(fieldView.body.contributions.find(r=>r.id==='sales').visits,1);
 const o=await request('sales','/api/wholesale',{action:'orderCreate',customerId:c.body.id,businessDate:day,paymentTerms:'credit',dueDate:'2027-01-01',items:[{sku:'HTTP-BAG',qty:5,unitPrice:100000}]});assert.equal(o.status,200);let view=await request('sales','/api/wholesale'),order=view.body.orders[0];
 assert.equal((await request('sales','/api/wholesale',{action:'orderApprove',orderId:o.body.id,version:order.version,supplyUserId:'supply',stockBasisConfirmed:true,reason:'申请人不得自行审批'})).status,403);
 assert.equal((await request('admin','/api/wholesale',{action:'orderApprove',orderId:o.body.id,version:order.version,supplyUserId:'supply',stockBasisConfirmed:true,reason:'核对库存允许出库'})).status,200);
 view=await request('supply','/api/wholesale');order=view.body.orders[0];assert.equal((await request('supply','/api/wholesale',{action:'orderShip',orderId:order.id,version:order.version,items:[{itemId:order.items[0].id,qty:5}],businessDate:day,warehouse:'印尼仓',carrier:'JNE',trackingNo:'HTTP001',handoverConfirmed:true})).status,200);
 view=await request('finance','/api/wholesale');assert.equal(view.body.dashboard.netAmount,500000);assert.equal(view.body.orders[0].paymentStatus,'未回款');const excel=await fetch(origin+'/api/wholesale/export?mode=all&month='+day.slice(0,7)+'&lang=id',{headers:{cookie:cookies.finance}});assert.equal(excel.status,200);assert.ok((await excel.arrayBuffer()).byteLength>5000);
 const foreignOrigin=await fetch(origin+'/api/wholesale',{method:'POST',headers:{origin:'https://attacker.test',cookie:cookies.admin,'content-type':'application/json'},body:'{}'});assert.equal(foreignOrigin.status,403);
 }finally{const done=once(child,'exit');child.kill('SIGTERM');await done;rmSync(root,{recursive:true,force:true})}
});
