import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync,existsSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawn} from 'node:child_process';import {once} from 'node:events';import net from 'node:net';
import {openDatabase} from '../server/storage.mjs';import {setAccount,verifyPassword} from '../server/accounts.mjs';
// Production Node build is a required gate; do not silently skip this integration test.
test('独立服务器：公司登录、禁止伪造身份、岗位隔离、出库销售和Excel导出',async()=>{
 assert.ok(existsSync('dist-node/server/index.js'),'Run pnpm build:server before tests');const root=mkdtempSync(join(tmpdir(),'lj-http-')),sqlite=openDatabase(join(root,'business.sqlite')).sqlite,password='test-only-'+crypto.randomUUID();
 for(const [id,role] of [['admin','管理员'],['sales','销售'],['supply','供应链'],['finance','财务']])setAccount(sqlite,{id,email:`${id}@example.test`,name:id,role,site:role==='销售'?'印尼':null,password});sqlite.prepare('INSERT INTO sku_settings(sku,name,updated_at) VALUES (?,?,?)').run('HTTP-BAG','bag',new Date().toISOString());for(const ch of ['TikTok','Shopee'])sqlite.prepare('INSERT INTO inventory_balances(site,channel,sku,qty,updated_at) VALUES (?,?,?,?,?)').run('印尼',ch,'HTTP-BAG',10,new Date().toISOString());assert.ok(!sqlite.prepare('SELECT password_hash FROM local_accounts').get().password_hash.includes(password));sqlite.close();
 const free=net.createServer();free.listen(0,'127.0.0.1');await once(free,'listening');const port=free.address().port;await new Promise(r=>free.close(r));const origin=`http://127.0.0.1:${port}`;let logs='';const child=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,NODE_ENV:'production',LOONGJUMP_DATA_DIR:root,LOONGJUMP_ORIGIN:origin,LOONGJUMP_ALLOW_HTTP:'1',PORT:String(port),HOST:'127.0.0.1'},stdio:['ignore','pipe','pipe']});child.stdout.on('data',b=>logs+=b);child.stderr.on('data',b=>logs+=b);
 try{await new Promise((res,rej)=>{const timer=setTimeout(()=>rej(Error('Server startup timeout: '+logs)),15000);child.stdout.on('data',b=>{if(String(b).includes('ready at')){clearTimeout(timer);res()}});child.once('exit',code=>{clearTimeout(timer);rej(Error(`Server exited ${code}: ${logs}`))})});
 const forged=await fetch(origin+'/api/system',{headers:{'oai-authenticated-user-id':'admin','oai-authenticated-user-email':'admin@example.test','x-local-test-user':'admin'}});assert.equal(forged.status,401);
 const login=async who=>{const page=await fetch(origin+'/signin-with-chatgpt'),html=await page.text(),csrf=html.match(/name="csrf" value="([a-f0-9]+)"/)[1],pre=page.headers.getSetCookie()[0].split(';')[0];const r=await fetch(origin+'/signin-with-chatgpt',{method:'POST',redirect:'manual',headers:{origin,'content-type':'application/x-www-form-urlencoded',cookie:pre},body:new URLSearchParams({csrf,email:`${who}@example.test`,password})});assert.equal(r.status,303,await r.text());return r.headers.getSetCookie().find(c=>c.startsWith('lj_session=')).split(';')[0]};
 const cookies={};for(const who of ['admin','sales','supply','finance'])cookies[who]=await login(who);
 const request=async(who,path,payload)=>{const r=await fetch(origin+path,{method:payload?'POST':'GET',headers:{cookie:cookies[who],origin,...(payload?{'content-type':'application/json'}:{})},...(payload?{body:JSON.stringify({...payload,operationId:crypto.randomUUID()})}:{})});const text=await r.text();let body;try{body=JSON.parse(text)}catch{body=text}return {status:r.status,body}};
 const system=await request('admin','/api/system');assert.equal(system.status,200,JSON.stringify(system.body));const page=await fetch(origin+'/',{headers:{cookie:cookies.admin}});assert.equal(page.status,200);assert.ok((await page.text()).includes('LOONG'));
 // Account creation must work through the real company login and production router.
 assert.equal((await fetch(origin+'/api/users')).status,401);
 assert.deepEqual((await request('admin','/api/users')).body,{canCreate:true,loginMode:'company'});
 assert.equal((await request('sales','/api/users')).status,403);
 const employee={name:'网页新增运营',email:' Newops@Example.Test ',password,role:'运营',site:'马来西亚',channel:'Shopee',responsibilityUnit:'运营团队',active:true};
 for(const who of ['sales','supply','finance'])assert.equal((await request(who,'/api/users',employee)).status,403);
 const crossSite=await fetch(origin+'/api/users',{method:'POST',headers:{origin:'https://attacker.test',cookie:cookies.admin,'content-type':'application/json'},body:JSON.stringify(employee)});assert.equal(crossSite.status,403);
 const malformed=await fetch(origin+'/api/users',{method:'POST',headers:{origin,cookie:cookies.admin,'content-type':'application/json'},body:'null'});assert.equal(malformed.status,400);
 const oversized=await fetch(origin+'/api/users',{method:'POST',headers:{origin,cookie:cookies.admin,'content-type':'application/json'},body:JSON.stringify({...employee,name:'x'.repeat(9000)})});assert.equal(oversized.status,413);
 assert.equal((await request('admin','/api/users',{...employee,password:'short'})).status,400);
 assert.equal((await request('admin','/api/users',{...employee,site:''})).status,400);
 const [created,repeated]=await Promise.all([request('admin','/api/users',employee),request('admin','/api/users',employee)]);
 assert.deepEqual([created.status,repeated.status].sort(),[201,409]);
 const accountResult=created.status===201?created:repeated;
 assert.ok(accountResult.body.userId);assert.ok(!JSON.stringify(accountResult.body).includes(password));
 cookies.newops=await login('newops');
 const employeeView=await request('newops','/api/system');assert.equal(employeeView.status,200);
 assert.equal(employeeView.body.actor.id,accountResult.body.userId);assert.equal(employeeView.body.actor.role,'运营');
 assert.equal(employeeView.body.actor.site,'马来西亚');assert.equal(employeeView.body.actor.channel,'Shopee');
 assert.ok(employeeView.body.inventory.every(row=>row.site==='马来西亚'&&row.channel==='Shopee'));
 assert.equal((await request('newops','/api/users',{...employee,email:'forbidden@example.test'})).status,403);
 let updatedUsers=await request('admin','/api/system');
 assert.equal(updatedUsers.body.users.find(user=>user.id===accountResult.body.userId).responsibility_unit,'运营团队');
 const creationAudit=updatedUsers.body.audit.find(row=>row.entity_id===accountResult.body.userId);
 assert.equal(creationAudit.action,'新增用户');assert.ok(!JSON.stringify(updatedUsers.body).includes(password));assert.ok(!JSON.stringify(updatedUsers.body).includes('password_hash'));
 assert.equal((await request('admin','/api/system',{action:'assignUser',userId:accountResult.body.userId,role:'运营',site:'马来西亚',channel:'Shopee',active:false})).status,200);
 assert.equal((await request('newops','/api/system')).status,401);
 updatedUsers=await request('admin','/api/system');assert.equal(updatedUsers.body.users.find(user=>user.id===accountResult.body.userId).active,0);
 assert.equal((await request('admin','/api/system',{action:'assignUser',userId:accountResult.body.userId,role:'运营',site:'马来西亚',channel:'Shopee',active:true})).status,200);
 cookies.newops=await login('newops');assert.equal((await request('newops','/api/system')).status,200);
 // Bulk imports are authenticated and atomic through the production HTTP router.
 const importMeta={fileName:'http-stock.csv',fileHash:'c'.repeat(64)};
 const stockRows=[{site:'马来西亚',channel:'Shopee',sku:'HTTP-IMPORT',name:'导入库存',countedQty:12,reason:'期初库存核对'}];
 assert.equal((await request('finance','/api/system',{action:'bulkImport',kind:'inventory',rows:stockRows,...importMeta})).status,403);
 const bulk=await request('admin','/api/system',{action:'bulkImport',kind:'inventory',rows:stockRows,...importMeta});assert.equal(bulk.status,200,JSON.stringify(bulk.body));assert.equal(bulk.body.imported,1);
 assert.equal((await request('admin','/api/system',{action:'bulkImport',kind:'inventory',rows:stockRows,...importMeta})).status,409);
 const opsCount=await request('newops','/api/system',{action:'bulkImport',kind:'inventory',rows:[{...stockRows[0],countedQty:9}],...importMeta});assert.equal(opsCount.status,200,JSON.stringify(opsCount.body));
 assert.equal((await request('newops','/api/system')).body.inventory.find(r=>r.sku==='HTTP-IMPORT').qty,12);
 assert.equal((await request('newops','/api/system',{action:'bulkImport',kind:'inventory',rows:[{...stockRows[0],site:'印尼',countedQty:2}],...importMeta})).status,403);
 const importedReceipt={receiptNo:'HTTP-RCV-1',sku:'HTTP-RCV',site:'印尼',channel:'TikTok',qty:3,proofRef:'仓库签收001'};
 assert.equal((await request('admin','/api/system',{action:'bulkImport',kind:'inbound',rows:[importedReceipt],...importMeta})).status,200);
 const invalidBatch=await request('admin','/api/system',{action:'bulkImport',kind:'inbound',rows:[{...importedReceipt,receiptNo:'HTTP-RCV-2'},importedReceipt],...importMeta});assert.equal(invalidBatch.status,409);
 const afterImport=await request('admin','/api/system');assert.ok(!afterImport.body.receipts.some(r=>r.receipt_no==='HTTP-RCV-2'));
 const salesImport={action:'salesImport',site:'马来西亚',channel:'Shopee',businessDate:new Date(Date.now()+8*3600000).toISOString().slice(0,10),sourceBatchRef:'HTTP-SALES-001',importKey:'http-file-sales-001',rows:[{sku:'HTTP-IMPORT',qty:2}],fileName:'sales.csv'};
 assert.equal((await request('newops','/api/system',salesImport)).status,200);
 assert.equal((await request('newops','/api/system',salesImport)).status,409);
 assert.equal((await request('newops','/api/system')).body.inventory.find(r=>r.sku==='HTTP-IMPORT').qty,10);
 const crossImport=await fetch(origin+'/api/system',{method:'POST',headers:{cookie:cookies.admin,origin:'https://attacker.test','content-type':'application/json'},body:JSON.stringify({action:'bulkImport',kind:'inventory',rows:stockRows,...importMeta})});assert.equal(crossImport.status,403);
 const c=await request('sales','/api/wholesale',{action:'customerCreate',name:'HTTP客户',contact:'Sari',phone:'08123456',city:'Jakarta',address:'Warehouse 1'});assert.equal(c.status,200,JSON.stringify(c.body));const day=new Date(Date.now()+7*3600000).toISOString().slice(0,10);
 const o=await request('sales','/api/wholesale',{action:'orderCreate',customerId:c.body.id,businessDate:day,paymentTerms:'credit',dueDate:'2027-01-01',items:[{sku:'HTTP-BAG',qty:5,unitPrice:100000}]});assert.equal(o.status,200);let view=await request('sales','/api/wholesale'),order=view.body.orders[0];
 assert.equal((await request('sales','/api/wholesale',{action:'orderApprove',orderId:o.body.id,version:order.version,supplyUserId:'supply',stockBasisConfirmed:true,reason:'申请人不得自行审批'})).status,403);
 assert.equal((await request('admin','/api/wholesale',{action:'orderApprove',orderId:o.body.id,version:order.version,supplyUserId:'supply',stockBasisConfirmed:true,reason:'核对库存允许出库'})).status,200);
 view=await request('supply','/api/wholesale');order=view.body.orders[0];assert.equal((await request('supply','/api/wholesale',{action:'orderShip',orderId:order.id,version:order.version,items:[{itemId:order.items[0].id,qty:5}],businessDate:day,warehouse:'印尼仓',carrier:'JNE',trackingNo:'HTTP001',handoverConfirmed:true})).status,200);
 view=await request('finance','/api/wholesale');assert.equal(view.body.dashboard.netAmount,500000);assert.equal(view.body.orders[0].paymentStatus,'未回款');const excel=await fetch(origin+'/api/wholesale/export?mode=all&month='+day.slice(0,7)+'&lang=id',{headers:{cookie:cookies.finance}});assert.equal(excel.status,200);assert.ok((await excel.arrayBuffer()).byteLength>5000);
 const foreignOrigin=await fetch(origin+'/api/wholesale',{method:'POST',headers:{origin:'https://attacker.test',cookie:cookies.admin,'content-type':'application/json'},body:'{}'});assert.equal(foreignOrigin.status,403);
 }finally{const done=once(child,'exit');child.kill('SIGTERM');await done;rmSync(root,{recursive:true,force:true})}
});
