import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import ts from 'typescript';
import {fixture} from './fixtures.mjs';
let source=readFileSync(new URL('../app/api/system/route.ts',import.meta.url),'utf8');
source=source.replace(/^import .*from "\.\.\/\.\.\/\.\.\/lib\/(database|auth)";\n/gm,'');
source=source.replaceAll('"../../../lib/','"../../lib/');
source=source.replace('"../../lib/forecast"','"../../lib/forecast.ts"');
const shim=`let activeDb;export function setDb(db){activeDb=db;}const database=()=>activeDb,ensureSchema=async()=>{},nowIso=()=>new Date().toISOString(),makeId=p=>p+'_'+crypto.randomUUID();class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}function requireScope(a,s,c){if(a.role==='运营'&&(a.site!==s||a.channel!==c))throw new HttpError(403,'站点权限不足')}const requireActor=()=>{throw Error('Use HTTP integration tests for authentication')};const ROLES=['管理员','销售','运营','运营主管','新品开发','财务','供应链','工厂','海运'];`;
mkdirSync(new URL('./.generated/',import.meta.url),{recursive:true});writeFileSync(new URL('./.generated/system.mjs',import.meta.url),ts.transpileModule(shim+source+'\nexport {bulkImport,salesImport,reverseSalesImport,normalizedSales,receiveInbound,receiveTransportLeg,inventoryAdjust,submitInventoryCount,buildSeriesOrders,resolveInventoryHold,decideApproval,confirmPurchaseOrder,monthlySubmit,submitPlan,createShipmentBatch,receiveShipmentBatch,decideNewProduct,submitNewProductStage};',{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);
export const svc=await import('./.generated/system.mjs');
export function systemFixture(){const f=fixture();svc.setDb(f.db);return f;}
export function seedMonthly(f){const t='2026-09-01';f.sqlite.prepare('INSERT INTO users(id,email,name,role,created_at,updated_at) VALUES(?,?,?,?,?,?)').run('factory-1','factory@example.test','工厂甲','工厂',t,t);for(const [id,type,assigned] of [['supplier-1','supplier',null],['factory-partner','factory','factory-1']])f.sqlite.prepare('INSERT INTO business_partners(id,type,code,name,assigned_user_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(id,type,id,type==='supplier'?'供应商甲':'工厂甲',assigned,t,t);f.sqlite.prepare("UPDATE sku_settings SET product_series='测试系列',supplier_name='供应商甲',factory_name='工厂甲'").run();const item={sku:'BAG-A',name:'测试包',total:10,allocations:[{site:'印尼',channel:'TikTok',qty:10}]},payload={items:[item],seriesOrders:[{seriesName:'测试系列',supplierName:'供应商甲',factoryName:'工厂甲',items:[item]}]};f.sqlite.prepare('INSERT INTO approval_requests(id,type,month,status,stage,creator_id,creator_role,payload_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run('approval-test','monthly_plan','2026-09','pending','admin_review',f.users.supply.id,'供应链',JSON.stringify(payload),t,t);return 'approval-test';}
export async function race(f,one,two){const batch=f.db.batch;let release,ready;const held=new Promise(r=>ready=r);let calls=0;f.db.batch=async s=>{if(++calls===1){ready();await new Promise(r=>release=r)}return batch(s)};const pending=one().then(v=>({ok:true,value:v}),e=>({ok:false,error:e}));await held;let second;try{second={ok:true,value:await two()}}catch(e){second={ok:false,error:e}}release();const first=await pending;f.db.batch=batch;return [first,second];}
