import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fixture} from './fixtures.mjs';
import {fileBucket} from '../server/storage.mjs';
import {previewCleanup,applyCleanup,undoCleanup} from '../server/test-cleanup.mjs';
async function setup(fn){const root=mkdtempSync(join(tmpdir(),'lj-test-clean-')),prior=process.env.LOONGJUMP_BACKUP_DIR;process.env.LOONGJUMP_BACKUP_DIR=root;const f=fixture();f.db.sqlite=f.sqlite;const env={DB:f.db,WHOLESALE_FILES:fileBucket(join(root,'files'))};try{for(const month of ['2026-09','2026-10']){f.sqlite.prepare("INSERT INTO monthly_submissions(id,month,site,channel,items_json,total_qty,actor_id,submitted_at) VALUES(?,?,'印尼','TikTok','[]',0,'id-ops','2026-09-30')").run(month,month);f.sqlite.prepare("INSERT INTO approval_requests(id,type,month,status,stage,creator_id,creator_role,payload_json,created_at,updated_at) VALUES(?,'monthly_plan',?,'pending','admin_review','supply-1','供应链','{}','2026-09-30','2026-09-30')").run(month,month);f.sqlite.prepare("INSERT INTO new_product_projects(id,cycle_month,sku,stage_started_at,current_due_at,created_by,created_at,updated_at) VALUES(?,?,'BAG-A','2026-09-01','2026-09-04','id-ops','2026-09-01','2026-09-01')").run(month,month);f.sqlite.prepare("INSERT INTO new_product_stage_records(id,project_id,stage_key,data_json,actor_id,actor_name,submitted_at,updated_at) VALUES(?,?,'candidate','{}','id-ops','运营','2026-09-01','2026-09-01')").run(month,month);}await fn(f,env);}finally{f.sqlite.close();if(prior===undefined)delete process.env.LOONGJUMP_BACKUP_DIR;else process.env.LOONGJUMP_BACKUP_DIR=prior;rmSync(root,{recursive:true,force:true});}}
test('测试计划及新品清理保留10月记录和库存，可恢复且留痕',()=>setup(async(f,env)=>{const stock=JSON.stringify(f.sqlite.prepare('SELECT * FROM inventory_balances').all());const p=previewCleanup(f.sqlite);assert.equal(p.counts.monthly_submissions,1);const r=await applyCleanup(env,f.users.admin,p);for(const t of ['monthly_submissions','approval_requests','new_product_projects','new_product_stage_records'])assert.deepEqual(f.sqlite.prepare(`SELECT id FROM ${t}`).all().map(r=>r.id),['2026-10']);assert.equal(JSON.stringify(f.sqlite.prepare('SELECT * FROM inventory_balances').all()),stock);undoCleanup(env,f.users.admin,r.id);assert.equal(previewCleanup(f.sqlite).counts.new_product_stage_records,1);assert.equal(f.sqlite.prepare("SELECT COUNT(*) n FROM audit_logs WHERE entity_type='test-cleanup'").get().n,2);}));
test('拒绝非管理员、过期预览、关联生产或批准计划、清理后的新业务覆盖',()=>setup(async(f,env)=>{const p=previewCleanup(f.sqlite);await assert.rejects(applyCleanup(env,f.users.supply,p),/管理员/);await assert.rejects(applyCleanup(env,f.users.admin,{fingerprint:'stale'}),/变化/);f.sqlite.exec("UPDATE approval_requests SET status='approved' WHERE month='2026-09'");assert.throws(()=>previewCleanup(f.sqlite),/关联/);f.sqlite.exec("UPDATE approval_requests SET status='pending';UPDATE new_product_projects SET production_batch_id='linked' WHERE cycle_month='2026-09'");assert.throws(()=>previewCleanup(f.sqlite),/关联/);f.sqlite.exec("UPDATE new_product_projects SET production_batch_id=NULL");const r=await applyCleanup(env,f.users.admin,previewCleanup(f.sqlite));f.sqlite.exec("UPDATE monthly_submissions SET total_qty=1 WHERE month='2026-10'");assert.throws(()=>undoCleanup(env,f.users.admin,r.id),/业务变化/);}));
test('中途失败整体回滚',()=>setup(async(f,env)=>{f.sqlite.exec("CREATE TRIGGER test_fail BEFORE DELETE ON approval_requests BEGIN SELECT RAISE(ABORT,'forced failure'); END");await assert.rejects(applyCleanup(env,f.users.admin,previewCleanup(f.sqlite)),/forced failure/);assert.equal(previewCleanup(f.sqlite).counts.new_product_projects,1);assert.equal(previewCleanup(f.sqlite).counts.monthly_submissions,1);}));
