"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {reasons,responsibilities} from '../lib/after-sales.mjs';
import './after-sales.css';
type Row=Record<string,any>;
const today=()=>new Date(Date.now()+8*3600000).toISOString().slice(0,10);
const amount=(v:number)=>((v||0)/100).toLocaleString('zh-CN',{maximumFractionDigits:2});
const labels:Row={draft:'草稿 · 待上传提交',submitted:'待确认责任',confirmed:'处理中 / 待赔付',closed:'已结案',void:'已作废'};
async function request(url:string,p?:Row){const r=await fetch(url,p?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}:{cache:'no-store'});const v=await r.json();if(!r.ok)throw Error(v.error||'操作失败');return v;}
function exportCsv(records:Row[],month:string){const rows=[['售后日期','站点','渠道','运营','售后单号','订单号','SKU','件数','客户售后原因','状态','币种','退款金额','工厂线索','仓库线索','生产/入库批次','确认责任','具体责任方','应赔金额','累计实赔','待赔金额','运营改进措施'],...records.map(r=>{const d=r.data,paid=d.payments.reduce((s:number,p:Row)=>s+p.amountCents,0);return [r.business_date,r.site,r.channel,r.owner_name,r.case_no,d.orderNo,r.sku,d.qty,d.reason,labels[r.status],d.currency,d.refundCents/100,d.factory,d.warehouse,d.batch,d.responsibility,d.liableName,d.claimCents==null?'':d.claimCents/100,paid/100,d.claimCents==null?'':(d.claimCents-paid)/100,d.improvement]})];const escape=(x:any)=>`"${String(x??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')}"`;const u=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(escape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=`售后追溯-${month}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
export default function AfterSales(){
 const [month,setMonth]=useState(today().slice(0,7)),[data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState(''),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[filter,setFilter]=useState(''),[query,setQuery]=useState(''),[reason,setReason]=useState('');
 const detail=useRef<HTMLDivElement>(null),generation=useRef(0);
 const load=useCallback(async()=>{const g=++generation.current,v=await request('/api/after-sales?month='+month);if(g===generation.current)setData(v);return v;},[month]);
 useEffect(()=>{setData(null);setCreating(false);void load().catch(e=>setError(e.message));const timer=setInterval(()=>{if(document.visibilityState==='visible')void load().catch(e=>setError(e.message))},15000);return()=>{generation.current++;clearInterval(timer)}},[load]);
 useEffect(()=>{if(selected||creating)detail.current?.scrollIntoView({behavior:'smooth',block:'start'})},[selected,creating]);
 async function act(p:Row){setBusy(true);setError('');try{const v=await request('/api/after-sales',p);await load();if(p.action==='create'&&p.businessDate.slice(0,7)!==month)setMonth(p.businessDate.slice(0,7));if(v.id)setSelected(v.id);setCreating(false);return true}catch(e){setError(e instanceof Error?e.message:'操作失败');return false}finally{setBusy(false)}}
 const records=data?.records||[],visible=records.filter((r:Row)=>(!filter||r.status===filter)&&(!reason||r.data.reason===reason)&&(!query||[r.sku,r.case_no,r.data.orderNo,r.owner_name,r.site,r.channel,r.data.liableName].join(' ').toLowerCase().includes(query.toLowerCase()))),chosen=records.find((r:Row)=>r.id===selected),s=data?.summary;
 return <div className="after-sales"><header className="as-heading"><div><p className="as-eyebrow">运营质量与履约协作</p><h2>售后反馈</h2><p>每日留证 · 共同跟进 · 月度追偿</p></div><div className="as-controls"><label>售后发生月份<input type="month" value={month} onChange={e=>{if(!creating||window.confirm('切换月份会放弃未保存内容，确认？'))setMonth(e.target.value)}}/></label><button className="btn" disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>刷新</button>{data?.canCreate&&<button className="btn primary" onClick={()=>{setSelected('');setCreating(true)}}>＋ 登记售后</button>}</div></header>
 <p className="as-help">一张售后单每个 SKU 登记一行；退款金额填该行金额，勿将整单金额复制到每个 SKU。记录不会自动扣减销售或增加库存。</p>
 {error&&<div className="notice error" role="alert">{error}</div>}
 {data&&<><div className="as-kpis">{[['售后明细 / 订单',`${s.cases} / ${s.orders}`],['涉及件数',s.qty],['待确认责任',s.pending],['未结案明细',s.open]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
 <div className="as-summary"><section className="panel"><h3>售后原因分布</h3><p className="as-help">客户反馈原因，不等同于责任认定；草稿、作废不计入。</p>{s.reasons.map((r:Row)=><div className="as-bar" key={r.reason}><span>{r.reason}</span><progress aria-label={r.reason} max={Math.max(1,s.cases)} value={r.cases}/><b>{r.cases} 条 · {r.qty} 件</b></div>)}</section><section className="panel"><h3>本月售后追偿</h3><p className="as-help">按售后发生月归集，累计赔付含后续月份；不同币种独立统计。</p>{s.currencies.length?s.currencies.map((c:Row)=><div className="as-money" key={c.currency}><strong>{c.currency}</strong><span>退款登记 <b>{amount(c.refundCents)}</b></span><span>确认应赔 <b>{amount(c.claimCents)}</b></span><span>累计实赔 <b>{amount(c.paidCents)}</b></span><span className="as-pending">剩余待赔 <b>{amount(c.claimCents-c.paidCents)}</b></span></div>):<p>本月暂无已提交售后。</p>}</section></div>
 {s.daily.length>0&&<section className="panel"><h3>每日售后明细趋势</h3><div className="as-daily">{s.daily.map((day:Row)=><div key={day.date} title={`${day.date}：${day.cases}条，${day.qty}件`}><b>{day.cases}</b><div style={{height:90*day.cases/Math.max(1,...s.daily.map((x:Row)=>x.cases))}}/><small>{day.date.slice(5)}</small></div>)}</div><p className="as-help">显示已登记日期；无记录不代表已确认零售后。</p></section>}
 <section className="panel"><header className="as-heading"><h3>售后台账</h3><button className="btn" onClick={()=>exportCsv(visible,month)}>导出当前筛选</button></header><div className="as-controls"><input aria-label="搜索售后" placeholder="搜索 SKU / 单号 / 运营 / 责任方" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="售后状态" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">全部状态</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l as string}</option>)}</select><select aria-label="售后原因筛选" value={reason} onChange={e=>setReason(e.target.value)}><option value="">全部原因</option>{reasons.map((r:string)=><option key={r}>{r}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>日期 / 运营</th><th>站点 / 渠道</th><th>单号 / SKU</th><th>原因 / 件数</th><th>责任 / 进度</th><th>操作</th></tr></thead><tbody>{visible.map((r:Row)=><tr key={r.id}><td>{r.business_date}<small>{r.owner_name}</small></td><td>{r.site}<small>{r.channel}</small></td><td>{r.case_no}<small>{r.sku}</small></td><td>{r.data.reason}<small>{r.data.qty} 件</small></td><td><span className={`pill ${r.status==='closed'?'green':'red'}`}>{labels[r.status]}</span><small>{r.data.liableName||'待核实'}</small></td><td><button className="btn" onClick={()=>{setCreating(false);setSelected(r.id)}}>查看 / 处理</button></td></tr>)}</tbody></table>{!visible.length&&<p className="as-empty">暂无符合条件的记录</p>}</div><small>每15秒同步；最近成功读取 {new Date(data.generatedAt).toLocaleTimeString('zh-CN')}</small></section>
 {s.liable.length>0&&<section className="panel"><h3>责任方月度追溯</h3><div className="table-wrap"><table><thead><tr><th>责任类型 / 对象</th><th>售后明细 / 件数</th><th>币种</th><th>应赔</th><th>已赔</th><th>待赔</th></tr></thead><tbody>{s.liable.map((r:Row,i:number)=><tr key={i}><td>{r.responsibility} · {r.name}</td><td>{r.cases} / {r.qty}</td><td>{r.currency}</td><td>{amount(r.claimCents)}</td><td>{amount(r.paidCents)}</td><td>{amount(r.claimCents-r.paidCents)}</td></tr>)}</tbody></table></div></section>}
 <div ref={detail} className="as-detail-anchor">{creating&&<CaseForm busy={busy} act={act} onCancel={()=>setCreating(false)}/>} {chosen&&<CaseDetail key={chosen.id} row={chosen} data={data} busy={busy} act={act} load={load} setError={setError} error={error}/>}</div></>}
 </div>;
}
function CaseForm({busy,act,onCancel,row}:{busy:boolean;act:(p:Row)=>Promise<boolean>;onCancel:()=>void;row?:Row}){
 const [editVersion]=useState(row?.version);
 const [v,setV]=useState<Row>(row?{...row.data,refundAmount:row.data.refundCents/100,businessDate:row.business_date,caseNo:row.case_no,sku:row.sku}:{businessDate:today(),caseNo:'',orderNo:'',sku:'',qty:1,refundAmount:'',reason:reasons[0],description:'',factory:'',warehouse:'',batch:'',improvement:''});
 const field=(key:string,label:string,type='text',required=false)=><label key={key}>{label}<input type={type} required={required} value={v[key]} disabled={Boolean(row&&['businessDate','caseNo','sku'].includes(key))} min={type==='number'?'0':undefined} max={type==='date'?today():undefined} step={type==='number'?(key==='qty'?'1':'0.01'):undefined} maxLength={160} onChange={e=>setV({...v,[key]:e.target.value})}/></label>;
 return <form className="panel as-form" onSubmit={async e=>{e.preventDefault();if(await act({...v,action:row?'save':'create',id:row?.id,version:editVersion}))onCancel()}}><h3>{row?'修改售后草稿':'登记每日售后'}</h3><p>先保存草稿，再上传截图或照片并提交。请遮挡客户电话、收货地址等与判断无关的信息。</p><div className="as-fields">{field('businessDate','售后发生日期','date',true)}{field('caseNo','平台售后单号（无单号请填稳定内部编号）','text',true)}{field('orderNo','平台订单号','text',true)}{field('sku','SKU','text',true)}{field('qty','本行涉及件数','number',true)}{field('refundAmount','本行退款金额（站点原币种，无退款填0）','number',true)}<label>客户售后原因<select value={v.reason} onChange={e=>setV({...v,reason:e.target.value})}>{reasons.map((r:string)=><option key={r}>{r}</option>)}</select></label>{field('factory','工厂名称 / 编码（线索，未知可留空）')}{field('warehouse','发货仓库（线索，未知可留空）')}{field('batch','生产批次 / 入库或发货凭证')}</div><label>情况描述（至少4字）<textarea required minLength={4} maxLength={2000} rows={4} value={v.description} onChange={e=>setV({...v,description:e.target.value})}/></label><label>客户沟通 / 链接优化 / 改进措施<textarea maxLength={2000} rows={3} value={v.improvement} onChange={e=>setV({...v,improvement:e.target.value})}/></label><div className="as-controls"><button className="btn primary" disabled={busy} type="submit">保存草稿，上传证据</button><button type="button" className="btn" onClick={onCancel}>取消</button></div></form>;
}
function CaseDetail({row:r,data,busy,act,load,setError,error}:{row:Row;data:Row;busy:boolean;act:(p:Row)=>Promise<boolean>;load:()=>Promise<any>;setError:(s:string)=>void;error:string}){
 const [note,setNote]=useState(''),[editing,setEditing]=useState(false),[uploading,setUploading]=useState(false),[localError,setLocalError]=useState(''),[history,setHistory]=useState<Row[]|null>(null),[decision,setDecision]=useState({responsibility:r.data.responsibility||'',liableName:r.data.liableName||'',claimAmount:r.data.claimCents==null?'':String(r.data.claimCents/100)}),[payment,setPayment]=useState({amount:'',reference:'',date:today()});
 const [baseVersion,setBaseVersion]=useState(r.version);
 const own=r.owner_id===data.actor.id,admin=data.actor.role==='管理员',d=r.data,disabled=busy||uploading,files=data.files.filter((f:Row)=>f.record_id===r.id);
 useEffect(()=>{setHistory(null)},[r.version]);
 const perform=async(action:string,extra:Row={})=>{setLocalError('');const ok=await act({action,id:r.id,version:baseVersion,note,...extra});if(ok){setBaseVersion(baseVersion+1);setNote('');setPayment({amount:'',reference:'',date:today()})}return ok;};
 if(editing)return <CaseForm row={r} busy={busy} act={act} onCancel={()=>setEditing(false)}/>;
 return <section className="panel as-detail"><header className="as-heading"><div><h3>{r.sku} · {r.case_no}</h3><p>{r.business_date} · {r.owner_name} · {r.site} / {r.channel}</p></div><span className="pill">{labels[r.status]}</span></header><div className="as-detail-grid"><div><h4>客户反馈</h4><p>{d.reason} · {d.qty} 件</p><p>订单：{d.orderNo}</p><p>退款登记：{d.currency} {amount(d.refundCents)}</p><p className="as-prose">{d.description}</p></div><div><h4>追溯线索</h4><p>工厂：{d.factory||'待核实'}</p><p>仓库：{d.warehouse||'待核实'}</p><p>批次 / 凭证：{d.batch||'待核实'}</p><p>管理员确认：{d.responsibility?`${d.responsibility} · ${d.liableName}`:'尚未判定'}</p><p>{d.decision}</p></div></div><div className="as-evidence">{files.map((f:Row)=><a key={f.id} href={`/api/after-sales/files?id=${encodeURIComponent(f.id)}`} target="_blank" rel="noreferrer"><img src={`/api/after-sales/files?id=${encodeURIComponent(f.id)}`} alt={`售后证据：${f.name}`} loading="lazy"/><small>{f.name}</small><small>上传于 {new Date(f.created_at).toLocaleString('zh-CN')}</small></a>)}</div>
 {own&&r.status==='draft'&&<><label className="as-upload">上传截图或照片（JPG / PNG / WebP，最多6张，每张10MB）<input type="file" accept="image/jpeg,image/png,image/webp" disabled={disabled||files.length>=6} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);setLocalError('');try{const form=new FormData();form.append('recordId',r.id);form.append('file',file);const res=await fetch('/api/after-sales/files',{method:'POST',body:form});const v=await res.json();if(!res.ok)throw Error(v.error);await load();setBaseVersion(r.version+1)}catch(err){setLocalError(err instanceof Error?err.message:'上传失败')}finally{setUploading(false);e.target.value=''}}}/></label><div className="as-controls"><button className="btn" disabled={disabled} onClick={()=>setEditing(true)}>修改草稿</button><button className="btn primary" disabled={disabled||!files.length} onClick={()=>void perform('submit')}>提交售后反馈</button></div></>}
 <h4>运营改进措施</h4><p className="as-prose">{d.improvement||'尚未填写；客户取消或描述不符类，结案前须补充沟通 / 优化措施。'}</p>
 {d.claimCents!=null&&<p className="as-settlement">{d.currency} · 应赔 {amount(d.claimCents)} · 已赔 {amount(d.payments.reduce((s:number,p:Row)=>s+p.amountCents,0))} · 待赔 {amount(d.claimCents-d.payments.reduce((s:number,p:Row)=>s+p.amountCents,0))}</p>}
 {d.payments.length>0&&<div className="table-wrap"><table><thead><tr><th>赔付日期</th><th>实赔金额</th><th>凭证号</th><th>登记人 / 说明</th></tr></thead><tbody>{d.payments.map((p:Row)=><tr key={p.id}><td>{p.date}</td><td>{d.currency} {amount(p.amountCents)}</td><td>{p.reference}</td><td>{p.actor} · {p.note}</td></tr>)}</tbody></table></div>}
 {r.version!==baseVersion&&<div className="notice info">此记录已被更新，请核对最新状态后继续。<button className="btn" onClick={()=>{setBaseVersion(r.version);setDecision({responsibility:d.responsibility||'',liableName:d.liableName||'',claimAmount:d.claimCents==null?'':String(d.claimCents/100)})}}>采用最新版本</button></div>}
 {r.status!=='void'&&<div className="as-workflow"><label>处理意见 / 判定依据 / 改进措施（至少4字）<textarea rows={3} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="as-controls">{r.status!=='draft'&&<button className="btn" disabled={disabled||note.trim().length<4} onClick={()=>void perform('comment')}>补充处理意见</button>}{own&&!['draft','void'].includes(r.status)&&<button className="btn" disabled={disabled||note.trim().length<4} onClick={()=>void perform('improve')}>保存运营改进措施</button>}{admin&&r.status==='submitted'&&<button className="btn danger" disabled={disabled||note.trim().length<4} onClick={()=>void perform('return')}>退回运营补充</button>}{(own&&r.status==='draft'||admin&&['submitted','confirmed'].includes(r.status)&&!d.payments.length)&&<button className="btn danger" disabled={disabled||note.trim().length<4} onClick={()=>{if(window.confirm('将作废该记录并保留操作痕迹，不计入售后汇总，确认？'))void perform('void')}}>作废并留痕</button>}</div>
 {admin&&['submitted','confirmed'].includes(r.status)&&<div className="as-admin"><h4>管理员确认责任</h4><div className="as-fields"><label>责任类型<select value={decision.responsibility} onChange={e=>setDecision({...decision,responsibility:e.target.value})}><option value="">请选择责任类型</option>{responsibilities.map((x:string)=><option key={x}>{x}</option>)}</select></label><label>具体工厂 / 仓库 / 责任方<input maxLength={160} value={decision.liableName} onChange={e=>setDecision({...decision,liableName:e.target.value})}/></label><label>应赔金额 · {d.currency}<input type="number" min="0" step="0.01" value={decision.claimAmount} onChange={e=>setDecision({...decision,claimAmount:e.target.value})}/></label></div><button className="btn primary" disabled={disabled||note.trim().length<4} onClick={()=>void perform('confirm',decision)}>确认责任及应赔金额</button></div>}
 {admin&&r.status==='confirmed'&&<div className="as-admin"><h4>实际赔付登记</h4><p>只登记已经发生的赔付，不会自动发起转账。</p><div className="as-fields"><label>赔付日期<input type="date" max={today()} value={payment.date} onChange={e=>setPayment({...payment,date:e.target.value})}/></label><label>本次实赔 · {d.currency}<input type="number" min="0.01" step="0.01" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></label><label>赔付凭证号<input maxLength={160} value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></label></div><div className="as-controls"><button className="btn" disabled={disabled||note.trim().length<4} onClick={()=>void perform('payment',payment)}>登记本次实赔</button><button className="btn primary" disabled={disabled||note.trim().length<4} onClick={()=>void perform('close')}>核对后结案</button></div></div>}</div>}
 {uploading&&<p role="status">正在上传证据…</p>}{(localError||error)&&<div className="notice error" role="alert">{localError||error}</div>}
 <details onToggle={async e=>{if(e.currentTarget.open&&!history)try{setHistory(await request('/api/after-sales?history='+encodeURIComponent(r.id)))}catch(err){setError(err instanceof Error?err.message:'读取失败')}}}><summary>操作记录与协作意见</summary>{history?.map((h:Row,i:number)=><article className="as-history" key={i}><strong>{h.actor_name} · {({create:'登记草稿',save:'修订草稿',submit:'提交',upload:'上传证据',comment:'协作意见',confirm:'确认责任',payment:'登记实赔',close:'结案',void:'作废',return:'退回',improve:'改进措施'} as Row)[h.action.split('.').pop()||'']||h.action}</strong><small>{new Date(h.created_at).toLocaleString('zh-CN')}</small><p>{JSON.parse(h.detail_json).note||'已记录'}</p></article>)}</details>
 </section>;
}
