"use client";
import {useEffect,useState} from 'react';
import {addDays,reviewToday,reviewMetrics,derivedReviewMetrics,ratio} from '../lib/business-review-model.mjs';
import './business-reviews.css';
type Row=Record<string,any>;
const fmt=(v:any)=>v==null?'待补充':Number(v).toLocaleString('zh-CN',{maximumFractionDigits:2});
const percent=(v:any)=>v==null?'—':`${(v*100).toFixed(1)}%`;
const statusLabel:Row={missing:'未建立',draft:'草稿',submitted:'待复核',returned:'待修订',reviewed:'已复核',open:'待执行',done:'待验收',closed:'已完成',cancelled:'已取消'};
async function request(url:string,p?:Row){const res=await fetch(url,p?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}:{cache:'no-store'});const value=await res.json();if(!res.ok)throw Error(value.error||'操作失败');return value;}
function download(name:string,rows:any[][]){const escape=(v:any)=>`"${String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')}"`;const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(escape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function BusinessReviews(){
 const [unsaved,setUnsaved]=useState(false);
 const leave=()=>!unsaved||window.confirm('有未保存的报告内容，确认放弃并切换？');
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(unsaved){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[unsaved]);
 const [kind,setKind]=useState('weekly'),[date,setDate]=useState(reviewToday()),[data,setData]=useState<Row|null>(null),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('reports');
 async function load(){const value=await request(`/api/business-reviews?kind=${kind}&date=${date}`);setData(value);return value;}
 useEffect(()=>{let active=true;setData(null);setSelected('');setError('');request(`/api/business-reviews?kind=${kind}&date=${date}`).then(v=>{if(active)setData(v)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[kind,date]);
 const act=async(p:Row)=>{setBusy(true);setError('');try{const value=await request('/api/business-reviews',p);await load();if(value.id)setSelected(value.id);return true;}catch(e){setError(e instanceof Error?e.message:'操作失败');return false;}finally{setBusy(false)}};
 const chosen=data?.reports.find((r:Row)=>r.id===selected);
 const submitted=data?.obligations.filter((r:Row)=>['submitted','reviewed'].includes(r.status)).length||0;
 return <div className="business-reviews"><header className="review-heading"><div><h2>周报与月度复盘</h2><p>数据与目标 → 差异与根因 → 行动与验收</p></div><div className="review-controls"><select aria-label="报告类型" value={kind} onChange={e=>{if(leave()){setUnsaved(false);setKind(e.target.value);setDate(reviewToday());}}}><option value="weekly">经营周报</option><option value="monthly">月度会议</option></select><input aria-label="报告日期" type="date" value={date} max={reviewToday()} onChange={e=>{if(leave()){setUnsaved(false);setDate(e.target.value);}}}/><button className="btn" disabled={busy} onClick={()=>{if(!leave())return;setUnsaved(false);setError('');void load().catch(e=>setError(e.message));}}>刷新</button></div></header>
 {error&&<div className="notice error" role="alert">{error}</div>}
 {!data?<p>正在读取报告…</p>:<><div className="notice info">{data.period.start} 至 {data.period.end} · {kind==='weekly'?`大小休交替，${data.period.deadline} 北京时间15:00前提交，统计此前7个完整自然日`:'每月28日会议，会前完成材料'}。{data.period.partial?'当前周期未结束，系统数据最多取至昨日；月底可退回补全。':'完整统计周期。'} 报表注明原币种，不跨币种相加。</div>
 <div className="review-overview"><div><span>已提交 / 应提交</span><strong>{submitted} / {data.obligations.length}</strong><progress aria-label="报告提交进度" max={Math.max(1,data.obligations.length)} value={submitted}/></div><div><span>待修订 / 未提交</span><strong>{data.obligations.length-submitted}</strong></div><div><span>到期未完成行动</span><strong>{data.actions.filter((a:Row)=>a.status==='open'&&a.due_date<=reviewToday()).length}</strong></div></div>
 <nav className="review-tabs"><button className={`btn ${view==='reports'?'primary':''}`} onClick={()=>{if(leave()){setUnsaved(false);setView('reports')}}}>报告与会议</button><button className={`btn ${view==='actions'?'primary':''}`} onClick={()=>{if(leave()){setUnsaved(false);setView('actions')}}}>跨周行动跟踪</button>{data.canWrite&&<button className="btn primary" disabled={busy} onClick={()=>{if(leave()){setUnsaved(false);void act({action:'create',kind,date})}}}>打开本人报告</button>}<button className="btn" onClick={()=>download(`${kind}-${data.period.start}-会议汇总.csv`,[['姓名','站点','渠道','状态','数据截止日','结果总结','可复制经验','问题','根因','协作需求','下期结果'],...data.obligations.map((o:Row)=>{const r=data.reports.find((x:Row)=>x.owner_id===o.id);return [o.name,o.site,o.channel,statusLabel[o.status],r?.snapshot.asOf,r?.data.summary,r?.data.win,r?.data.problem,r?.data.rootCause,r?.data.support,r?.data.nextResult]})])}>导出会议汇总</button></nav>
 {view==='reports'?<><section className="panel"><h3>{kind==='monthly'?'月度会议准备清单':'本期提交清单'}</h3><div className="table-wrap"><table><thead><tr><th>责任人 / 站点</th><th>渠道</th><th>进度</th><th>操作</th></tr></thead><tbody>{data.obligations.map((o:Row)=><tr key={o.id}><td>{o.name}<small>{o.site}</small></td><td>{o.channel}</td><td><span className={`pill ${['submitted','reviewed'].includes(o.status)?'green':'red'}`}>{statusLabel[o.status]}{o.late?' · 已到期':''}</span></td><td>{o.reportId?<button className="btn" onClick={()=>{if(leave()){setUnsaved(false);setSelected(o.reportId)}}}>查看报告</button>:o.id===data.actor.id?<button className="btn" disabled={busy} onClick={()=>{if(leave()){setUnsaved(false);void act({action:'create',kind,date})}}}>开始填写</button>:'等待提交'}</td></tr>)}</tbody></table></div></section>
 {chosen&&<ReviewEditor key={`${chosen.id}-${chosen.version}`} row={chosen} data={data} act={act} busy={busy} onDirty={setUnsaved}/>}</>:<section className="panel"><h3>跨周行动跟踪</h3><p>所有周期的行动持续保留。负责人提交完成证据，管理员验收后才算关闭。</p><ActionList actions={data.actions} data={data} act={act} busy={busy}/></section>}</>}
 </div>;
}
function ActionList({actions,data,act,busy}:{actions:Row[];data:Row;act:(p:Row)=>Promise<boolean>;busy:boolean}){
 const update=(a:Row,status:string)=>{const note=window.prompt(status==='done'?'填写结果数字及证据/报表链接':'填写验收结论或处理原因');if(note)void act({action:'actionUpdate',id:a.report_id,version:a.report_version??data.reports.find((r:Row)=>r.id===a.report_id)?.version,actionId:a.id,actionVersion:a.version,status,note});};
 return <div className="review-action-list">{actions.length?actions.map(a=><article key={a.id} className={a.status==='open'&&a.due_date<reviewToday()?'overdue':''}><header><strong>{a.title}</strong><span className={`pill ${a.status==='closed'?'green':'red'}`}>{statusLabel[a.status]}{a.status==='open'&&a.due_date<reviewToday()?' · 逾期':''}</span></header><p>验收目标：{a.target}</p><small>{data.users.find((u:Row)=>u.id===a.owner_id)?.name||'历史账号'} · 截止 {a.due_date} · 来源 {a.period_start} {a.channel} · {a.priority==='high'?'高优先级':'正常优先级'}</small>{a.evidence&&<p>完成证据：{a.evidence}</p>}{a.review_note&&<p>复核意见：{a.review_note}</p>}<div className="review-tabs">{a.status==='open'&&a.owner_id===data.actor.id&&a.report_status!=='draft'&&<button className="btn primary" disabled={busy} onClick={()=>update(a,'done')}>提交完成证据</button>}{data.canReview&&a.status==='done'&&<><button className="btn" disabled={busy} onClick={()=>update(a,'closed')}>验收完成</button><button className="btn danger" disabled={busy} onClick={()=>update(a,'open')}>退回行动</button></>}{data.canReview&&['open','done'].includes(a.status)&&<button className="btn danger" disabled={busy} onClick={()=>update(a,'cancelled')}>取消并记录原因</button>}</div></article>):<p>暂无行动项</p>}</div>;
}
function ReviewEditor({row,data,act,busy,onDirty}:{row:Row;data:Row;act:(p:Row)=>Promise<boolean>;busy:boolean;onDirty:(v:boolean)=>void}){
 const [draft,setDraft]=useState<Row>(row.data),[dirty,setDirty]=useState(false),[action,setAction]=useState({title:'',target:'',ownerId:row.owner_id,dueDate:addDays(reviewToday(),7),priority:'normal'});
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false)},[dirty,onDirty]);
 const own=row.owner_id===data.actor.id,editable=own&&['draft','returned'].includes(row.status),s=row.snapshot||{},metrics=reviewMetrics(row.channel),manual=Object.fromEntries(metrics.map((m:Row)=>[m.key,draft.metrics?.[m.key]?.actual??null]));
 const currency=row.channel==='线下分销'?'IDR':({印尼:'IDR',马来西亚:'MYR',泰国:'THB',越南:'VND',菲律宾:'PHP'} as Row)[row.site];
 const amount=s.currencies?.find((r:Row)=>r.currency===currency),adCost=amount&&!amount.costMissing?amount.adCost:null,derived=derivedReviewMetrics(manual,manual.adSpend);
 const set=(key:string,value:any)=>{setDraft({...draft,[key]:value});setDirty(true)};
 const saveMetric=(key:string,field:string,value:any)=>set('metrics',{...draft.metrics,[key]:{...draft.metrics?.[key],[field]:value===''?null:field==='source'?value:Number(value)}});
 const review=(a:string)=>{const note=window.prompt(a==='review'?'填写复核结论和管理建议':'填写撤回/退回原因，月底补全可注明补充完整月度结果');if(note)void act({action:a,id:row.id,version:row.version,note});};
 return <section className="panel review-editor"><header className="review-heading"><div><h3>{row.owner_name} · {row.site} / {row.channel}</h3><p>{row.period_start} 至 {row.period_end} · V{row.version} · {statusLabel[row.status]}{dirty?' · 有未保存内容':''}</p></div><span className={`pill ${row.status==='reviewed'?'green':'red'}`}>{statusLabel[row.status]}</span></header>
 {row.review_note&&<div className="notice info">复核 / 修订意见：{row.review_note}</div>}
 <h4>系统经营数据</h4><p>{s.asOf?`数据截至 ${s.asOf}，${s.partial?'阶段结果':'完整周期'}。`:'尚未读取数据。'}{s.source} 本次读数时间：{s.generatedAt||'—'}。</p>
 {editable&&<button className="btn" disabled={busy||dirty} onClick={()=>act({action:'refreshSnapshot',id:row.id,version:row.version})}>读取最新系统数据</button>}{dirty&&<small>先保存填写内容，再读取数据或添加行动。</small>}
 <div className="review-overview"><div><span>销售净件数</span><strong>{fmt(s.quantity)}</strong></div>{row.channel==='线下分销'?<><div><span>有效拜访 / 新签客户</span><strong>{fmt(s.visits)} / {fmt(s.signed)}</strong></div><div><span>核销回款 IDR</span><strong>{fmt(s.receipts)}</strong></div></>:<div><span>已确认日报 / 应有天数</span><strong>{s.coverage??'—'} / {s.expectedDays??'—'}</strong></div>}{(s.currencies||[]).map((c:Row)=><div key={c.currency}><span>系统销售额 {c.currency}</span><strong>{fmt(c.revenue)}</strong><small>{c.revenueMissing?'包含金额缺失，不能视作完整销售额':''}广告费 {fmt(c.adCost)} · 全店销售额/广告费 {fmt(c.roas)}</small></div>)}</div>
 {s.previous&&<p>同期对照：{s.previous.from} 至 {s.previous.to}，销售 {fmt(s.previous.quantity)} 件；{s.previous.currencies.map((c:Row)=>`${c.currency} ${fmt(c.revenue)}${c.revenueMissing?'（金额缺失）':''}`).join('，')}。两期导入不完整时不据此判断增长。</p>}
 {s.skuRanking?.length>0&&<details><summary>热销 SKU 与件数排名</summary><div className="review-bars">{s.skuRanking.map((r:Row)=><div key={r.sku}><span>{r.sku}</span><progress aria-label={r.sku} max={Math.max(1,...s.skuRanking.map((x:Row)=>x.qty))} value={Math.max(0,r.qty)}/><strong>{fmt(r.qty)} 件</strong></div>)}</div></details>}
 <details open><summary>平台 / 业务补充指标与目标（金额：{currency}）</summary><p>系统销量不是订单数；平台 GMV、归因成交等请按平台报告填写，未知留空。每项实际值需注明数据来源。广告归因 ROAS 使用补充表内的平台广告 GMV / 同口径广告消耗；请确保币种、期间与归因窗口一致。优化前后率按百分数填，例如 2.5 表示2.5%。</p>{row.previous&&<p>上次提交期间：{row.previous.period_start} 至 {row.previous.period_end}。周报为滚动窗口，不可相加得到月报。</p>}<div className="table-wrap"><table><thead><tr><th>指标</th><th>本期目标</th><th>本期实际</th><th>达成率</th><th>上期实际 / 环比</th><th>下期目标</th><th>来源 / 口径</th></tr></thead><tbody>{metrics.map((m:Row)=>{const v=draft.metrics?.[m.key]||{};return <tr key={m.key}><td>{m.label}<small>{m.unit==='币种'?currency:m.unit}{m.direction==='down'?' · 越低越好':''}</small></td>{['target','actual'].map(f=><td key={f}>{editable?<input aria-label={`${m.label}${f==='target'?'本期目标':'本期实际'}`} type="number" min="0" step="any" value={v[f]??''} onChange={e=>saveMetric(m.key,f,e.target.value)}/>:fmt(v[f])}</td>)}<td>{m.direction==='down'?(v.actual==null||v.target==null?'—':v.actual<=v.target?'达标':'超出目标'):percent(ratio(v.actual,v.target))}</td><td>{fmt(row.previous?.data.metrics?.[m.key]?.actual)}<small>{percent(ratio(v.actual==null||row.previous?.data.metrics?.[m.key]?.actual==null?null:v.actual-row.previous.data.metrics[m.key].actual,row.previous?.data.metrics?.[m.key]?.actual))}</small></td><td>{editable?<input aria-label={`${m.label}下期目标`} type="number" min="0" step="any" value={v.nextTarget??''} onChange={e=>saveMetric(m.key,'nextTarget',e.target.value)}/>:fmt(v.nextTarget)}</td><td>{editable?<input aria-label={`${m.label}来源`} maxLength={300} value={v.source||''} onChange={e=>saveMetric(m.key,'source',e.target.value)}/>:v.source||'—'}</td></tr>})}</tbody></table></div></details>
 {row.channel!=='线下分销'&&<div className="review-ratios"><span>客单价 {fmt(derived.aov)}</span><span>转化率 {percent(derived.conversion)}</span>{row.channel==='Shopee'&&<span>点击率 {percent(derived.ctr)}</span>}<span>广告归因 ROAS {fmt(derived.adRoas)}</span><span>广告费率 {percent(derived.adRate)}</span><span>退款金额占 GMV {percent(derived.refundRate)}</span>{row.channel==='TikTok'?<span>直播 GMV 占比 {percent(derived.liveShare)}</span>:<><span>活动转化率 {percent(derived.campaignConversion)}</span><span>自然 GMV 占比 {percent(derived.naturalShare)}</span><span>CTR 提升 {fmt(derived.ctrChange)} 个百分点</span><span>CVR 提升 {fmt(derived.cvrChange)} 个百分点</span></>}</div>}
 <div className="review-narrative">{[['summary','本期目标与结果差异','用数字说明达成与差距'],['win','最值得复制的一件事','做对了什么，带来什么结果，如何复制'],['problem','最需要改进的问题','指出具体指标、SKU 或业务环节'],['rootCause','核心原因与证据','区分流量、转化、商品、履约、资源或协同'],['support','需要协作与管理决策','明确需要谁提供什么支持，何时需要'],['nextResult','下期必须取得的量化结果','数字目标与最后期限']].map(([key,label,placeholder])=><label key={key}>{label}{editable?<textarea value={draft[key]||''} maxLength={2000} onChange={e=>set(key,e.target.value)} placeholder={placeholder}/>:<p>{draft[key]||'未填写'}</p>}</label>)}</div>
 <div className="review-tabs">{editable&&<><button className="btn" disabled={busy} onClick={()=>act({action:'save',id:row.id,version:row.version,data:draft})}>保存草稿</button><button className="btn primary" disabled={busy} onClick={()=>act({action:'submit',id:row.id,version:row.version,data:draft})}>提交并锁定数据快照</button></>}{own&&row.status==='submitted'&&<button className="btn danger" disabled={busy} onClick={()=>review('withdraw')}>撤回修订</button>}{data.canReview&&!own&&row.status==='submitted'&&<button className="btn primary" disabled={busy} onClick={()=>review('review')}>复核通过</button>}{data.canReview&&!own&&['submitted','reviewed'].includes(row.status)&&<button className="btn danger" disabled={busy} onClick={()=>review('return')}>退回 / 月底补全</button>}</div>
 <h4>下期重点行动</h4><p>建议聚焦三项，每项写清动作、量化验收目标、责任人和期限。完成后仍需管理员验收。</p>
 {(editable||data.canReview)&&<div className="review-action-form"><label>具体动作<input value={action.title} maxLength={300} onChange={e=>setAction({...action,title:e.target.value})}/></label><label>量化验收目标<input value={action.target} maxLength={500} onChange={e=>setAction({...action,target:e.target.value})}/></label><label>负责人<select value={action.ownerId} onChange={e=>setAction({...action,ownerId:e.target.value})}>{data.users.map((u:Row)=><option key={u.id} value={u.id}>{u.name} · {u.role}</option>)}</select></label><label>截止日期<input type="date" value={action.dueDate} min={reviewToday()} onChange={e=>setAction({...action,dueDate:e.target.value})}/></label><label>优先级<select value={action.priority} onChange={e=>setAction({...action,priority:e.target.value})}><option value="normal">正常</option><option value="high">高</option></select></label><button className="btn" disabled={busy||dirty} onClick={()=>act({action:'addAction',id:row.id,version:row.version,...action})}>添加行动</button></div>}
 <ActionList actions={data.actions.filter((a:Row)=>a.report_id===row.id)} data={data} act={act} busy={busy}/>
 <details><summary>操作与修订记录</summary>{data.history.filter((h:Row)=>h.entity_id===row.id).map((h:Row,i:number)=><article key={i}><p>{h.created_at} · {h.actor_name} · {h.action} {h.detail.note||''}</p>{h.detail.data&&<details><summary>查看当时提交内容</summary><p>{h.detail.data.summary}</p><p>{h.detail.data.problem}</p><p>{h.detail.data.rootCause}</p><p>{h.detail.data.nextResult}</p><p>数据截止：{h.detail.snapshot?.asOf||'—'}</p></details>}</article>)}</details>
 </section>;
}
