"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {useWholesaleLanguage} from './wholesale-language';
// Permission-scoped response from the field sales API.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row=Record<string,any>;
type DevicePosition={latitude:number;longitude:number;accuracy:number;capturedAt:number};
function captureLocation():Promise<DevicePosition>{return new Promise((resolve,reject)=>{
 if(!navigator.geolocation)return reject(Error('设备不支持定位 / Perangkat tidak mendukung lokasi'));
 navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,capturedAt:p.timestamp}),e=>reject(Error(e.code===1?'请在手机浏览器设置允许本站定位 / Izinkan lokasi situs di pengaturan browser':'定位失败，请到室外重试 / Lokasi gagal, coba di luar ruangan')),{enableHighAccuracy:true,maximumAge:0,timeout:20000});
});}

const today=()=>new Date(Date.now()+7*3600000).toISOString().slice(0,10);
export default function FieldSales({month}:{month:string}){
 const {language,t,fmt,money,stamp}=useWholesaleLanguage(),l=(zh:string,id:string)=>language==='id'?id:zh;
 const [data,setData]=useState<Row|null>(null),[tab,setTab]=useState('visits'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[selected,setSelected]=useState(''),[person,setPerson]=useState(''),[query,setQuery]=useState(''),[reason,setReason]=useState('');
 const [form,setForm]=useState({kind:'visit',salesUserId:'',customerId:'',businessDate:today(),endDate:today(),visitType:'cold',leaveType:'sick',note:'',nextFollowup:'',contractNo:''});
 const [syncError,setSyncError]=useState(''),[locating,setLocating]=useState(false);
 const activePanel=useRef<HTMLElement|null>(null),[openSequence,setOpenSequence]=useState(0);
 useEffect(()=>{if(!selected)return;const frame=requestAnimationFrame(()=>{const node=activePanel.current;if(!node)return;node.scrollIntoView({block:'start',behavior:'auto'});node.querySelector<HTMLElement>('h4')?.focus({preventScroll:true});});return()=>cancelAnimationFrame(frame);},[selected,openSequence]);
 const openRecord=(id:string)=>{setSelected(id);setReason('');setOpenSequence(n=>n+1);};
 const retry=useRef<{key:string;id:string}|null>(null),generation=useRef(0);
 const load=useCallback(async()=>{const seq=++generation.current,r=await fetch(`/api/field-sales?month=${month}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);if(seq===generation.current){setData(d);setSyncError('');}},[month]);
 useEffect(()=>{setData(null);load().catch(e=>setNotice(e.message));return ()=>{generation.current++;};},[load]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')load().catch(()=>setSyncError(l('同步中断，正在显示上次数据','Sinkronisasi terputus, menampilkan data terakhir')));};const timer=setInterval(refresh,15000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[load,language]);
 const mutate=async(payload:Row)=>{setBusy(true);setNotice('');const key=JSON.stringify(payload);if(retry.current?.key!==key)retry.current={key,id:crypto.randomUUID()};try{const response=await fetch('/api/field-sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,operationId:retry.current.id})}),result=await response.json();if(!response.ok)throw Error(result.error);retry.current=null;setNotice(l('已保存，操作记录可追溯。','Tersimpan. Riwayat aktivitas tersedia.'));try{await load();}catch{setNotice(l('已保存，但刷新失败，请点击刷新；请勿重复创建。','Tersimpan tetapi pemuatan gagal. Muat ulang; jangan buat ulang.'));}return result;}catch(e){setNotice(e instanceof Error?e.message:String(e));return null;}finally{setBusy(false);}};
 const submitRecord=async(r:Row)=>{if(r.kind!=='visit')return mutate({action:'submit',id:r.id,version:r.version});setLocating(true);setNotice(l('正在获取现场GPS，请允许定位并稍候…','Mengambil GPS saat ini, izinkan lokasi…'));try{const location=await captureLocation();await mutate({action:'submit',id:r.id,version:r.version,location});}catch(e){setNotice(e instanceof Error?e.message:String(e));}finally{setLocating(false);}};
 const status=(s:string)=>({draft:l('草稿','Draf'),valid:l('有效','Valid'),review:l('待复核','Perlu verifikasi'),pending:l('待审批','Menunggu persetujuan'),approved:l('已批准','Disetujui'),active:l('已备案','Terarsip'),rejected:l('已驳回','Ditolak'),withdrawn:l('已撤回','Ditarik'),void:l('已作废','Dibatalkan'),met:l('达标','Tercapai'),short:l('未达标','Belum tercapai'),verify:l('待核实','Perlu diperiksa'),leave:l('已批准请假','Cuti disetujui'),weekend:l('休息日','Akhir pekan'),future:l('未到日期','Belum waktunya'),not_started:l('未入系统','Belum bergabung'),in_progress:l('今日进行中','Hari ini berlangsung')}[s]||s);
 const leaveName=(s:string)=>({sick:l('病假','Sakit'),personal:l('事假','Izin pribadi'),annual:l('年假','Cuti tahunan')}[s]||s);
 const kindName=(s:string)=>({visit:l('客户拜访','Kunjungan'),leave:l('请假','Cuti'),contract:l('签约合同','Kontrak')}[s]||s);
 const badge=(s:string)=><span className={`field-badge ${s}`}>{status(s)}</span>;
 const panel=(title:string,children:React.ReactNode,active=false)=><section key={title} ref={active?activePanel:undefined} style={active?{scrollMarginTop:100}:undefined} className="panel field-panel"><h4 tabIndex={active?-1:undefined}>{title}</h4>{children}</section>;
 const input=(key:keyof typeof form,label:string,type='text',required=true)=><label className="wh-field"><span>{label}</span><input type={type} required={required} value={form[key]} maxLength={key==='contractNo'?100:undefined} max={type==='date'&&form.kind!=='leave'&&key==='businessDate'?today():undefined} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
 async function exportAttendance(){if(!data)return;setBusy(true);try{const x=await import('xlsx'),book=x.utils.book_new(),make=(name:string,rows:unknown[][])=>x.utils.book_append_sheet(book,x.utils.aoa_to_sheet(rows),name);make(l('出勤汇总','Ringkasan'),[[l('销售','Sales'),l('月份','Bulan'),l('达标','Tercapai'),l('未达标','Belum tercapai'),l('待核实','Perlu diperiksa'),l('已批准请假','Cuti'),l('进行中','Berlangsung')],...data.attendance.map((a:Row)=>[a.name,month,a.summary.met,a.summary.short,a.summary.verify,a.summary.leave,a.summary.in_progress])]);make(l('每日明细','Harian'),[[l('销售','Sales'),l('日期','Tanggal'),l('状态','Status'),l('有效客户数','Pelanggan valid'),l('假别','Jenis cuti'),l('待复核拜访','Kunjungan diperiksa'),l('假期有拜访','Kunjungan saat cuti')],...data.attendance.flatMap((a:Row)=>a.days.map((d:Row)=>[a.name,d.date,status(d.status),d.count,leaveName(d.leave),d.pending,d.conflict?l('请核对','Periksa'):'']))]);make(l('请假记录','Permohonan'),[[l('销售','Sales'),l('开始','Mulai'),l('结束','Selesai'),l('假别','Jenis'),l('状态','Status'),l('原因','Alasan')],...data.records.filter((r:Row)=>r.kind==='leave').map((r:Row)=>[data.users.find((u:Row)=>u.id===r.sales_user_id)?.name,r.business_date,r.end_date,leaveName(r.data.leaveType),status(r.status),r.data.note])]);x.writeFile(book,`Attendance-${month}.xlsx`);}catch{setNotice(l('导出失败，请重试','Ekspor gagal. Coba lagi.'));}finally{setBusy(false);}}
 if(!data)return <section className="panel field-panel"><p role="status">{notice||l('正在读取外勤工作台…','Memuat ruang kerja sales…')}</p><button className="btn" onClick={()=>load().catch(e=>setNotice(e.message))}>{l('重新读取','Muat ulang')}</button></section>;
 const admin=data.actor.role==='管理员',sales=data.actor.role==='销售',write=admin||sales,visible=(r:Row)=>!person||r.sales_user_id===person;
 const current=data.records.find((r:Row)=>r.id===selected),owner=sales?data.actor.id:form.salesUserId;
 const recordFiles=(id:string)=>data.files.filter((f:Row)=>f.record_id===id);
 const contrib=data.contributions.filter((r:Row)=>!person||r.id===person),attend=data.attendance.filter((r:Row)=>!person||r.id===person);
 const records=data.records.filter((r:Row)=>visible(r)&&(tab==='contracts'?r.kind==='contract':r.kind==='visit'||r.kind==='leave')).sort((a:Row,b:Row)=>b.created_at.localeCompare(a.created_at));
 const due=data.followups.filter((r:Row)=>visible(r));
 const startForm=(kind:string)=>{if(selected==='new'&&form.kind===kind){setOpenSequence(n=>n+1);return;}setForm({...form,kind,customerId:'',note:'',contractNo:'',businessDate:today(),endDate:today()});openRecord('new');};
 const total=(key:string)=>contrib.reduce((s:number,r:Row)=>s+Number(r[key]||0),0);
 const filesView=(ids:Row[])=><div className="field-files">{ids.map(f=><a key={f.id} href={`/api/field-sales/files?id=${encodeURIComponent(f.id)}`} target="_blank" rel="noreferrer">{f.content_type.startsWith('image/')?<img loading="lazy" src={`/api/field-sales/files?id=${encodeURIComponent(f.id)}`} alt={l('带上传日期的照片','Foto bertanggal unggah')}/>:<span>PDF</span>}<small>{f.name}<br/>{stamp(f.created_at)}</small></a>)}</div>;
 return <div className="field-sales">
  <p className={`field-sync ${syncError?'error':''}`} role="status">{syncError||`${l('每15秒自动同步 · 最近成功','Sinkronisasi tiap 15 detik · Terakhir')}: ${stamp(data.syncedAt)}`}</p>{write&&tab==='visits'&&<div className="field-quick-actions"><button className="btn primary" onClick={()=>startForm('visit')}>{l('＋ 登记拜访','＋ Catat kunjungan')}</button><button className="btn" onClick={()=>startForm('leave')}>{l('申请请假','Ajukan cuti')}</button></div>}<div className="field-heading"><div><p className="wh-eyebrow">FIELD SALES · INDONESIA</p><h3>{l('外勤销售工作台','Ruang Kerja Sales Lapangan')}</h3><p>{l('每天3家不同客户 · 周末双休 · 时间按印尼西部 WIB','3 pelanggan berbeda per hari · Sabtu/Minggu libur · Waktu WIB')}</p></div><div className="wh-actions">{!sales&&<label>{l('销售人员','Sales')}<select value={person} onChange={e=>setPerson(e.target.value)}><option value="">{l('全体销售','Semua sales')}</option>{data.users.map((u:Row)=><option key={u.id} value={u.id}>{u.name}{u.active?'':l('（已停用）',' (nonaktif)')}</option>)}</select></label>}<button className="btn" disabled={busy} onClick={()=>load().catch(e=>setNotice(e.message))}>{l('刷新','Muat ulang')}</button></div></div>
  {notice&&<div role="status" className="wh-notice">{t(notice)}<button onClick={()=>setNotice('')} aria-label={l('关闭','Tutup')}>×</button></div>}
  <nav className="field-nav" aria-label={l('外勤功能','Menu lapangan')}>{[['visits',l('拜访与请假','Kunjungan & Cuti')],['attendance',l('出勤月历','Kalender Kehadiran')],...(data.actor.role==='供应链'?[]:[['contracts',l('合同备案','Arsip Kontrak')]]),['contribution',l('贡献看板','Kinerja Sales')],['shared',l('库存与新品','Stok & Produk Baru')]].map(([id,label])=><button key={id} className={tab===id?'active':''} aria-pressed={tab===id} onClick={()=>{setTab(id);setSelected('');setQuery('');}}>{label}</button>)}</nav>
  {(tab==='visits'||tab==='contracts')&&<>
   {panel(tab==='contracts'?l('签约合同档案','Arsip kontrak bertanda tangan'):l('今日目标与待跟进','Target hari ini & tindak lanjut'),<>
    <div className="wh-actions">{write&&<>{tab==='contracts'?<button className="btn primary" onClick={()=>startForm('contract')}>{l('＋ 备案合同','＋ Arsip kontrak')}</button>:<><button className="btn primary" onClick={()=>startForm('visit')}>{l('＋ 登记拜访','＋ Catat kunjungan')}</button><button className="btn" onClick={()=>startForm('leave')}>{l('申请请假','Ajukan cuti')}</button></>}</>}
    <span>{tab==='contracts'?l('已有签署文件 → 上传备案 → 管理员确认。客户资料与已有拜访照片自动关联。','Dokumen sudah ditandatangani → unggah → konfirmasi admin. Data pelanggan dan foto kunjungan ditautkan otomatis.'):l('提交时自动采集GPS；资料完整且定位正常的当天拜访自动有效，异常待复核。同客户同日计1家。','GPS diambil saat kirim. Data lengkap dan lokasi normal menjadi valid; kejanggalan perlu verifikasi. Satu pelanggan dihitung sekali per hari.')}</span></div>
    {tab==='visits'&&<><div className="field-goals">{data.attendance.filter((a:Row)=>!person||a.id===person).map((a:Row)=>{const day=a.days.find((d:Row)=>d.date===data.today);return day&&<article key={a.id}><strong>{a.name}</strong><b>{day.count}<small> / 3</small></b><progress max={3} value={Math.min(3,day.count)}/>{badge(day.status)}</article>;})}</div>{due.length>0&&<details className="field-reminder"><summary>{l('到期跟进提醒','Tindak lanjut jatuh tempo')} · {due.length}</summary>{due.map((r:Row)=><p key={r.id}><button className="field-link" onClick={()=>openRecord(r.id)}>{r.data.customer.name} · {r.data.nextFollowup}</button> — {r.data.customer.phone}</p>)}</details>}</>}
   </>)}
   {selected==='new'&&panel(kindName(form.kind),<form onSubmit={async e=>{e.preventDefault();const result=await mutate({action:'create',...form,salesUserId:owner});if(result)openRecord(result.id);}}><div className="wh-grid">
    {admin&&<label className="wh-field"><span>{l('销售人员','Sales')}</span><select required value={form.salesUserId} onChange={e=>setForm({...form,salesUserId:e.target.value,customerId:''})}><option value="">{l('请选择','Pilih')}</option>{data.users.filter((u:Row)=>u.active).map((u:Row)=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>}
    {form.kind!=='leave'&&<label className="wh-field"><span>{l('客户（新客户请先在客户档案新增）','Pelanggan (buat pelanggan baru di Data Pelanggan)')}</span><select required value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})}><option value="">{l('请选择客户','Pilih pelanggan')}</option>{data.customers.filter((c:Row)=>c.sales_user_id===owner).map((c:Row)=><option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</select></label>}
    {input('businessDate',form.kind==='leave'?l('开始日期','Tanggal mulai'):form.kind==='contract'?l('签约日期','Tanggal tanda tangan'):l('拜访日期','Tanggal kunjungan'),'date')}
    {form.kind==='leave'?<>{input('endDate',l('结束日期','Tanggal selesai'),'date')}<label className="wh-field"><span>{l('假别','Jenis cuti')}</span><select value={form.leaveType} onChange={e=>setForm({...form,leaveType:e.target.value})}>{['sick','personal','annual'].map(s=><option key={s} value={s}>{leaveName(s)}</option>)}</select></label></>:form.kind==='visit'?<><label className="wh-field"><span>{l('拜访类型','Jenis kunjungan')}</span><select value={form.visitType} onChange={e=>setForm({...form,visitType:e.target.value})}><option value="cold">{l('陌生拜访','Kunjungan awal')}</option><option value="followup">{l('跟进拜访','Kunjungan lanjutan')}</option></select></label>{input('nextFollowup',l('下次跟进日期','Tanggal tindak lanjut'),'date',false)}</>:input('contractNo',l('合同编号','Nomor kontrak'))}
    <label className="wh-field wh-wide"><span>{form.kind==='leave'?l('请假原因','Alasan cuti'):l('拜访描述 / 合同说明','Catatan kunjungan / kontrak')}</span><textarea required={form.kind!=='contract'} minLength={form.kind==='visit'?10:2} maxLength={2000} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label>
   </div>{form.customerId&&<p className="field-context">{data.customers.find((c:Row)=>c.id===form.customerId)?.address} · {data.customers.find((c:Row)=>c.id===form.customerId)?.contact} · {data.customers.find((c:Row)=>c.id===form.customerId)?.phone}</p>}<div className="wh-actions"><button className="btn primary" disabled={busy}>{l('保存草稿，继续上传 / 提交','Simpan draf, lanjut unggah / kirim')}</button><button className="btn" type="button" onClick={()=>setSelected('')}>{l('关闭','Tutup')}</button></div></form>,true)}
   {current&&panel(`${kindName(current.kind)} · ${current.data.customer?.name||leaveName(current.data.leaveType)}`,<>
    <div className="field-detail"><p>{badge(current.status)} · {current.business_date}{current.end_date!==current.business_date?' → '+current.end_date:''} · {data.users.find((u:Row)=>u.id===current.sales_user_id)?.name}</p><p>{current.data.customer?.address}<br/>{current.data.customer?.contact} {current.data.customer?.phone}</p><p>{current.data.note}</p>{current.data.location&&<div className="field-location"><strong>{l('现场GPS地址（不可手改）','Alamat GPS lokasi (tidak dapat diedit)')}</strong><p>{current.data.location.address} · ±{Math.round(current.data.location.accuracy)}m</p><p>{l('服务器接收时间','Diterima server')}: {stamp(current.data.location.receivedAt)}</p><a target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${current.data.location.latitude}&mlon=${current.data.location.longitude}#map=18/${current.data.location.latitude}/${current.data.location.longitude}`}>{l('在地图查看现场位置','Lihat lokasi di peta')}</a></div>}{current.data.contractNo&&<p>{l('合同编号','Nomor kontrak')}: {current.data.contractNo}</p>}{current.kind==='visit'&&<p>{current.data.visitType==='cold'?l('陌生拜访','Kunjungan awal'):l('跟进拜访','Kunjungan lanjutan')} · {l('提交时累计拜访次数','Jumlah kunjungan saat dikirim')}: {current.data.visitNumber||'—'} · {l('下次跟进','Tindak lanjut')}: {current.data.nextFollowup||'—'}</p>}
    {current.data.checks&&<p>{l('判定依据','Dasar penilaian')}: {current.data.checks.length?current.data.checks.map((s:string)=>s==='low_accuracy'?l('定位精度不足100米，待复核','Akurasi GPS lebih dari 100m, perlu verifikasi'):s==='shared_location'?l('同日不同客户位置接近，待复核','Pelanggan berbeda berlokasi dekat, perlu verifikasi'):s==='location_changed'?l('与客户历史位置偏离，待复核','Lokasi berbeda dari riwayat pelanggan'):s==='backdated'?l('补录，需人工核对日期','Entri mundur, periksa tanggal'):l('照片曾用于其他拜访，需核实','Foto digunakan pada kunjungan lain')).join('；'):l('现场GPS、联系人、电话、描述与当天照片完整','Alamat, kontak, telepon, catatan, dan foto hari ini lengkap')}</p>}
    {current.kind==='visit'&&<p className="wh-copy">{l('GPS由设备提供，不能完全排除模拟定位；仅在提交时采集，不后台追踪。照片日期是服务器上传时间，不等同于真实拍摄时间。自动有效仅代表符合资料规则，不证明真实到店。','GPS berasal dari perangkat dan dapat dipalsukan; diambil saat mengirim, tanpa pelacakan latar belakang. Tanggal foto adalah waktu unggah server, bukan waktu pengambilan. Valid otomatis berarti data memenuhi aturan, bukan bukti pasti kehadiran.')}</p>}</div>
    {filesView(recordFiles(current.id))}{current.kind==='contract'&&current.data.photoIds?.length>0&&<><h5>{l('自动关联的客户拜访照片','Foto kunjungan pelanggan terkait')}</h5>{filesView(data.files.filter((f:Row)=>current.data.photoIds.includes(f.id)))}</>}
    {write&&current.status==='draft'&&current.kind!=='leave'&&<label className="field-upload">{l('上传照片 / 已签署合同（最多6份，每份10MB）','Unggah foto / kontrak bertanda tangan (maks. 6 file, 10MB/file)')}<input type="file" capture={current.kind==='visit'?'environment':undefined} accept={current.kind==='visit'?'image/jpeg,image/png,image/webp':'image/jpeg,image/png,image/webp,application/pdf'} disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);const fd=new FormData();fd.set('recordId',current.id);fd.set('file',file);try{const response=await fetch('/api/field-sales/files',{method:'POST',body:fd}),result=await response.json();if(!response.ok)throw Error(result.error);await load();setNotice(l('上传完成，照片已添加服务器日期。','Unggah selesai. Foto diberi tanggal server.'));}catch(err){setNotice(err instanceof Error?err.message:String(err));}finally{setBusy(false);e.target.value='';}}}/></label>}
    {write&&<><label className="wh-field"><span>{l('复核 / 驳回 / 撤回 / 作废原因','Alasan verifikasi / penolakan / penarikan / pembatalan')}</span><input value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label><div className="wh-actions">{current.status==='draft'&&<button className="btn primary" disabled={busy||locating} onClick={()=>submitRecord(current)}>{locating?l('定位中…','Mengambil lokasi…'):current.kind==='visit'?l('获取现场GPS并提交','Ambil GPS & kirim'):l('提交','Kirim')}</button>}{admin&&((current.kind==='visit'&&['valid','review','rejected'].includes(current.status))||current.status==='pending')&&<><button className="btn primary" disabled={busy||reason.trim().length<2} onClick={()=>mutate({action:'review',id:current.id,version:current.version,decision:'approve',reason})}>{l('确认有效 / 批准','Valid / Setujui')}</button><button className="btn danger" disabled={busy||reason.trim().length<2} onClick={()=>mutate({action:'review',id:current.id,version:current.version,decision:'reject',reason})}>{l('驳回 / 判为无效','Tolak / Tidak valid')}</button></>}{['draft','pending','review'].includes(current.status)&&<button className="btn danger" disabled={busy||reason.trim().length<2} onClick={()=>mutate({action:'withdraw',id:current.id,version:current.version,reason})}>{l('撤回','Tarik')}</button>}{admin&&['active','approved'].includes(current.status)&&<button className="btn danger" disabled={busy||reason.trim().length<2} onClick={()=>mutate({action:'void',id:current.id,version:current.version,reason})}>{l('作废','Batalkan')}</button>}</div><small>{l('驳回、撤回与作废前请先填写原因。草稿填错可撤回后重新录入。','Isi alasan sebelum menolak, menarik, atau membatalkan. Draf salah dapat ditarik dan dibuat ulang.')}</small></>}
    <details><summary>{l('操作记录','Riwayat aktivitas')}</summary>{data.history.filter((h:Row)=>h.entity_id===current.id).map((h:Row,i:number)=>{const d=JSON.parse(h.detail_json);return <p key={i}>{stamp(h.created_at)} · {h.actor_name} · {({create:l('创建','Buat'),upload:l('上传','Unggah'),submit:l('提交','Kirim'),review:l('复核','Verifikasi'),withdraw:l('撤回','Tarik'),void:l('作废','Batalkan')} as Record<string,string>)[h.action.replace('field.','')]||h.action} · {d.after?.status?status(d.after.status):''} {d.reason||''}</p>;})}</details><button className="btn" onClick={()=>setSelected('')}>{l('关闭详情','Tutup detail')}</button>
   </>,true)}
   {panel(l('记录清单','Daftar catatan'),<><input className="field-search" placeholder={l('搜索客户、销售、合同编号','Cari pelanggan, sales, nomor kontrak')} aria-label={l('搜索记录','Cari catatan')} value={query} onChange={e=>setQuery(e.target.value)}/><div className="table-wrap"><table><thead><tr>{[l('日期 / 销售','Tanggal / Sales'),l('客户 / 类型','Pelanggan / Jenis'),l('地址 / 联系方式','Alamat / Kontak'),l('状态','Status'),l('操作','Tindakan')].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{records.filter((r:Row)=>JSON.stringify(r.data).toLowerCase().includes(query.toLowerCase())||(data.users.find((u:Row)=>u.id===r.sales_user_id)?.name||'').toLowerCase().includes(query.toLowerCase())).map((r:Row)=><tr key={r.id}><td>{r.business_date}<small>{data.users.find((u:Row)=>u.id===r.sales_user_id)?.name}</small></td><td>{r.data.customer?.name||leaveName(r.data.leaveType)}<small>{kindName(r.kind)} {r.data.contractNo||''}</small></td><td>{r.data.location?.address||r.data.customer?.address||`${r.business_date} → ${r.end_date}`}<small>{r.data.customer?.contact} {r.data.customer?.phone}</small></td><td>{badge(r.status)}</td><td><button className="btn" onClick={()=>openRecord(r.id)}>{l('查看 / 处理','Lihat / Proses')}</button></td></tr>)}</tbody></table></div>{!records.length&&<p className="wh-empty">{l('暂无记录。先建立客户档案，再登记拜访或合同。','Belum ada catatan. Buat data pelanggan sebelum kunjungan atau kontrak.')}</p>}</>)}
  </>}
  {tab==='attendance'&&<>{panel(l('月度出勤汇总','Ringkasan Kehadiran Bulanan'),<><p>{l('周六、周日不计应出勤；已批准请假单列。未满3家为未达标，无记录为待核实，不自动判旷工或扣薪。今日尚未结束显示进行中。','Sabtu/Minggu tidak dihitung. Cuti disetujui ditampilkan terpisah. Kurang dari 3 pelanggan belum mencapai target; tanpa catatan perlu diperiksa. Tidak otomatis absen atau potong gaji. Hari ini masih berlangsung.')}</p><button className="btn" disabled={busy} onClick={exportAttendance}>{l('导出月度出勤 Excel','Ekspor kehadiran bulanan Excel')}</button></>)}{attend.map((a:Row)=>panel(a.name,<><div className="field-summary">{Object.entries(a.summary).map(([s,n])=><span key={s}>{status(s)} <strong>{String(n)}</strong></span>)}</div><div className="field-calendar">{a.days.map((d:Row)=><article key={d.date} className={d.status}><time>{d.date.slice(5)}</time>{badge(d.status)}<strong>{d.count} / 3</strong>{d.leave&&<small>{leaveName(d.leave)}</small>}{d.pending>0&&<small>{l('待复核','Perlu verifikasi')} {d.pending}</small>}{d.conflict&&<small>{l('假期有拜访，请核对','Kunjungan saat cuti: periksa')}</small>}</article>)}</div></>))}</>}
  {tab==='contribution'&&<>
   <div className="field-kpis">{[[l('有效拜访客户人次','Kunjungan pelanggan valid'),fmt(total('visits'))],[l('新增签约客户','Pelanggan baru berkontrak'),fmt(total('signed'))],[l('实际出库数量','Jumlah terkirim'),fmt(total('quantity'))],[l('实际出库金额','Nilai terkirim'),money(total('amount'))],[l('已核销回款','Penerimaan dialokasikan'),money(total('receipts'))],[l('退款','Pengembalian uang'),money(total('refunds'))]].map(([label,v])=><article key={label}><span>{label}</span><strong>{v}</strong></article>)}</div>
   {panel(l('贡献口径','Dasar perhitungan'),<p>{l('拜访人次按每天不同客户去重，独立客户数按月去重；新增签约客户仅计首次有效备案合同。出库按实际发货日期，退货单列；回款按订单核销业务日期，冲销与解除核销扣减，不含未分配银行收款。历史订单归原销售，不随客户转交改变。','Kunjungan dihitung per pelanggan per hari; pelanggan unik per bulan. Pelanggan kontrak baru hanya dari kontrak terarsip pertama. Pengiriman menurut tanggal pengiriman; retur terpisah. Penerimaan berdasarkan alokasi pesanan dikurangi pembatalan/pelepasan alokasi, tanpa dana bank belum dialokasikan. Atribusi historis pesanan tetap pada sales asal.')}</p>)}
   {panel(l('销售贡献对比','Perbandingan Kinerja Sales'),<div className="field-bars">{[...contrib].sort((a:Row,b:Row)=>b.amount-a.amount).map((c:Row)=><div key={c.id}><div className="field-bar-title"><strong>{c.name}</strong><span>{money(c.amount)}</span></div><div className="field-track"><div style={{width:`${Math.max(0,c.amount)/Math.max(1,...contrib.map((r:Row)=>r.amount))*100}%`}}/></div><small>{l('独立客户','Pelanggan unik')} {c.clients} · {l('拜访人次','Kunjungan')} {c.visits} · {l('签约','Kontrak')} {c.signed} · {l('出库','Terkirim')} {fmt(c.quantity)} · {l('退货','Retur')} {fmt(c.returnQty)} / {money(c.returnAmount)} · {l('回款','Penerimaan')} {money(c.receipts)}</small></div>)}</div>)}
   {contrib.map((c:Row)=>panel(`${c.name} · ${l('SKU排名（净出库件数）','Peringkat SKU (unit terkirim neto)')}`,<>{!c.skus.length&&<p className="wh-empty">{l('本月暂无实际出库或退货','Belum ada pengiriman atau retur bulan ini')}</p>}<div className="field-bars">{c.skus.slice(0,10).map((s:Row,i:number)=><div key={s.sku}><div className="field-bar-title"><strong>{i+1}. {s.sku}</strong><span>{fmt(s.qty-s.returned)}</span></div><div className="field-track teal"><div style={{width:`${Math.max(0,s.qty-s.returned)/Math.max(1,...c.skus.map((r:Row)=>r.qty-r.returned))*100}%`}}/></div><small>{s.name} · {l('出库 / 退货','Terkirim / Retur')} {s.qty} / {s.returned}</small></div>)}</div>{c.skus.length>10&&<details><summary>{l('查看全部SKU','Lihat semua SKU')} ({c.skus.length})</summary>{c.skus.map((s:Row,i:number)=><p key={s.sku}>{i+1}. {s.sku} · {fmt(s.qty-s.returned)}</p>)}</details>}</>))}
  </>}
  {tab==='shared'&&<>
   {panel(l('总库存查询 · 只读','Pencarian Stok Total · Hanya Baca'),<><p>{l('账面可售库存含已预留；可用数按各库位扣除预留后汇总。印尼当前规则仅可从 TikTok / Shopee 的独立份额出库，最终以订单审批时库存为准。其他国家库存不能直接承诺交货。','Stok tercatat mencakup reservasi; stok tersedia setelah dikurangi reservasi per lokasi. Pengiriman Indonesia saat ini memakai alokasi terpisah TikTok/Shopee dan diverifikasi saat persetujuan pesanan. Stok negara lain bukan janji pengiriman.')}</p><input className="field-search" aria-label={l('搜索库存或新品','Cari stok atau produk')} placeholder={l('搜索 SKU / 商品','Cari SKU / produk')} value={query} onChange={e=>setQuery(e.target.value)}/><div className="table-wrap"><table><thead><tr>{['SKU',l('全站账面可售','Stok tercatat semua negara'),l('已预留','Direservasi'),l('全站可用','Tersedia semua negara'),l('印尼可用于线下','Tersedia grosir Indonesia'),l('待上架 / 隔离','Belum rak / Karantina'),l('更新时间','Diperbarui')].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{data.inventory.filter((s:Row)=>(s.sku+' '+s.name).toLowerCase().includes(query.toLowerCase())).map((s:Row)=><tr key={s.sku}><td>{s.sku}<small>{s.name}</small></td><td>{fmt(s.qty)}</td><td>{fmt(s.reserved)}</td><td>{fmt(s.available)}</td><td><strong>{fmt(s.indonesia)}</strong></td><td>{fmt(s.pending)} / {fmt(s.quarantine)}</td><td>{stamp(s.updated_at)}</td></tr>)}</tbody></table></div></>)}
   {panel(l('新品开发进度 · 只读','Progres Produk Baru · Hanya Baca'),<><p>{l('阶段截止日期为内部计划，不是承诺上市或交货日期。','Batas tahap adalah rencana internal, bukan janji peluncuran atau pengiriman.')}</p><div className="field-products">{data.products.filter((p:Row)=>(p.sku+' '+p.name).toLowerCase().includes(query.toLowerCase())).map((p:Row)=><article key={p.id}><strong>{p.sku}</strong><p>{p.name}</p><span>{({selection:l('选款立项','Seleksi'),parallel_test:l('调研与种草','Riset & uji pasar'),finance:l('财务测算','Evaluasi kelayakan'),sample:l('打板确认','Konfirmasi sampel'),research:l('调研与种草','Riset'),development:l('开发','Pengembangan'),sampling:l('打样','Sampel'),production:l('生产','Produksi'),launch:l('上市','Peluncuran')} as Record<string,string>)[p.stage]||p.stage}</span><small>{p.status==='completed'?l('已完成','Selesai'):p.status==='active'?l('进行中','Berlangsung'):p.status} · {l('当前阶段计划截止','Batas rencana tahap')}: {stamp(p.current_due_at)}</small></article>)}</div>{!data.products.length&&<p>{l('暂无新品项目','Belum ada proyek produk baru')}</p>}</>)}
  </>}
 </div>;
}
