"use client";
import {useState,useEffect} from 'react';
import {forecastPerformance} from '../lib/forecast-model.mjs';
type R=Record<string,any>;
const config=[['supplier','供应商','text',''],['transportMode','运输方式 sea／air／land','text','sea'],['productionDays','生产实际交期（天）','number',21],['transportDays','运输实际交期（天）','number',35],['safetyDays','安全库存天数','number',0],['reviewDays','复盘周期（天）','number',7],['serviceLevel','服务水平（0.8—0.999）','number',.95],['seasonFactor','季节系数','number',1],['lifecycle','生命周期 normal／new／declining／discontinued','text','normal'],['campaignFactor','活动系数','number',1],['campaignStart','活动开始','date',''],['campaignEnd','活动结束','date',''],['outlierMultiple','异常销量上限倍数','number',4],['minOrderQty','MOQ','number',1],['orderMultiple','整箱倍数','number',1],['capacityQty','产能上限（空为不限）','number',''],['warehouseQty','可接收入仓上限（空为不限）','number',''],['budgetAmount','本SKU预算（空为不限）','number',''],['unitCost','同币种单位成本','number',0],['currency','成本币种 CNY／IDR／USD','text','CNY'],['maxCoverDays','最大库存覆盖天数','number',120],['note','参数依据','text','']] as const;
const snake=(s:string)=>s.replace(/[A-Z]/g,m=>'_'+m.toLowerCase());
export default function ForecastSettings({data,act,busy}:{data:R;act:any;busy:boolean}){
 const actor=data.actor,[scope,setScope]=useState({sku:data.skuSettings[0]?.sku||'',site:actor.site||'印尼',channel:actor.channel||'TikTok'}),[form,setForm]=useState<R>(Object.fromEntries(config.map(([k,,,d])=>[k,d]))),[version,setVersion]=useState(0),[correction,setCorrection]=useState({businessDate:new Date().toISOString().slice(0,10),returnQty:0,stockout:false,excludeSpike:false,reason:''}),[month,setMonth]=useState(data.currentMonth);
 const current=data.supplyPolicies?.find((p:R)=>p.sku===scope.sku&&p.site===scope.site&&p.channel===scope.channel);
 useEffect(()=>{setVersion(current?.version||0);setForm(Object.fromEntries(config.map(([k,,,d])=>[k,current?.[snake(k)]??d])));},[current?.version,scope.sku,scope.site,scope.channel]);
 if(!['管理员','供应链','运营','运营主管'].includes(actor.role))return null;
 const history=(data.forecastHistory||[]).filter((r:R)=>r.month===month),perf=forecastPerformance(history);
 const choose=(next:typeof scope)=>{setScope(next);const p=data.supplyPolicies.find((r:R)=>r.sku===next.sku&&r.site===next.site&&r.channel===next.channel);setVersion(p?.version||0);setForm(Object.fromEntries(config.map(([k,,,d])=>[k,p?.[snake(k)]??d])));};
 return <section className="panel"><h3>站点供应参数与预测复盘</h3><p>参数按 SKU＋站点＋渠道保存，供应商与运输方式随版本记录。预算、仓容和产能均为分配给该 SKU 的额度；活动仅对有效日期生效。</p><div className="form-grid"><label>SKU<select value={scope.sku} onChange={e=>choose({...scope,sku:e.target.value})}><option value="">请选择</option>{data.skuSettings.map((r:R)=><option key={r.sku}>{r.sku}</option>)}</select></label><label>站点<select disabled={actor.role==='运营'} value={scope.site} onChange={e=>choose({...scope,site:e.target.value})}>{['印尼','马来西亚','泰国','越南','菲律宾'].map(s=><option key={s}>{s}</option>)}</select></label><label>渠道<select disabled={actor.role==='运营'} value={scope.channel} onChange={e=>choose({...scope,channel:e.target.value})}><option>TikTok</option><option>Shopee</option></select></label></div>
 {actor.role!=='运营'&&<details><summary>维护供应参数 · V{version}</summary><div className="form-grid">{config.map(([k,label,type])=><label key={k}>{label}<input type={type} step="any" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><button className="btn primary" disabled={busy||!scope.sku} onClick={()=>act('supplyPolicySave',{...scope,...form,version},'供应参数已保存')}>保存参数</button></details>}
 <details><summary>登记需求修正</summary><p>修正用于需求预测，不直接修改库存和财务销售。退货实物仍需办理退货入库。</p><label>业务日期<input type="date" value={correction.businessDate} onChange={e=>setCorrection({...correction,businessDate:e.target.value})}/></label><label>当日退货数量<input type="number" min="0" value={correction.returnQty} onChange={e=>setCorrection({...correction,returnQty:Number(e.target.value)})}/></label><label><input type="checkbox" checked={correction.stockout} onChange={e=>setCorrection({...correction,stockout:e.target.checked})}/>当日断货（从需求均值分母剔除）</label><label><input type="checkbox" checked={correction.excludeSpike} onChange={e=>setCorrection({...correction,excludeSpike:e.target.checked})}/>排除异常爆量日</label><label>依据与原因<textarea value={correction.reason} onChange={e=>setCorrection({...correction,reason:e.target.value})}/></label><button className="btn" disabled={busy||correction.reason.length<4} onClick={()=>act('demandCorrectionSave',{...scope,...correction},'需求修正已记录')}>保存当日修正</button></details>
 <label>复盘月份<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><p>加权预测准确率 {perf.accuracy===null?'无实际销量，暂不计算':`${(perf.accuracy*100).toFixed(1)}%`}；偏差 {perf.bias===null?'—':`${(perf.bias*100).toFixed(1)}%`}。正偏差表示高估；未结束月份为进行中数据。</p><div className="table-wrap"><table><thead><tr><th>SKU／站点／渠道</th><th>系统备货建议</th><th>运营提交</th><th>批准数量</th><th>预测月销量</th><th>实际净销量</th></tr></thead><tbody>{history.map((r:R)=><tr key={r.id}><td>{r.sku}／{r.site}／{r.channel}</td><td>{r.system_qty}</td><td>{r.operator_qty}</td><td>{r.approved_qty??'待审批'}</td><td>{Math.round(r.forecast_sales)}</td><td>{r.actual_sales}</td></tr>)}</tbody></table></div></section>
}
