"use client";
import {useState,useEffect} from 'react';
import {forecastPerformance} from '../lib/forecast-model.mjs';
type R=Record<string,any>;
const config=[['supplier','供应商','text',''],['transportMode','运输方式','text','sea'],['productionDays','生产实际交期（天）','number',21],['transportDays','运输实际交期（天）','number',35],['safetyDays','安全库存天数','number',0],['reviewDays','复盘周期（天）','number',7],['serviceLevel','服务水平（0.8—0.999）','number',.95],['seasonFactor','季节系数','number',1],['lifecycle','产品生命周期','text','normal'],['campaignFactor','活动系数','number',1],['campaignStart','活动开始','date',''],['campaignEnd','活动结束','date',''],['outlierMultiple','异常销量上限倍数','number',4],['minOrderQty','最小起订量（件）','number',1],['orderMultiple','整箱倍数','number',1],['capacityQty','产能上限（空为不限）','number',''],['warehouseQty','可接收入仓上限（空为不限）','number',''],['budgetAmount','本SKU预算（空为不限）','number',''],['unitCost','同币种单位成本','number',0],['currency','成本币种','text','CNY'],['maxCoverDays','最大库存覆盖天数','number',120],['note','参数依据','text','']] as const;
const snake=(s:string)=>s.replace(/[A-Z]/g,m=>'_'+m.toLowerCase());

const groups=[{title:'交期与库存保障',hint:'按实际交期与服务目标设置备货周期。',keys:['supplier','transportMode','productionDays','transportDays','safetyDays','reviewDays','serviceLevel','maxCoverDays']},{title:'需求与活动',hint:'活动系数仅在有效日期内生效。',keys:['lifecycle','seasonFactor','outlierMultiple','campaignFactor','campaignStart','campaignEnd']},{title:'采购与预算约束',hint:'预算、产能和仓容填写分配给当前 SKU 的额度。',keys:['minOrderQty','orderMultiple','capacityQty','warehouseQty','budgetAmount','unitCost','currency','note']}];
const options:Record<string,[string,string][]>= {transportMode:[['sea','海运'],['air','空运'],['land','陆运']],lifecycle:[['normal','常规销售'],['new','新品'],['declining','衰退期'],['discontinued','已停售']],currency:[['CNY','人民币 CNY'],['IDR','印尼盾 IDR'],['USD','美元 USD']]};
const yesterday=()=>new Date(Date.now()+8*3600000-86400000).toISOString().slice(0,10);
export default function ForecastSettings({data,act,busy}:{data:R;act:any;busy:boolean}){
 const actor=data.actor,[scope,setScope]=useState({sku:data.skuSettings[0]?.sku||'',site:actor.site||'印尼',channel:actor.channel||'TikTok'}),[form,setForm]=useState<R>(Object.fromEntries(config.map(([k,,,d])=>[k,d]))),[version,setVersion]=useState(0),[correction,setCorrection]=useState({businessDate:yesterday(),returnQty:0,stockout:false,excludeSpike:false,reason:''}),[month,setMonth]=useState(data.currentMonth),[onlyScope,setOnlyScope]=useState(false),[error,setError]=useState('');
 const current=data.supplyPolicies?.find((p:R)=>p.sku===scope.sku&&p.site===scope.site&&p.channel===scope.channel);
 useEffect(()=>{setVersion(current?.version||0);setForm(Object.fromEntries(config.map(([k,,,d])=>[k,current?.[snake(k)]??d])));setError('');},[current?.version,scope.sku,scope.site,scope.channel]);
 if(!['管理员','供应链','运营','运营主管'].includes(actor.role))return null;
 const history=(data.forecastHistory||[]).filter((r:R)=>r.month===month&&(!onlyScope||(r.sku===scope.sku&&r.site===scope.site&&r.channel===scope.channel))),perf=forecastPerformance(history);
 const save=async(action:string,payload:R,message:string)=>{setError('');return act(action,payload,message,setError);};
 return <section className="panel forecast-settings"><div className="forecast-heading"><div><span className="section-eyebrow">供应决策 · 参数与复盘</span><h3>站点供应参数与预测复盘</h3><p>先选择 SKU 和销售范围，再维护供应参数或登记需求修正。每次保存均保留操作记录。</p></div><span className="pill blue">{version?'参数版本 V'+version:'使用默认参数'}</span></div>
 <div className="forecast-scope maintenance-grid"><label className="scope-sku">商品 SKU<select value={scope.sku} onChange={e=>setScope({...scope,sku:e.target.value})}><option value="">请选择商品</option>{data.skuSettings.map((r:R)=><option key={r.sku} value={r.sku}>{r.sku} · {r.name}</option>)}</select></label><label>站点<select disabled={actor.role==='运营'} value={scope.site} onChange={e=>setScope({...scope,site:e.target.value})}>{['印尼','马来西亚','泰国','越南','菲律宾'].map(s=><option key={s}>{s}</option>)}</select></label><label>渠道<select disabled={actor.role==='运营'} value={scope.channel} onChange={e=>setScope({...scope,channel:e.target.value})}><option>TikTok</option><option>Shopee</option></select></label></div>
 {actor.role!=='运营'&&<details className="forecast-section" open><summary><span>01 · 供应参数</span><small>交期、需求系数与采购约束</small></summary><div className="forecast-section-body">{groups.map(group=><fieldset key={group.title}><legend>{group.title}</legend><p>{group.hint}</p><div className="maintenance-grid">{config.filter(([k])=>group.keys.includes(k)).map(([k,label,type])=><label key={k} className={k==='note'?'wide':''}>{label}{options[k]?<select value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}>{options[k].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:<input type={type} min={type==='number'?'0':undefined} step="any" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</label>)}</div></fieldset>)}<div className="maintenance-actions"><span className="muted">保存范围：{scope.site} · {scope.channel} · {scope.sku||'未选择 SKU'}</span><button className="btn primary" disabled={busy||!scope.sku} onClick={()=>save('supplyPolicySave',{...scope,...form,version},'供应参数已保存')}>保存供应参数</button></div></div></details>}
 <details className="forecast-section"><summary><span>02 · 需求修正</span><small>修正预测依据，不改变库存与财务销售</small></summary><div className="forecast-section-body"><p className="notice">仅用于需求预测。退货实物仍需办理退货入库；同一 SKU、日期与渠道再次保存会更新该日修正。</p><div className="maintenance-grid"><label>业务日期<input type="date" value={correction.businessDate} onChange={e=>setCorrection({...correction,businessDate:e.target.value})}/></label><label>当日退货数量<input type="number" min="0" step="1" value={correction.returnQty} onChange={e=>setCorrection({...correction,returnQty:Number(e.target.value)})}/></label></div><div className="forecast-toggles"><label><input type="checkbox" checked={correction.stockout} onChange={e=>setCorrection({...correction,stockout:e.target.checked})}/><span><strong>当日断货</strong><small>从需求均值的有效天数中剔除</small></span></label><label><input type="checkbox" checked={correction.excludeSpike} onChange={e=>setCorrection({...correction,excludeSpike:e.target.checked})}/><span><strong>异常爆量</strong><small>排除不具有代表性的销量峰值</small></span></label></div><div className="maintenance-grid"><label className="wide">依据与原因<textarea value={correction.reason} placeholder="请填写核对依据，至少4个字" onChange={e=>setCorrection({...correction,reason:e.target.value})}/></label></div><div className="maintenance-actions"><button className="btn primary" disabled={busy||!scope.sku||correction.reason.trim().length<4} onClick={()=>save('demandCorrectionSave',{...scope,...correction},'需求修正已记录')}>保存当日修正</button></div></div></details>
 {error&&<p className="notice error" role="alert">{error}</p>}
 <div className="forecast-review"><div className="forecast-heading"><div><h4>03 · 预测复盘</h4><p>比较系统预测与实际净销量，持续校准备货参数。</p></div><label className="month-control">复盘月份<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div><label className="report-toggle"><input type="checkbox" checked={onlyScope} onChange={e=>setOnlyScope(e.target.checked)}/>只看当前 SKU、站点和渠道</label><div className="forecast-metrics"><article><small>加权预测准确率</small><strong>{perf.accuracy===null?'—':`${(perf.accuracy*100).toFixed(1)}%`}</strong><p>无实际销量时不计算</p></article><article><small>预测偏差</small><strong>{perf.bias===null?'—':`${perf.bias>0?'+':''}${(perf.bias*100).toFixed(1)}%`}</strong><p>正值为高估，负值为低估</p></article><article><small>复盘记录</small><strong>{history.length.toLocaleString()}<em> 条</em></strong><p>{month>=data.currentMonth?'月份尚未结束，结果持续更新':'所选月份历史记录'}</p></article></div><div className="table-wrap"><table><thead><tr><th>SKU / 站点 / 渠道</th><th>系统备货建议</th><th>运营提交</th><th>批准数量</th><th>预测月销量</th><th>实际净销量</th></tr></thead><tbody>{history.map((r:R)=><tr key={r.id}><td><strong>{r.sku}</strong><small>{r.site} · {r.channel}</small></td><td>{r.system_qty}</td><td>{r.operator_qty}</td><td>{r.approved_qty??'待审批'}</td><td>{Math.round(r.forecast_sales)}</td><td>{r.actual_sales}</td></tr>)}{!history.length&&<tr><td colSpan={6} className="empty">当前范围暂无复盘记录，提交月度需求后生成。</td></tr>}</tbody></table></div></div></section>;
}
