"use client";
import {useState} from 'react';
type R=Record<string,any>;
export function SupplyPicker({users,value,onChange}:{users:R[];value:string;onChange:(v:string)=>void}){return <label>供应链负责人<select value={value} onChange={e=>onChange(e.target.value)}><option value="">请选择负责人</option>{users.filter(u=>u.role==='供应链'&&u.active).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>}
export function PurchaseReassign({data,order,act,busy}:{data:R;order:R;act:any;busy:boolean}){const [s,setS]=useState('');return data.actor.role==='管理员'&&!['completed','cancelled'].includes(order.status)?<details><summary>指派负责人</summary><SupplyPicker users={data.users} value={s} onChange={setS}/><button className="btn" disabled={busy||!s} onClick={()=>{const reason=window.prompt('请填写重新指派原因');if(reason)void act('purchaseReassign',{purchaseOrderId:order.id,updatedAt:order.updated_at,supplyUserId:s,reason},'采购负责人已更新');}}>保存指派</button></details>:null}
export default function PlanChanges({data,act,busy}:{data:R;act:any;busy:boolean}){
 const [selected,setSelected]=useState(''),[rows,setRows]=useState<R[]>([]),[reason,setReason]=useState(''),[supply,setSupply]=useState('');
 if(!['管理员','供应链'].includes(data.actor.role))return null;const approvals=data.approvals.filter((a:R)=>a.status==='approved'),base=approvals.find((a:R)=>a.id===selected);
 const select=(id:string)=>{setSelected(id);const a=approvals.find((a:R)=>a.id===id);setRows((a?.payload?.items||[]).flatMap((r:R)=>r.allocations.map((p:R)=>({...p,sku:r.sku,name:r.name}))));};
 return <section className="panel"><h3>已批准计划变更</h3><p>记录原版、变更后数量和原因，交由另一位管理员审批。已确认下单或生产的数量不能减少；未执行草稿保留撤销记录。</p><label>选择原计划<select value={selected} onChange={e=>select(e.target.value)}><option value="">请选择</option>{approvals.map((a:R)=><option key={a.id} value={a.id}>{a.month} · V{a.version}</option>)}</select></label>{base&&<><div className="table-wrap"><table><thead><tr><th>SKU</th><th>站点</th><th>渠道</th><th>新数量</th><th/></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><input aria-label="变更SKU" value={r.sku} onChange={e=>setRows(rows.map((x,j)=>i===j?{...x,sku:e.target.value}:x))}/></td><td><select aria-label="变更站点" value={r.site} onChange={e=>setRows(rows.map((x,j)=>i===j?{...x,site:e.target.value}:x))}>{['印尼','马来西亚','泰国','越南','菲律宾'].map(s=><option key={s}>{s}</option>)}</select></td><td><select aria-label="变更渠道" value={r.channel} onChange={e=>setRows(rows.map((x,j)=>i===j?{...x,channel:e.target.value}:x))}><option>TikTok</option><option>Shopee</option></select></td><td><input aria-label="变更数量" type="number" min="0" value={r.qty} onChange={e=>setRows(rows.map((x,j)=>i===j?{...x,qty:e.target.value}:x))}/></td><td><button className="btn" onClick={()=>setRows(rows.filter((_,j)=>i!==j))}>移除</button></td></tr>)}</tbody></table></div><button className="btn" onClick={()=>setRows([...rows,{sku:'',site:'印尼',channel:'TikTok',qty:1}])}>增加明细</button><p>原计划 {(base.payload?.items||[]).reduce((s:number,r:R)=>s+r.total,0)} 件 → 新计划 {rows.reduce((s,r)=>s+Number(r.qty),0)} 件</p><label>变更原因<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="btn primary" disabled={busy||reason.length<4} onClick={()=>act('planChangeSubmit',{approvalId:base.id,version:base.version,rows,reason},'变更申请已提交')}>提交变更审批</button></>}
 <SupplyPicker users={data.users} value={supply} onChange={setSupply}/>{(data.planChanges||[]).map((c:R)=>{const old=JSON.parse(c.old_json),next=JSON.parse(c.new_json);return <details key={c.id}><summary>{c.month} · V{c.base_version} · {c.status} · {c.reason}</summary><div className="table-wrap"><table><thead><tr><th>SKU / 站点 / 渠道</th><th>原数量</th><th>新数量</th><th>差异</th></tr></thead><tbody>{[...new Set([...old.items,...next.items].flatMap((r:R)=>r.allocations.map((a:R)=>`${r.sku}|${a.site}|${a.channel}`)))].map((key:any)=>{const get=(v:R)=>v.items.flatMap((r:R)=>r.allocations.map((a:R)=>({key:`${r.sku}|${a.site}|${a.channel}`,qty:a.qty}))).find((x:R)=>x.key===key)?.qty||0;return <tr key={key}><td>{key}</td><td>{get(old)}</td><td>{get(next)}</td><td>{get(next)-get(old)}</td></tr>})}</tbody></table></div>{c.status==='pending'&&data.actor.role==='管理员'&&c.creator_id!==data.actor.id&&['approve','reject'].map(d=><button key={d} className="btn" disabled={busy||(d==='approve'&&!supply)} onClick={()=>{const note=window.prompt('请输入审批意见');if(note)void act('planChangeDecide',{changeId:c.id,version:c.version,decision:d,supplyUserId:supply,reason:note},'变更审批已记录');}}>{d==='approve'?'批准变更':'驳回变更'}</button>)}<p>{c.decision_note}</p></details>})}</section>
}
