"use client";
import {useEffect,useState} from "react";
type Row=Record<string,any>;
export default function PlanInventoryCheck({row,onChange,goInventory}:{row:Row;onChange:(value:Row|null)=>void;goInventory?:(scope:Row)=>void}){
 const [check,setCheck]=useState<Row|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false),[ack,setAck]=useState(false);
 const load=async()=>{setLoading(true);setError("");setCheck(null);setAck(false);onChange(null);try{const response=await fetch("/api/system",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"checkPlanApproval",approvalId:row.id,version:row.version})});const value=await response.json();if(!response.ok)throw new Error(value.error||"检查失败，请重试");setCheck(value);onChange({...value,ack:false});}catch(e){setError(e instanceof Error?e.message:"检查失败，请重试");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[row.id,row.version]); // A fresh review is required whenever the plan changes.
 const download=()=>{if(!check)return;const cell=(v:unknown)=>`"${String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')}"`;const rows=[["级别","SKU","站点","渠道","账面","预留","待上架","隔离","原因"],...check.issues.map((r:Row)=>[r.level==="blocking"?"阻止审批":"需确认",r.sku,r.site,r.channel,r.qty,r.reserved_qty,r.pending_shelf_qty,r.quarantine_qty,r.reason])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${row.month}-计划库存异常.csv`;a.click();URL.revokeObjectURL(url);};
 return <section aria-label="审批库存检查"><h4>计划库存检查</h4><p>仅显示本计划涉及的异常。批准备货不会修正库存，也不会解除库存预留。</p><button type="button" className="btn" disabled={loading} onClick={load}>{loading?"正在检查全部 SKU…":"重新检查"}</button>{error&&<p role="alert">{error}</p>}{check&&<><div className={`notice ${check.blocking?'error':check.warnings?'warn':'info'}`}>已检查 {check.snapshot.length} 个 SKU / 站点 / 渠道；阻止审批 {check.blocking} 项，负库存预警 {check.warnings} 项。</div>{check.issues.length>0&&<><button type="button" className="btn" onClick={download}>导出全部异常</button><div className="table-wrap"><table><thead><tr><th>SKU / 站点 / 渠道</th><th>账面 / 预留 / 待上架 / 隔离</th><th>原因</th><th>处理</th></tr></thead><tbody>{check.issues.map((r:Row)=><tr key={JSON.stringify([r.sku,r.site,r.channel])}><td>{r.sku}<div>{r.site} · {r.channel}</div></td><td>{r.qty} / {r.reserved_qty} / {r.pending_shelf_qty} / {r.quarantine_qty}</td><td><strong>{r.level==='blocking'?'必须处理':'需确认'}</strong>：{r.reason}</td><td>{goInventory&&<button type="button" className="btn" onClick={()=>goInventory(r)}>查看库存</button>}</td></tr>)}</tbody></table></div></>}{check.warnings>0&&!check.blocking&&<label><input type="checkbox" checked={ack} onChange={e=>{setAck(e.target.checked);onChange({...check,ack:e.target.checked});}}/> 我已核对上述负库存，确认继续备货，并在批准意见中说明依据；库存差异另行处理。</label>}</>}</section>;
}
