"use client";
import {useState,useRef,useEffect} from 'react';
import {hasPermission} from '../lib/permissions.mjs';
import {SALES_CURRENCIES,SITE_CURRENCIES,normalizeSales} from '../lib/sales-data.mjs';
import TableImport from './table-import';
type R=Record<string,any>;
export default function SalesImportHistory({data,act,busy}:{data:R;act:any;busy:boolean}){
 const [selected,setSelected]=useState<R|null>(null),[mode,setMode]=useState(''),[rows,setRows]=useState<R[]>([]),[date,setDate]=useState(''),[ref,setRef]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[page,setPage]=useState(0);
 const editor=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(selected)editor.current?.scrollIntoView({behavior:'smooth',block:'center'});},[selected,mode]);
 const canEdit=hasPermission(data.actor.role,'sales.correct'),canDelete=hasPermission(data.actor.role,'sales.reverse');
 const open=async(row:R,next:string)=>{setSelected(row);setMode(next);setError('');setReason('');setDate(row.business_date);setRef(row.source_batch_ref);setRows([]);setPage(0);if(next==='delete')return;setLoading(true);try{const response=await fetch(`/api/system?salesImportId=${encodeURIComponent(row.id)}`),body=await response.json();if(!response.ok)throw Error(body.error||'读取失败');if(body.source.reversed_at)throw Error('该批次已被修改或删除，请刷新');setRows(body.rows.map((r:R)=>({sku:r.sku,name:r.name,qty:r.qty,amount:r.reported_amount??'',adCost:r.ad_cost??'',currency:r.currency||''})));}catch(e){setError(e instanceof Error?e.message:'读取失败');}finally{setLoading(false);}};
 const save=async()=>{setError('');const result=await act(mode==='edit'?'correctSalesImport':'reverseSalesImport',{importId:selected?.id,businessDate:date,sourceBatchRef:ref,rows,reason},mode==='edit'?'销售批次已修订，库存已同步校正，请重新核对日报':'批次已删除并冲销，原记录和库存流水保留',setError);if(result){setSelected(null);setMode('');}};
 const update=(i:number,key:string,value:string)=>setRows(rows.map((r,j)=>i===j?{...r,[key]:value}:r));
 return <section className="panel sales-maintenance"><div className="panel-head"><div><h4>最近导入批次</h4><p>修改后原批次冲销并生成修订批次；删除恢复对应库存，历史可追溯。销量变更后须重新确认日报完整。</p></div></div>
 <div className="table-wrap import-history-table"><table><thead><tr><th>销售日期</th><th>站点 / 渠道</th><th>来源 / 文件</th><th>SKU / 件数</th><th>状态</th><th>操作</th></tr></thead><tbody>{data.imports.map((r:R)=><tr key={r.id}><td>{r.business_date}</td><td>{r.site} · {r.channel}</td><td>{r.source_batch_ref}<small>{r.file_name}</small></td><td>{r.row_count} / {Number(r.total_qty).toLocaleString()}</td><td><span className={`pill ${r.reversed_at?'red':'green'}`}>{r.reversed_at?'已冲销':'有效'}</span>{r.reversed_at&&<small>{r.reversal_reason}</small>}</td><td>{!r.reversed_at&&<div className="maintenance-actions">{canEdit&&!String(r.import_key).startsWith('coverage|')&&<button className="btn" disabled={busy||loading} onClick={()=>open(r,'edit')}>修改</button>}{canDelete&&<button className="btn danger" disabled={busy||loading} onClick={()=>open(r,'delete')}>删除</button>}</div>}</td></tr>)}{!data.imports.length&&<tr><td colSpan={6}>暂无导入记录</td></tr>}</tbody></table></div>
 {selected&&<div ref={editor} className="maintenance-editor" role="region" aria-label="批次维护"><h3>{mode==='edit'?'修改销售批次':'删除销售批次'} · {selected.business_date}</h3><p>{selected.site} · {selected.channel} · {selected.source_batch_ref}</p>
 {mode==='delete'?<div className="notice warn">将冲销此批次 {selected.total_qty} 件销售，恢复相应库存。原始记录、金额和操作原因保留，批次不再计入有效销售。</div>:<>
 <div className="form-grid"><label className="field">销售日期<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">平台报表编号<input value={ref} onChange={e=>setRef(e.target.value)}/></label></div>
 {loading?<p role="status">正在读取完整批次…</p>:<><TableImport kind="sales" busy={busy} confirmLabel="替换编辑清单（尚未保存）" description="可以上传修正后的完整文件替换清单，或在下方直接修改。确认保存后才影响库存和销售。" onApply={async next=>{setRows(normalizeSales(next,SITE_CURRENCIES[selected.site as keyof typeof SITE_CURRENCIES]).map((r:R)=>({...r,amount:r.amount??'',adCost:r.adCost??''})));setPage(0);return true;}}/>
 <div className="table-wrap"><table><thead><tr><th>SKU</th><th>数量</th><th>销售额</th><th>SKU 广告成本</th><th>币种</th><th>操作</th></tr></thead><tbody>{rows.slice(page*20,page*20+20).map((r,j)=>{const i=page*20+j;return <tr key={i}><td><input aria-label={`第${i+1}行SKU`} value={r.sku} onChange={e=>update(i,'sku',e.target.value)}/></td>{['qty','amount','adCost'].map((k,n)=><td key={k}><input aria-label={`第${i+1}行${['数量','销售额','广告成本'][n]}`} type="number" min="0" step={k==='qty'?'1':'.01'} value={r[k]} onChange={e=>update(i,k,e.target.value)}/></td>)}<td><select aria-label={`第${i+1}行币种`} value={r.currency} onChange={e=>update(i,'currency',e.target.value)}><option value="">请选择</option>{SALES_CURRENCIES.map(c=><option key={c}>{c}</option>)}</select></td><td><button className="btn danger" disabled={busy} onClick={()=>{setRows(rows.filter((_,j)=>i!==j));setPage(0);}}>移除行</button></td></tr>})}</tbody></table></div>
 <div className="maintenance-actions"><span>共 {rows.length} 行 · 第 {page+1} 页</span><button className="btn" disabled={!page} onClick={()=>setPage(page-1)}>上一页</button><button className="btn" disabled={(page+1)*20>=rows.length} onClick={()=>setPage(page+1)}>下一页</button></div></>}
 </>}
 <label className="field">{mode==='edit'?'修改':'删除'}原因（至少5个字）<textarea value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} placeholder="请填写核对依据和本次调整原因"/></label>
 {error&&<p className="notice error" role="alert">{error}</p>}<div className="maintenance-actions"><button className="btn" disabled={busy} onClick={()=>setSelected(null)}>取消</button><button className={`btn ${mode==='edit'?'primary':'danger'}`} disabled={busy||loading||reason.trim().length<5||(mode==='edit'&&!rows.length)} onClick={save}>{mode==='edit'?'保存修改并校正库存':'确认删除并冲销'}</button></div></div>}
 </section>;
}
