"use client";
import {useState,type ReactNode} from 'react';
import {useWholesaleLanguage} from './wholesale-language';
type Row=Record<string,any>;
type Props={data:Row;busy:boolean;mutate:(action:string,payload:Row)=>Promise<boolean>};
const today=()=>new Date(Date.now()+7*3600000).toISOString().slice(0,10);
function Field({label,children}:{label:string;children:ReactNode}){const {t}=useWholesaleLanguage();return <label className="field"><span>{t(label)}</span>{children}</label>;}
export function CustomerMaintenance({data,busy,mutate}:Props){
 const {t}=useWholesaleLanguage(),[selected,setSelected]=useState(''),[draft,setDraft]=useState<Row>({}),[reason,setReason]=useState(''),[owner,setOwner]=useState('');
 const customer=data.customers.find((c:Row)=>c.id===selected);
 return <section className="panel"><h4>{t("客户资料与交接")}</h4><p>{t("修改影响新订单，历史订单保留原资料；交接不改变历史销售贡献。")}</p><Field label="选择客户"><select value={selected} onChange={e=>{const c=data.customers.find((r:Row)=>r.id===e.target.value);setSelected(e.target.value);setDraft(c?{...c,active:!!c.active}:{});setOwner(c?.sales_user_id||'');setReason('');}}><option value="">{t("选择客户")}</option>{data.customers.map((c:Row)=><option value={c.id} key={c.id}>{c.code} · {c.name}</option>)}</select></Field>{customer&&<form className="wh-form" onSubmit={async e=>{e.preventDefault();if(await mutate('customerUpdate',{...draft,customerId:customer.id,version:customer.version,reason}))setReason('');}}><div className="wh-grid">{[['name','客户名称'],['contact','联系人'],['phone','电话'],['city','城市'],['address','收货地址'],['note','备注']].map(([key,label])=><Field key={key} label={label}><input required={key!=='note'} value={draft[key]||''} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></Field>)}<Field label="客户状态"><select value={draft.active?'active':'inactive'} onChange={e=>setDraft({...draft,active:e.target.value==='active'})}><option value="active">{t("启用")}</option><option value="inactive">{t("停用")}</option></select></Field><Field label="修改或交接原因"><input required minLength={4} value={reason} onChange={e=>setReason(e.target.value)}/></Field></div><button className="btn primary" disabled={busy}>{t("保存客户资料")}</button>{data.actor.role==='管理员'&&<div className="wh-grid"><Field label="接手销售"><select value={owner} onChange={e=>setOwner(e.target.value)}>{data.users.filter((u:Row)=>['销售','运营','管理员'].includes(u.role)).map((u:Row)=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><button className="btn" type="button" disabled={busy||owner===customer.sales_user_id||reason.length<4} onClick={()=>mutate('customerTransfer',{customerId:customer.id,version:customer.version,salesUserId:owner,reason})}>{t("确认客户交接")}</button></div>}</form>}</section>;
}
export function FinanceCorrection({order,busy,mutate}:{order:Row;busy:boolean;mutate:Props['mutate']}){
 const {t,money}=useWholesaleLanguage(),[entryId,setEntryId]=useState(''),[day,setDay]=useState(today()),[reference,setReference]=useState(''),[note,setNote]=useState('');
 const entries=order.entries.filter((e:Row)=>['receipt','refund'].includes(e.kind)&&!order.entries.some((r:Row)=>r.reverses_id===e.id));
 return <details className="wh-action-box"><summary>{t("纠正回款或退款记录")}</summary><p>{t("冲正保留原记录；银行收款核销撤销后，金额返回未分配余额。")}</p><form onSubmit={async e=>{e.preventDefault();if(await mutate('financeReverse',{entryId,version:order.version,businessDate:day,reference,note})){setEntryId('');setReference('');setNote('');}}}><div className="wh-grid"><Field label="原始记录"><select required value={entryId} onChange={e=>setEntryId(e.target.value)}><option value="">{t("请选择")}</option>{entries.map((e:Row)=><option key={e.id} value={e.id}>{e.business_date} · {e.reference} · {money(e.amount)}</option>)}</select></Field><Field label="冲正日期"><input required type="date" max={today()} value={day} onChange={e=>setDay(e.target.value)}/></Field><Field label="冲正凭证编号"><input required value={reference} onChange={e=>setReference(e.target.value)}/></Field><Field label="冲正原因"><input required minLength={4} value={note} onChange={e=>setNote(e.target.value)}/></Field></div><button disabled={busy} className="btn danger">{t("确认冲正或撤销核销")}</button></form></details>;
}
export function BankReceiptManager({data,busy,mutate}:Props){
 const {t,money}=useWholesaleLanguage(),[form,setForm]=useState({customerId:'',amount:'',reference:'',bankAccount:'',businessDate:today(),note:''}),[selected,setSelected]=useState(''),[allocations,setAllocations]=useState<Record<string,string>>({}),[day,setDay]=useState(today()),[note,setNote]=useState(''),[event,setEvent]=useState({kind:'bankReceiptRefund',amount:'',reference:''});
 const bank=(data.bankReceipts||[]).find((b:Row)=>b.id===selected),eligible=bank?data.orders.filter((o:Row)=>o.customer_id===bank.customer_id&&o.outstanding>0&&!['pending','rejected','cancelled'].includes(o.status)):[];
 const remaining=bank?bank.amount-bank.allocated_amount-bank.refunded_amount-bank.voided_amount:0;
 return <section className="panel"><h4>{t("银行收款与多订单核销")}</h4><p>{t("银行流水登记一次，可分配至同一客户的多张订单；未分配余额保留为客户预收。")}</p><details><summary>{t("登记对公收款")}</summary><form className="wh-form" onSubmit={async e=>{e.preventDefault();if(await mutate('bankReceiptCreate',form))setForm({...form,amount:'',reference:'',note:''});}}><div className="wh-grid"><Field label="客户"><select required value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})}><option value="">{t("选择客户")}</option>{data.customers.filter((c:Row)=>c.active).map((c:Row)=><option key={c.id} value={c.id}>{c.name} · {c.code}</option>)}</select></Field>{[['amount','实际到账金额 IDR'],['reference','银行流水号'],['bankAccount','公司收款账户'],['businessDate','实际到账日期'],['note','核对说明']].map(([key,label])=><Field key={key} label={label}><input required type={key==='amount'?'number':key==='businessDate'?'date':'text'} min={key==='amount'?1:undefined} max={key==='businessDate'?today():undefined} value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})}/></Field>)}</div><button disabled={busy} className="btn primary">{t("确认实际到账")}</button></form></details>
 <div className="table-wrap"><table><thead><tr>{['客户','银行流水号','实际到账日期','收款金额','已核销金额','未分配余额','操作'].map(k=><th key={k}>{t(k)}</th>)}</tr></thead><tbody>{(data.bankReceipts||[]).map((b:Row)=><tr key={b.id}><td>{b.customer_name}</td><td>{b.reference}</td><td>{b.business_date}</td><td>{money(b.amount)}</td><td>{money(b.allocated_amount)}</td><td>{money(b.amount-b.allocated_amount-b.refunded_amount-b.voided_amount)}</td><td><button className="btn" onClick={()=>{setSelected(b.id);setAllocations({});setNote('');}}>{t("分配或处理")}</button></td></tr>)}</tbody></table></div>
 {bank&&<div className="wh-action-box"><h5>{bank.reference} · {t("未分配余额")} {money(remaining)}</h5><div className="wh-grid"><Field label="核销或处理日期"><input type="date" required min={bank.business_date} max={today()} value={day} onChange={e=>setDay(e.target.value)}/></Field><Field label="处理说明"><input value={note} onChange={e=>setNote(e.target.value)}/></Field></div><form onSubmit={async e=>{e.preventDefault();const items=eligible.filter((o:Row)=>Number(allocations[o.id])>0).map((o:Row)=>({orderId:o.id,version:o.version,amount:Number(allocations[o.id])}));if(await mutate('bankReceiptAllocate',{receiptId:bank.id,version:bank.version,businessDate:day,note,allocations:items}))setAllocations({});}}><div className="table-wrap"><table><thead><tr><th>{t("订单号")}</th><th>{t("合同待收款")}</th><th>{t("本次核销金额")}</th></tr></thead><tbody>{eligible.map((o:Row)=><tr key={o.id}><td>{o.order_no}</td><td>{money(o.outstanding)}</td><td><input aria-label={t("本次核销金额")} type="number" min="0" max={o.outstanding} value={allocations[o.id]||''} onChange={e=>setAllocations({...allocations,[o.id]:e.target.value})}/></td></tr>)}</tbody></table></div><button className="btn primary" disabled={busy||!eligible.length}>{t("确认分配核销")}</button></form><details><summary>{t("未分配余额退款或冲正")}</summary><form onSubmit={e=>{e.preventDefault();void mutate(event.kind,{receiptId:bank.id,version:bank.version,businessDate:day,note,amount:event.amount,reference:event.reference});}}><div className="wh-grid"><Field label="处理类型"><select value={event.kind} onChange={e=>setEvent({...event,kind:e.target.value})}><option value="bankReceiptRefund">{t("实际退回未分配款")}</option><option value="bankReceiptVoid">{t("冲正错误收款")}</option></select></Field><Field label="金额 IDR"><input required type="number" min="1" max={remaining} value={event.amount} onChange={e=>setEvent({...event,amount:e.target.value})}/></Field><Field label="凭证编号"><input required value={event.reference} onChange={e=>setEvent({...event,reference:e.target.value})}/></Field></div><button className="btn danger" disabled={busy||note.length<4}>{t("确认处理")}</button></form></details></div>}</section>;
}
export function PeriodManager({data,busy,mutate,month}:Props&{month:string}){
 const {t}=useWholesaleLanguage(),[reason,setReason]=useState(''),period=(data.periods||[]).find((p:Row)=>p.month===month),closed=period?.status==='closed';
 return <section className="panel"><h4>{t("财务关账与历史快照")}</h4><p>{month} · {t(closed?'已关账':'未关账')}</p><p>{t("关账冻结该月及以前的业务日期，历史导出使用关账快照；反关账由管理员从最近月份开始。")}</p><Field label="关账或反关账原因"><input value={reason} onChange={e=>setReason(e.target.value)} minLength={4}/></Field><button className="btn" disabled={busy||reason.length<4||month>=today().slice(0,7)||(closed&&data.actor.role!=='管理员')} onClick={()=>mutate(closed?'financePeriodReopen':'financePeriodClose',{month,reason})}>{t(closed?'反关账':'确认关账')}</button></section>;
}
