"use client";
import { CustomerMaintenance, FinanceCorrection, BankReceiptManager, PeriodManager } from "./wholesale-management-ui";
import { useCallback, useEffect, useRef, useState } from "react";
import { useWholesaleLanguage,WholesaleLanguageSwitch } from "./wholesale-language";
import { wholesaleDownloadName,wholesaleValidationMessage } from "../lib/wholesale-i18n.mjs";
import { hasPermission } from "../lib/permissions.mjs";

// The API returns joined, permission-scoped records from the wholesale ledger.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row=Record<string,any>;
type Mutate=(action:string,payload:Row)=>Promise<boolean>;
const labels:Record<string,string>={pending:"待审批",approved:"待打包",packing:"打包中",partial:"部分发货",completed:"已完成发货",closed:"部分发货已结单",rejected:"已驳回",cancelled:"已取消"};
const financeLabels:Record<string,string>={receipt:"确认回款",refund:"确认退款",invoice:"登记开票",invoice_void:"登记开票冲销"};
const today=()=>new Date(Date.now()+7*3600000).toISOString().slice(0,10);
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){
  const {t}=useWholesaleLanguage();return <label className={wide?"wh-field wh-wide":"wh-field"}><span>{t(label)}</span>{children}</label>;}
function Badge({value}:{value:string}){
  const {t}=useWholesaleLanguage();return <span className={`wh-badge ${value==="completed"||value==="已回款"?"done":value==="pending"||value==="未回款"||value==="待退款"?"wait":""}`}>{t(labels[value]||value)}</span>;}
function Panel({title,children,action}:{title:string;children:React.ReactNode;action?:React.ReactNode}){
  const {t}=useWholesaleLanguage();return <section className="panel wh-panel"><div className="panel-head"><h4>{t(title)}</h4>{action}</div>{children}</section>;}
function Empty({children}:{children:React.ReactNode}){
  return <p className="wh-empty">{children}</p>;}
async function responseJson(response:Response){const result=await response.json();if(!response.ok)throw new Error(result.errorKey||result.error||"操作失败");return result;}

export default function Wholesale({onChanged}:{onChanged:()=>Promise<void>}){
  const {t,language,fmt,money,stamp}=useWholesaleLanguage();
  const surface=useRef<HTMLDivElement>(null);
  useEffect(()=>{surface.current?.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>("input,select,textarea").forEach(field=>field.setCustomValidity(""));},[language]);
  const validate=(event:React.FormEvent<HTMLDivElement>)=>{const field=event.target as HTMLInputElement;if(typeof field.setCustomValidity==="function")field.setCustomValidity(wholesaleValidationMessage(language,field.validity,{min:field.min,max:field.max,minLength:field.minLength}));};
  const clearValidation=(event:React.FormEvent<HTMLDivElement>)=>{const field=event.target as HTMLInputElement;if(typeof field.setCustomValidity==="function")field.setCustomValidity("");};
  const [month,setMonth]=useState(today().slice(0,7)),[data,setData]=useState<Row|null>(null),[view,setView]=useState("orders"),[selected,setSelected]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[create,setCreate]=useState(false),[customerForm,setCustomerForm]=useState(false);
  const [exporting,setExporting]=useState(false);
  const download=async(mode:"all"|"month")=>{
    setExporting(true);
    try{const response=await fetch(`/api/wholesale/export?mode=${mode}&month=${month}&lang=${language}`,{cache:"no-store"});if(!response.ok){const result=await response.json();throw new Error(result.errorKey||result.error||"导出失败");}const blob=await response.blob();const url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=wholesaleDownloadName(language,mode,mode==="all"?today():month);document.body.appendChild(anchor);anchor.click();anchor.remove();window.setTimeout(()=>URL.revokeObjectURL(url),60000);setNotice(mode==="all"?"全部权限内订单已导出，含客户、出库、结算及财务流水。":`${month}月度对账已导出，含期初与期末余额。`);}
    catch(e){setNotice(e instanceof Error?e.message:"导出失败，请稍后重试");}finally{setExporting(false);}
  };
  const retry=useRef<{key:string;id:string}|null>(null),sequence=useRef(0);
  const load=useCallback(async()=>{const generation=++sequence.current;const result=await responseJson(await fetch(`/api/wholesale?month=${month}`,{cache:"no-store"}));if(generation===sequence.current)setData(result);},[month]);
  useEffect(()=>{load().catch(e=>setNotice(e.message)).finally(()=>setLoading(false));},[load]);
  const mutate:Mutate=async(action,payload)=>{
    setBusy(true);setNotice("");const key=JSON.stringify({action,...payload});if(retry.current?.key!==key)retry.current={key,id:crypto.randomUUID()};
    try{const result=await responseJson(await fetch("/api/wholesale",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...payload,operationId:retry.current.id})}));retry.current=null;
      setNotice(result.replayed?"该操作此前已保存，未重复处理。":"已保存。库存、订单和结算状态已更新。");
      try{await load();await onChanged();}catch{setNotice("操作已保存，列表刷新暂时失败，请点击刷新核对。");}return true;
    }catch(e){setNotice(e instanceof Error?e.message:"保存失败，请保留填写内容后重试");return false;}finally{setBusy(false);}
  };
  if(!data)return <div className="wholesale" lang={language==="id"?"id":"zh-CN"}><WholesaleLanguageSwitch/><h3>{t("印尼线下批发")}</h3><p role="status">{loading?t("正在读取批发订单…"):t(notice)}</p><button className="btn" onClick={()=>load().catch(e=>setNotice(e.message))}>{t("重新读取")}</button></div>;
  const actor=data.actor,can=(p:string)=>hasPermission(actor.role,p),d=data.dashboard;
  const order=data.orders.find((o:Row)=>o.id===selected);
  const filtered=data.orders.filter((o:Row)=>(view!=="completed"||["completed","closed"].includes(o.status))&&(status==="all"||o.status===status)&&[o.order_no,o.customer.name,o.customer.phone,o.sales_name,...o.items.map((i:Row)=>i.sku)].join(" ").toLowerCase().includes(search.toLowerCase()));
  const cards=[["本月出库销售额",money(d.salesAmount)],["本月出库件数",fmt(d.quantity)],["本月客户 / SKU",`${d.customerCount} / ${d.skuCount}`],["本月回款",money(d.cashReceived)],["当前合同待收款",money(d.currentOutstanding)],["当前合同待退款",money(d.currentRefundDue)]];
  const exportOrders=()=>{const columns=["序号","订单号","订单日期","完成发货时间（印尼西部）","客户编号","客户","联系人","电话","城市","收货地址","销售负责人","SKU种类数","订单件数","已发件数","订单金额IDR","出库销售额IDR","退货金额IDR","净销售额IDR","按已出库待收款IDR","按已出库结算状态","合同待收款IDR","净回款IDR","回款状态","是否需开票","有效开票金额IDR","开票状态","履约状态"];
    const content=[columns.map(c=>t(c)),...filtered.map((o:Row,i:number)=>[i+1,o.order_no,o.business_date,stamp(o.completed_at),o.customer.code,o.customer.name,o.customer.contact,o.customer.phone,o.customer.city,o.customer.address,o.sales_name,o.items.length,o.total_qty,o.items.reduce((s:number,r:Row)=>s+r.shipped_qty,0),o.total_amount,o.financial.salesAmount,o.financial.returnAmount,o.financial.netSales,o.financial.receivable,t(o.financial.settlementStatus),o.outstanding,o.paid,t(o.paymentStatus),t(o.invoice_required?"是":"否"),o.invoiced,t(o.invoiceStatus),t(labels[o.status])])].map(row=>row.map((v:unknown)=>{const value=String(v??"");return `"${(/^[=+@\-\t\r]/.test(value)?"'":"")+value.replaceAll('"','""')}"`;}).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob(["\ufeff",content],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download=language==="id"?`Pesanan-Grosir-Terfilter-${today()}.csv`:`印尼线下批发订单-${today()}.csv`;a.click();URL.revokeObjectURL(url);};
  return <div className="wholesale" ref={surface} lang={language==="id"?"id":"zh-CN"} onInvalid={validate} onInput={clearValidation}>
    <div className="wh-language-row"><WholesaleLanguageSwitch/></div><div className="wh-head"><div><p className="wh-eyebrow">INDONESIA · WHOLESALE</p><h3>{t("印尼线下批发")}</h3><p>{t("申请出库 → 独立审批 → 供应链发货 → 回款与开票跟进")}</p></div><div className="wh-actions"><label>{t("统计月份")}<input aria-label={t("统计月份")} type="month" max={today().slice(0,7)} value={month} onChange={e=>{if(e.target.value){setLoading(true);setMonth(e.target.value);}}}/></label><button className="btn" disabled={busy||loading} onClick={()=>load().catch(e=>setNotice(e.message))}>{t("刷新")}</button><button className="btn primary" disabled={exporting||busy||loading} onClick={()=>download("all")}>{exporting?t("正在生成Excel…"):["管理员","财务"].includes(actor.role)?t("一键导出全部订单"):t("导出负责订单")}</button>{can("wholesale.create")&&<button className="btn primary" onClick={()=>{setCreate(!create);setSelected("");}}>{t("＋ 出库申请")}</button>}</div></div>
    {notice&&<div className="wh-notice" role="status">{t(notice)}<button aria-label={t("关闭提示")} onClick={()=>setNotice("")}>×</button></div>}
    <p className="wh-copy wh-sales-rule">{t("已实际出库即计入销售额，按成交单价 × 出库件数计算，币种为 IDR 印尼盾。未回款、未开票及部分出库均计入；退货另列并冲减净销售额。")}</p>
    <div className="wh-metrics">{cards.map(([label,value])=><article key={label}><span>{t(label)}</span><strong>{value}</strong></article>)}</div>
    <div className="wh-tabs" role="tablist" aria-label={t("线下批发视图")}>{[["orders","全部订单"],["completed","完成订单"],["customers","客户档案"],["dashboard","月度销售看板"],["finance","财务月度对账"],["checks",`${t("业务检查")}${data.checks.issues.length?` · ${data.checks.issues.length}`:""}`]].map(([id,label])=><button role="tab" aria-selected={view===id} key={id} className={view===id?"active":""} onClick={()=>{setView(id);setSelected("");setCreate(false);}}>{t(label)}</button>)}</div>
    {create&&<CreateOrder data={data} busy={busy} mutate={mutate} done={()=>setCreate(false)} newCustomer={()=>{setCustomerForm(true);setView("customers");setCreate(false);}}/>}
    {order&&<OrderDetail key={`${order.id}-${order.version}`} order={order} data={data} busy={busy} mutate={mutate} close={()=>setSelected("")} refresh={load} notice={setNotice}/>}
    {(view==="orders"||view==="completed")&&<Panel title={view==="completed"?t("已完成发货的订单"):t("订单台账")} action={<button className="btn" onClick={exportOrders}>{t("导出筛选列表CSV")}</button>}>
      <div className="wh-filter"><input aria-label={t("搜索订单")} value={search} onChange={e=>setSearch(e.target.value)} placeholder={t("订单号、客户、电话、销售或 SKU")}/>{view!=="completed"&&<select aria-label={t("履约状态")} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{t("全部履约状态")}</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{t(v)}</option>)}</select>}<span>{filtered.length} {t("笔 · 发货完成后继续跟进回款与开票")}</span></div>
      <div className="table-wrap"><table><thead><tr><th>{t("序号 / 日期")}</th><th>{t("订单与客户")}</th><th>{t("销售 / SKU")}</th><th>{t("发货件数")}</th><th>{t("出库销售额 / 订单金额")}</th><th>{t("订单回款")}</th><th>{t("开票")}</th><th>{t("履约")}</th><th>{t("操作")}</th></tr></thead><tbody>{filtered.map((o:Row,i:number)=><tr key={o.id}><td>{i+1}<small>{o.business_date}</small></td><td><strong>{o.order_no}</strong><small>{o.customer.name} · {o.customer.contact}</small><small>{o.customer.phone} · {o.customer.city}</small></td><td>{o.sales_name}<small>{o.items.length} {t("种 SKU")}</small></td><td>{fmt(o.items.reduce((s:number,r:Row)=>s+r.shipped_qty,0))} / {fmt(o.total_qty)}<small>{t("已发 / 申请")}</small></td><td><strong>{money(o.financial.salesAmount)}</strong><small>{t("订单")}{money(o.total_amount)}</small></td><td><Badge value={o.paymentStatus}/><small>{t("已收")}{money(o.paid)}</small><small>{t("合同待收")}{money(o.outstanding)}</small></td><td><Badge value={o.invoiceStatus}/></td><td><Badge value={o.status}/><small>{o.supply_name||t("待分配供应链")}</small></td><td><button className="btn" onClick={()=>{setSelected(o.id);setCreate(false);window.scrollTo({top:0,behavior:"smooth"});}}>{t("查看 / 处理")}</button></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty>{t("暂无符合条件的订单。销售建立客户档案后即可提出出库申请。")}</Empty>}
    </Panel>}
    {view==="customers"&&<><Panel title={t("印尼批发客户")} action={can("wholesale.customer")?<button className="btn primary" onClick={()=>setCustomerForm(!customerForm)}>{t("＋ 新增客户")}</button>:undefined}>{customerForm&&<CustomerForm data={data} busy={busy} mutate={mutate} done={()=>setCustomerForm(false)}/>}<div className="table-wrap"><table><thead><tr><th>{t("客户编号 / 名称")}</th><th>{t("联系人 / 电话")}</th><th>{t("城市 / 收货地址")}</th><th>{t("销售负责人")}</th><th>{t("订单 / 合同待收款")}</th></tr></thead><tbody>{data.customers.map((c:Row)=>{const orders=data.orders.filter((o:Row)=>o.customer_id===c.id);return <tr key={c.id}><td>{c.code}<small>{c.name}</small></td><td>{c.contact}<small>{c.phone}</small></td><td>{c.city}<small>{c.address}</small></td><td>{data.users.find((u:Row)=>u.id===c.sales_user_id)?.name||"—"}</td><td>{orders.length} {t("笔")}<small>{money(orders.reduce((s:number,o:Row)=>s+o.outstanding,0))}</small></td></tr>;})}</tbody></table></div>{!data.customers.length&&<Empty>{t("暂无客户，请先填写真实客户资料。")}</Empty>}</Panel></>}
    {view==="customers"&&can("wholesale.customer")&&<CustomerMaintenance data={data} busy={busy} mutate={mutate}/>}
    {view==="dashboard"&&<Dashboard dashboard={d}/>}
    {view==="finance"&&<><FinanceReconciliation report={data.finance} exporting={exporting||loading} download={()=>download("month")}/>{can("wholesale.finance")&&<><BankReceiptManager data={data} busy={busy} mutate={mutate}/><PeriodManager data={data} busy={busy} mutate={mutate} month={month}/></>}</>}
    {view==="checks"&&<><Panel title={t("自动业务检查")} action={<button className="btn" disabled={loading||busy} onClick={()=>load().catch(e=>setNotice(e.message))}>{t("重新检查")}</button>}><p className="wh-copy">{t(data.checks.scope)} · {stamp(data.checks.checkedAt)}{t("。系统核对订单合计、库存分配、发货明细、完成状态及逾期结算；管理员同时核对预留余额和实际扣库流水。")}</p>{data.checks.issues.length?<div className="table-wrap"><table><thead><tr><th>{t("订单 / SKU")}</th><th>{t("待处理事项")}</th></tr></thead><tbody>{data.checks.issues.map((i:Row,n:number)=><tr key={n}><td>{i.order}</td><td>{t(i.type)}</td></tr>)}</tbody></table></div>:<Empty>{t("当前检查未发现异常。")}</Empty>}</Panel><Panel title={t("库存与结算规则")}><ul className="wh-rules"><li>{t("首期仅使用印尼 TikTok、Shopee 的独立账面库存份额。偶数均分；单数多出1件由可用库存较多的平台承担，持平时分给 TikTok。")}</li><li>{t("单个平台不足时从另一平台补齐；合计不足则不批准。审批先锁定，实际发货才扣账面库存。待上架、隔离和在途货不能用于本次出库。")}</li><li>{t("分批发货沿用审批时保存的分配，总扣减等于实际发货总数；单号、照片或视频用于证明实际出库。")}</li><li>{t("原有销售导入可能反映实际超卖，系统保留差异并提示预留不足。先核对差异，再安排线下发货。")}</li><li>{t("线下销售按实际发货独立统计，不写成 TikTok 或 Shopee 平台订单，不再次导入扣库存。")}</li><li>{t("当前分配规则版本为 average_v1。后续虚拟库位通过调拨转入，历史订单按原扣库来源追溯。")}</li></ul></Panel></>}
    <p className="wh-footnote">{t("金额单位 IDR；单价按最终商品成交价填写。月度归属按印尼西部时间及业务日期统计；销售额、银行收款和开票金额分别记录。")}</p>
  </div>;
}

function CustomerForm({data,busy,mutate,done}:{data:Row;busy:boolean;mutate:Mutate;done:()=>void}){
  const {t}=useWholesaleLanguage();
  const [form,setForm]=useState({name:"",contact:"",phone:"",city:"",address:"",note:"",salesUserId:data.actor.id});
  return <form className="wh-form" onSubmit={async e=>{e.preventDefault();if(await mutate("customerCreate",form))done();}}><div className="wh-grid">{[["name","客户 / 公司名称"],["contact","联系人"],["phone","电话或 WhatsApp"],["city","城市"],["address","完整收货地址"]].map(([key,label])=><Field key={key} label={label} wide={key==="address"}><input required value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})}/></Field>)}{data.actor.role==="管理员"&&<Field label={t("销售负责人")}><select value={form.salesUserId} onChange={e=>setForm({...form,salesUserId:e.target.value})}>{data.users.filter((u:Row)=>["管理员","销售","运营"].includes(u.role)).map((u:Row)=><option key={u.id} value={u.id}>{u.name} · {t(u.role)}</option>)}</select></Field>}<Field label={t("客户备注")}><input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></Field></div><div className="wh-actions"><button className="btn primary" disabled={busy}>{t("保存客户")}</button><button className="btn" type="button" onClick={done}>{t("关闭")}</button></div></form>;
}

function CreateOrder({data,busy,mutate,done,newCustomer}:{data:Row;busy:boolean;mutate:Mutate;done:()=>void;newCustomer:()=>void}){
  const {t,fmt,money}=useWholesaleLanguage();
  const [form,setForm]=useState({customerId:"",businessDate:today(),paymentTerms:"prepaid",dueDate:"",invoiceRequired:false,note:""}),[items,setItems]=useState([{sku:"",qty:"5",unitPrice:""}]);
  const update=(index:number,key:string,value:string)=>setItems(items.map((r,i)=>i===index?{...r,[key]:value}:r));
  const total=items.reduce((s,r)=>s+Number(r.qty)*Number(r.unitPrice),0);
  return <Panel title={t("销售出库申请")} action={<button className="btn" onClick={done}>{t("关闭")}</button>}><form className="wh-form" onSubmit={async e=>{e.preventDefault();if(await mutate("orderCreate",{...form,site:"印尼",items}))done();}}><div className="wh-grid"><Field label={t("客户")}><select required value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})}><option value="">{t("选择客户")}</option>{data.customers.filter((c:Row)=>data.actor.role==="管理员"||c.sales_user_id===data.actor.id).map((c:Row)=><option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</select></Field><Field label={t("客户档案")}><button className="btn" type="button" onClick={newCustomer}>{t("新增客户")}</button></Field><Field label={t("订单日期")}><input required type="date" max={today()} value={form.businessDate} onChange={e=>setForm({...form,businessDate:e.target.value})}/></Field><Field label={t("付款条件")}><select value={form.paymentTerms} onChange={e=>setForm({...form,paymentTerms:e.target.value})}><option value="prepaid">{t("先款后货")}</option><option value="credit">{t("赊销账期（须管理员批准）")}</option></select></Field>{form.paymentTerms==="credit"&&<Field label={t("回款到期日")}><input required type="date" min={form.businessDate} value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></Field>}<Field label={t("客户是否需要开票")}><select value={String(form.invoiceRequired)} onChange={e=>setForm({...form,invoiceRequired:e.target.value==="true"})}><option value="false">{t("不需要")}</option><option value="true">{t("需要")}</option></select></Field></div>
    <div className="table-wrap"><table><thead><tr><th>{t("SKU / 商品")}</th><th>{t("件数")}</th><th>{t("成交单价 IDR")}</th><th>{t("金额")}</th><th>{t("两平台当前可用")}</th><th/></tr></thead><tbody>{items.map((r,i)=><tr key={i}><td><select aria-label={t("第{0}行SKU",[i+1])} required value={r.sku} onChange={e=>update(i,"sku",e.target.value)}><option value="">{t("选择 SKU")}</option>{data.skus.map((s:Row)=><option key={s.sku} value={s.sku}>{s.sku} · {s.name}</option>)}</select></td><td><input aria-label={t("第{0}行数量",[i+1])} type="number" min="1" step="1" required value={r.qty} onChange={e=>update(i,"qty",e.target.value)}/></td><td><input aria-label={t("第{0}行单价",[i+1])} type="number" min="1" step="1" required value={r.unitPrice} onChange={e=>update(i,"unitPrice",e.target.value)}/></td><td>{money(Number(r.qty)*Number(r.unitPrice))}</td><td>{r.sku?["TikTok","Shopee"].map(ch=>{const s=data.stock.find((s:Row)=>s.sku===r.sku&&s.channel===ch);return <small key={ch}>{ch}：{fmt(Math.max(0,Number(s?.qty||0)-Number(s?.reserved_qty||0)))}</small>;}):"—"}</td><td>{items.length>1&&<button className="btn" type="button" onClick={()=>setItems(items.filter((_,n)=>n!==i))}>{t("移除")}</button>}</td></tr>)}</tbody></table></div><div className="wh-actions"><button type="button" className="btn" disabled={items.length>=20} onClick={()=>setItems([...items,{sku:"",qty:"1",unitPrice:""}])}>＋ SKU</button><strong>{t("订单商品金额")}{money(total)}</strong></div><Field label={t("销售备注及开票抬头资料")} wide><textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder={t("收货要求、约定账期；需开票时填写抬头等资料")}/></Field><p className="wh-copy">{t("提交后进入管理员审批；审批前不占库存。审批通过后锁定版本，修改商品或价格须取消原单再提交。")}</p><button className="btn primary" disabled={busy}>{t("提交出库申请")}</button></form></Panel>;
}

function OrderDetail({order:o,data,busy,mutate,close,refresh,notice}:{order:Row;data:Row;busy:boolean;mutate:Mutate;close:()=>void;refresh:()=>Promise<void>;notice:(s:string)=>void}){
  const {t,language,money}=useWholesaleLanguage();
  const actor=data.actor,can=(p:string)=>hasPermission(actor.role,p),base={orderId:o.id,version:o.version};
  const [supply,setSupply]=useState(o.supply_user_id||data.users.find((u:Row)=>u.role==="供应链")?.id||""),[reason,setReason]=useState(""),[stockConfirmed,setStockConfirmed]=useState(false),[showFinance,setShowFinance]=useState(false),[showReturn,setShowReturn]=useState(false);
  const ownApproval=o.creator_id===actor.id||o.sales_user_id===actor.id;
  const active=["approved","packing","partial"].includes(o.status);
  return <Panel title={`${o.order_no} · ${t(labels[o.status])}`} action={<button className="btn" onClick={close}>{t("收起")}</button>}>
    <div className="wh-detail"><div><strong>{o.customer.name}</strong><p>{o.customer.contact} · {o.customer.phone}</p><p>{o.customer.city} · {o.customer.address}</p><p>{t("销售：")}{o.sales_name} {t("供应链：")}{o.supply_name||t("待分配")}</p></div><div><strong>{money(o.total_amount)}</strong><p>{o.payment_terms==="prepaid"?t("先款后货"):t("赊销，到期日 {0}",[o.due_date])}</p><p>{t("净回款")}{money(o.paid)} {t("合同待收")}{money(o.outstanding)} {t("待退款")}{money(o.refundDue)}</p><p>{t("出库销售额")}{money(o.financial.salesAmount)} {t("· 已出库待收")}{money(o.financial.receivable)}</p><p>{t("开票：")}{t(o.invoiceStatus)} {t("有效金额")}{money(o.invoiced)}</p></div></div>
    {o.cancelled_amount>0&&<p className="wh-copy">{t("已取消未发商品金额")}{money(o.cancelled_amount)}{t("；剩余有效应收")}{money(o.payable)}。</p>}
    {o.note&&<p className="wh-copy">{t("销售备注：")}{o.note}</p>}{o.decision_note&&<p className="wh-copy">{t("审批 / 调整说明：")}{o.decision_note}</p>}
    <div className="table-wrap"><table><thead><tr><th>{t("SKU / 商品")}</th><th>{t("单价")}</th><th>{t("申请 / 已发 / 已退")}</th><th>{t("审批锁定来源")}</th></tr></thead><tbody>{o.items.map((i:Row)=><tr key={i.id}><td>{i.sku}<small>{i.name}</small></td><td>{money(i.unit_price)}</td><td>{i.qty} / {i.shipped_qty} / {i.returned_qty}</td><td>{i.allocations.length?i.allocations.map((a:Row)=><small key={a.id}>{a.channel}{t("：总分配")}{a.qty}{t("，已出")}{a.shipped_qty}{t("，待出")}{a.qty-a.shipped_qty-a.released_qty}{t("，已退")}{a.returned_qty}</small>):t("审批后锁定")}</td></tr>)}</tbody></table></div>
    {(can("wholesale.approve")&&(o.status==="pending"||active))&&<div className="wh-action-box"><h5>{o.status==="pending"?t("管理员审批"):t("调整供应链负责人")}</h5>{ownApproval&&o.status==="pending"&&<p className="wh-warning">{t("本单申请人或销售负责人不能自行审批，请另一位管理员处理。")}</p>}<div className="wh-grid"><Field label={t("供应链负责人")}><select value={supply} onChange={e=>setSupply(e.target.value)}><option value="">{t("请选择")}</option>{data.users.filter((u:Row)=>u.role==="供应链").map((u:Row)=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label={t("审批 / 调整原因")}><input value={reason} onChange={e=>setReason(e.target.value)} placeholder={t("赊销、驳回、改派或取消时必填")}/></Field></div>{o.status==="pending"&&<label className="wh-check"><input type="checkbox" checked={stockConfirmed} onChange={e=>setStockConfirmed(e.target.checked)}/>{t("已核对 TikTok、Shopee 为可分别扣减的独立库存份额，没有重复计算同一批实物")}</label>}<div className="wh-actions">{o.status==="pending"?<><button className="btn primary" disabled={busy||ownApproval||!supply||!stockConfirmed} onClick={()=>mutate("orderApprove",{...base,supplyUserId:supply,stockBasisConfirmed:stockConfirmed,reason})}>{t("批准并锁库存")}</button><button className="btn danger" disabled={busy||ownApproval||reason.length<4} onClick={()=>mutate("orderReject",{...base,reason})}>{t("驳回")}</button></>:<button className="btn" disabled={busy||!supply||reason.length<4} onClick={()=>mutate("orderReassign",{...base,supplyUserId:supply,reason})}>{t("保存改派")}</button>}{o.status==="partial"&&<button className="btn danger" disabled={busy||reason.length<4} onClick={()=>mutate("orderCloseRemainder",{...base,reason})}>{t("取消未发余量并结单")}</button>}{!o.items.some((i:Row)=>i.shipped_qty>0)&&<button className="btn danger" disabled={busy||reason.length<4} onClick={()=>mutate("orderCancel",{...base,reason})}>{t("取消订单并释放预留")}</button>}</div>{!supply&&<p className="wh-copy">{t("请先由管理员在账号权限中配置已登录成员的供应链岗位。")}</p>}</div>}
    {o.status==="pending"&&actor.role!=="管理员"&&can("wholesale.create")&&<div className="wh-actions"><input aria-label={t("撤回申请原因")} value={reason} onChange={e=>setReason(e.target.value)} placeholder={t("填写撤回申请原因")}/><button className="btn danger" disabled={busy||reason.length<4} onClick={()=>mutate("orderCancel",{...base,reason})}>{t("撤回申请")}</button></div>}
    {active&&can("wholesale.ship")&&<><div className="wh-actions">{o.status==="approved"&&<button className="btn" disabled={busy} onClick={()=>mutate("orderPack",base)}>{t("供应链已接单，安排打包")}</button>}</div><ShipmentForm order={o} busy={busy} mutate={mutate} refresh={refresh} notice={notice}/></>}
    <div className="wh-actions">{can("wholesale.finance")&&<button className="btn" onClick={()=>setShowFinance(!showFinance)}>{t("回款 / 开票登记")}</button>}{can("wholesale.return")&&o.items.some((i:Row)=>i.shipped_qty>i.returned_qty)&&<button className="btn" onClick={()=>setShowReturn(!showReturn)}>{t("退货实收登记")}</button>}</div>
    {showFinance&&<><FinanceForm order={o} busy={busy} mutate={mutate}/><FinanceCorrection order={o} busy={busy} mutate={mutate}/></>} {showReturn&&<ReturnForm order={o} busy={busy} mutate={mutate}/>}
    <h5>{t("发货记录")}</h5>{!o.shipments.length?<Empty>{t("尚未发货。")}</Empty>:o.shipments.map((s:Row)=><div className="wh-history" key={s.id}><strong>{s.shipment_no} · {s.business_date}</strong><p>{s.warehouse} → {s.carrier} {t("单号：")}{s.tracking_no||t("凭照片 / 视频出库")}</p><p>{s.items.map((i:Row)=>`${o.items.find((r:Row)=>r.id===i.order_item_id)?.sku} × ${i.qty}`).join("；")}</p><div className="wh-actions">{s.proofs.map((f:Row)=><a key={f.id} href={`/api/wholesale/files?id=${encodeURIComponent(f.id)}&lang=${language}`} target="_blank" rel="noreferrer">{t("查看")}{f.name}</a>)}</div></div>)}
    <h5>{t("结算与退货记录")}</h5><div className="table-wrap"><table><thead><tr><th>{t("日期")}</th><th>{t("类型")}</th><th>{t("金额 IDR")}</th><th>{t("凭证")}</th><th>{t("说明")}</th></tr></thead><tbody>{o.entries.map((r:Row)=><tr key={r.id}><td>{r.business_date}</td><td>{t(financeLabels[r.kind]||({receipt_void:"回款冲正",refund_void:"退款冲正",receipt_unallocate:"撤销收款核销"} as Row)[r.kind]||r.kind)}</td><td>{money(r.amount)}</td><td>{r.reference}</td><td>{r.note}</td></tr>)}{o.returns.map((r:Row)=><tr key={r.id}><td>{r.business_date}</td><td>{t("退货")}{r.qty} {t("件 ·")}{r.resellable?t("可售"):t("隔离")}</td><td>{money(r.amount)}</td><td>{r.proof_ref}</td><td>{r.reason}</td></tr>)}</tbody></table></div>{!o.entries.length&&!o.returns.length&&<Empty>{t("尚无回款、开票或退货记录。")}</Empty>}
  </Panel>;
}

function ShipmentForm({order:o,busy,mutate,refresh,notice}:{order:Row;busy:boolean;mutate:Mutate;refresh:()=>Promise<void>;notice:(s:string)=>void}){
  const {t,language,money}=useWholesaleLanguage();
  const [form,setForm]=useState({businessDate:today(),trackingNo:"",carrier:"",warehouse:"",note:"",handoverConfirmed:false}),[quantities,setQuantities]=useState<Record<string,string>>(Object.fromEntries(o.items.map((i:Row)=>[i.id,String(i.qty-i.shipped_qty)]))),[proofIds,setProofIds]=useState<string[]>(o.files.map((f:Row)=>f.id)),[file,setFile]=useState<File|null>(null),[uploading,setUploading]=useState(false);
  const upload=async()=>{if(!file)return;setUploading(true);try{const form=new FormData();form.append("orderId",o.id);form.append("file",file);const r=await responseJson(await fetch(`/api/wholesale/files?lang=${language}`,{method:"POST",body:form}));setProofIds([...proofIds,r.id]);setFile(null);await refresh();notice("凭证已上传，请核对实际出库数量后确认发货。");}catch(e){notice(e instanceof Error?e.message:"凭证上传失败");}finally{setUploading(false);}};
  return <form className="wh-action-box" onSubmit={async e=>{e.preventDefault();await mutate("orderShip",{orderId:o.id,version:o.version,...form,proofIds,items:o.items.filter((i:Row)=>Number(quantities[i.id])>0).map((i:Row)=>({itemId:i.id,qty:Number(quantities[i.id])}))});}}><h5>{t("仓库实际发货登记")}</h5><p className="wh-copy">{t("可分批发货；未发的 SKU 填 0。物流单号与出库照片／视频至少提供一种。上传凭证本身不会改变发货状态。")}</p>{o.payment_terms==="prepaid"&&o.outstanding>0&&<p className="wh-warning">{t("先款后货订单仍待收")}{money(o.outstanding)}{t("；财务确认前无法提交发货。")}</p>}<div className="wh-grid">{o.items.filter((i:Row)=>i.qty>i.shipped_qty).map((i:Row)=><Field key={i.id} label={t("{0} · 剩余 {1} 件",[i.sku,i.qty-i.shipped_qty])}><input type="number" min="0" max={i.qty-i.shipped_qty} step="1" value={quantities[i.id]} onChange={e=>setQuantities({...quantities,[i.id]:e.target.value})}/></Field>)}{[["warehouse","实际发货仓库"],["carrier","承运商 / 自提方式"],["trackingNo","物流单号（与出库影像二选一）"]].map(([key,label])=><Field key={key} label={label}><input required={key!=="trackingNo"} value={String(form[key as keyof typeof form])} onChange={e=>setForm({...form,[key]:e.target.value})}/></Field>)}<Field label={t("实际出库日期")}><input required type="date" max={today()} min={o.business_date} value={form.businessDate} onChange={e=>setForm({...form,businessDate:e.target.value})}/></Field></div><div className="wh-upload"><Field label={t("出库照片或视频 · 每份不超过20MB")}><span className="wh-file-control"><span>{t("选择照片或视频")}</span><span className="wh-file-name">{file?.name||t("未选择文件")}</span><input type="file" aria-label={t("选择照片或视频")} accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime" onChange={e=>setFile(e.target.files?.[0]||null)}/></span></Field><button type="button" className="btn" disabled={!file||uploading||busy} onClick={upload}>{uploading?t("上传中…"):t("上传凭证")}</button></div><div>{o.files.map((f:Row)=><label className="wh-check" key={f.id}><input type="checkbox" checked={proofIds.includes(f.id)} onChange={e=>setProofIds(e.target.checked?[...proofIds,f.id]:proofIds.filter(id=>id!==f.id))}/>{f.name}</label>)}</div><label className="wh-check"><input type="checkbox" checked={form.handoverConfirmed} onChange={e=>setForm({...form,handoverConfirmed:e.target.checked})}/>{t("已与仓库核实，货物已实际交付承运人或客户，数量与本次登记一致")}</label><button className="btn primary" disabled={busy||uploading||!form.handoverConfirmed||(o.payment_terms==="prepaid"&&o.outstanding>0)}>{t("确认本次发货并扣库存")}</button></form>;
}

function FinanceForm({order:o,busy,mutate}:{order:Row;busy:boolean;mutate:Mutate}){
  const {t}=useWholesaleLanguage();
  const [form,setForm]=useState({kind:"receipt",amount:String(o.outstanding||""),reference:"",businessDate:today(),note:""});
  return <form className="wh-action-box" onSubmit={async e=>{e.preventDefault();await mutate("financeAdd",{orderId:o.id,version:o.version,...form});}}><h5>{t("财务核销")}</h5><p className="wh-copy">{t("核对销售公司对公账户实际到账后再确认回款。上传转账截图或订单发货不代表到账。金额和票据按实际记录，原记录不能直接删除。")}</p><div className="wh-grid"><Field label={t("登记类型")}><select value={form.kind} onChange={e=>{const kind=e.target.value;setForm({...form,kind,amount:String(kind==="receipt"?o.outstanding:kind==="refund"?o.refundDue:kind==="invoice"?o.invoiceRemaining:o.invoiced)});}}>{Object.entries(financeLabels).map(([k,v])=><option key={k} value={k}>{t(v)}</option>)}</select></Field><Field label={t("金额 IDR")}><input required type="number" min="1" step="1" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label={t("唯一银行流水号 / 票据编号")}><input required value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></Field><Field label={t("实际业务日期")}><input required type="date" max={today()} min={o.business_date} value={form.businessDate} onChange={e=>setForm({...form,businessDate:e.target.value})}/></Field><Field label={t("核对说明及账户 / 票据依据")} wide><textarea required minLength={4} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></Field></div><button className="btn primary" disabled={busy}>{t("确认财务记录")}</button></form>;
}
function ReturnForm({order:o,busy,mutate}:{order:Row;busy:boolean;mutate:Mutate}){
  const {t}=useWholesaleLanguage();
  const [form,setForm]=useState({itemId:"",qty:"1",businessDate:today(),reason:"",proofRef:"",receivedConfirmed:false,resellable:false});
  return <form className="wh-action-box" onSubmit={async e=>{e.preventDefault();await mutate("orderReturn",{orderId:o.id,version:o.version,...form});}}><h5>{t("退货验收入库")}</h5><div className="wh-grid"><Field label={t("原订单 SKU")}><select required value={form.itemId} onChange={e=>setForm({...form,itemId:e.target.value})}><option value="">{t("选择 SKU")}</option>{o.items.filter((i:Row)=>i.shipped_qty>i.returned_qty).map((i:Row)=><option key={i.id} value={i.id}>{i.sku} {t("· 最多")}{i.shipped_qty-i.returned_qty} {t("件")}</option>)}</select></Field><Field label={t("实际收回件数")}><input required type="number" min="1" step="1" value={form.qty} onChange={e=>setForm({...form,qty:e.target.value})}/></Field><Field label={t("收回日期")}><input required type="date" max={today()} min={o.business_date} value={form.businessDate} onChange={e=>setForm({...form,businessDate:e.target.value})}/></Field><Field label={t("验收单号 / 凭证引用")}><input required value={form.proofRef} onChange={e=>setForm({...form,proofRef:e.target.value})}/></Field><Field label={t("退货原因")} wide><input required minLength={4} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></Field></div><label className="wh-check"><input type="checkbox" checked={form.receivedConfirmed} onChange={e=>setForm({...form,receivedConfirmed:e.target.checked})}/>{t("仓库已经实际收回以上货品")}</label><label className="wh-check"><input type="checkbox" checked={form.resellable} onChange={e=>setForm({...form,resellable:e.target.checked})}/>{t("已验收合格，可直接恢复可售库存；未勾选则进入隔离库存")}</label><p className="wh-copy">{t("按原扣库渠道归还库存；退货冲减销售，实际退款由财务另行登记。")}</p><button className="btn primary" disabled={busy||!form.receivedConfirmed}>{t("确认退货入库")}</button></form>;
}

function FinanceReconciliation({report:r,exporting,download}:{report:Row;exporting:boolean;download:()=>void}){
  const {t,money}=useWholesaleLanguage();
  const totals=r.totals;
  return <><Panel title={t("{0} 财务月度对账",[r.month])} action={<button className="btn primary" disabled={exporting} onClick={download}>{exporting?t("生成中…"):t("导出本月对账Excel")}</button>}>
    <p className="wh-copy">{t("统计截至")}{r.cutoff}{t("，共")}{r.orderCount} {t("笔订单。")}{r.isClosedMonth?t("历史月份按期末业务日期重新计算，之后收到的款项归入之后月份。"):t("本月为截至今日的累计对账，月末可再次导出。")}</p>
    <div className="wh-metrics">{[["期初待收",totals.openingReceivable],["期初预收或待退",totals.openingAdvance],["本月出库销售额",totals.salesAmount],["本月退货金额",totals.returnAmount],["本月回款",totals.receipts],["本月退款",totals.refunds],["期末待收",totals.closingReceivable],["期末预收或待退",totals.closingAdvance],["本月净销售额",totals.netSales]].map(([label,value])=><article key={String(label)}><span>{t(label)}</span><strong>{money(value)}</strong></article>)}</div>
    <p className="wh-copy">{t("期末余额 = 期初余额 + 出库销售额 − 退货金额 − 回款 + 退款。余额为正表示已出库待收，为负表示预收或待退款。各订单余额分别列示，避免不同客户互相抵消。")}</p>
    <div className="table-wrap"><table><thead><tr><th>{t("订单 / 客户")}</th><th>{t("销售")}</th><th>{t("期初余额")}</th><th>{t("本月出库销售额")}</th><th>{t("退货金额")}</th><th>{t("回款 / 退款")}</th><th>{t("结算金额净回款")}</th><th>{t("期末余额")}</th><th>{t("期末结算状态")}</th></tr></thead><tbody>{r.rows.map((o:Row)=><tr key={o.id}><td>{o.orderNo}<small>{o.customerName}</small></td><td>{o.salesName}</td><td>{money(o.openingBalance)}</td><td>{money(o.salesAmount)}</td><td>{money(o.returnAmount)}</td><td>{money(o.receipts)}<small>{t("退款")}{money(o.refunds)}</small></td><td>{money(o.netReceipts)}</td><td><strong>{money(o.closingBalance)}</strong></td><td><Badge value={o.settlementStatus}/></td></tr>)}</tbody></table></div>
    {!r.rows.length&&<Empty>{t("截至该月份暂无订单。")}</Empty>}
  </Panel><Panel title={t("Excel对账内容")}><p className="wh-copy">{t("一份文件包含订单总表、月度对账、SKU出库明细、收款退款明细、开票明细、退货明细及对账说明与汇总。客户电话和订单编号按文本保存，印尼盾金额按数字保存，方便财务直接筛选、汇总和核对银行流水。")}</p></Panel></>;
}

function Dashboard({dashboard:d}:{dashboard:Row}){
  const {t,fmt,money}=useWholesaleLanguage();
  const max=Math.max(1,...d.customers.map((c:Row)=>Math.abs(c.amount)));
  return <><Panel title={t("{0} 客户销售贡献",[d.month])}><p className="wh-copy">{t("净销售额 = 当月实际发货金额 − 当月退货金额。客户贡献以全体可见客户净销售额为分母；净额不为正时不计算占比。SKU 数按编码去重，件数按数量累加；仅退货的客户也纳入本月明细。")}</p><div className="table-wrap"><table><thead><tr><th>{t("客户")}</th><th>{t("净销售额")}</th><th>{t("贡献占比")}</th><th>{t("净件数")}</th><th>{t("SKU 数")}</th><th>{t("相关订单数")}</th></tr></thead><tbody>{d.customers.map((c:Row)=><tr key={c.id}><td><strong>{c.name}</strong><div className="wh-bar"><span style={{width:`${Math.abs(c.amount)/max*100}%`,background:c.amount<0?"#dc4960":undefined}}/></div></td><td>{money(c.amount)}</td><td>{c.contribution===null?"—":`${(c.contribution*100).toFixed(1)}%`}</td><td>{fmt(c.qty)}</td><td>{c.skuCount}</td><td>{c.orderCount}</td></tr>)}</tbody></table></div>{!d.customers.length&&<Empty>{t("本月尚无发货或退货记录。")}</Empty>}</Panel><div className="wh-dashboard-grid"><Panel title={t("SKU 月度销售")}><div className="table-wrap"><table><thead><tr><th>SKU</th><th>{t("净件数")}</th><th>{t("净销售额")}</th><th>{t("客户数")}</th></tr></thead><tbody>{d.skus.map((s:Row)=><tr key={s.sku}><td>{s.sku}<small>{s.name}</small></td><td>{fmt(s.qty)}</td><td>{money(s.amount)}</td><td>{s.customerCount}</td></tr>)}</tbody></table></div></Panel><Panel title={t("销售人员贡献")}><div className="table-wrap"><table><thead><tr><th>{t("销售")}</th><th>{t("净销售额")}</th><th>{t("客户数")}</th><th>{t("SKU 数")}</th></tr></thead><tbody>{d.salespeople.map((s:Row)=><tr key={s.id}><td>{s.name}</td><td>{money(s.amount)}</td><td>{s.customerCount}</td><td>{s.skuCount}</td></tr>)}</tbody></table></div></Panel></div><Panel title={t("月度统计口径")}><div className="wh-detail"><div><p>{t("发货金额")}{money(d.salesAmount)} {t("退货金额")}{money(d.returnAmount)}</p><p>{t("实际发货")}{fmt(d.quantity)} {t("件 实收退货")}{fmt(d.returnQty)} {t("件")}</p><p>{t("本月发生发货的订单")}{d.orderCount} {t("笔；分批跨月订单在各月按实际发货统计。")}</p></div><div><p>{t("本月对公回款")}{money(d.cashReceived)}</p><p>{t("本月实际退款")}{money(d.cashRefunded)}</p><p>{t("当前合同待收款和待退款按全部有效订单计算，包含未出库约定款项。已出库应收及历史期末余额请查看财务月度对账。")}</p></div></div></Panel></>;
}
