import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,readFileSync,readdirSync,writeFileSync,existsSync,renameSync,rmSync,statSync,createReadStream,createWriteStream} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {createHash} from 'node:crypto';
import {Readable} from 'node:stream';
import {pipeline} from 'node:stream/promises';
export const dataRoot=resolve(process.env.LOONGJUMP_DATA_DIR||'./data');
export function migrate(sqlite,migrationDir=resolve('drizzle')){sqlite.exec('PRAGMA foreign_keys=ON; PRAGMA busy_timeout=10000; PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS local_migrations(name TEXT PRIMARY KEY,sha256 TEXT NOT NULL,applied_at TEXT NOT NULL)');for(const name of readdirSync(migrationDir).filter(n=>n.endsWith('.sql')).sort()){const source=readFileSync(resolve(migrationDir,name),'utf8'),hash=createHash('sha256').update(source).digest('hex'),done=sqlite.prepare('SELECT sha256 FROM local_migrations WHERE name=?').get(name);if(done){if(done.sha256!==hash)throw Error(`Applied migration changed: ${name}`);continue}sqlite.exec('BEGIN IMMEDIATE');try{sqlite.exec(source);sqlite.prepare('INSERT INTO local_migrations VALUES (?,?,?)').run(name,hash,new Date().toISOString());sqlite.exec('COMMIT')}catch(e){sqlite.exec('ROLLBACK');throw e}}}
export function openDatabase(path=resolve(dataRoot,'business.sqlite'),{migrations=true}={}){mkdirSync(dirname(path),{recursive:true,mode:0o700});const sqlite=new DatabaseSync(path);if(migrations)migrate(sqlite);sqlite.exec('PRAGMA foreign_keys=ON; PRAGMA busy_timeout=10000');class Statement{constructor(sql,args=[]){this.sql=sql;this.args=args}bind(...args){return new Statement(this.sql,args)}execute(){const s=sqlite.prepare(this.sql);if(s.columns().length){return {results:s.all(...this.args),success:true,meta:{changes:0}}}const r=s.run(...this.args);return {results:[],success:true,meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}}}async first(column){const r=this.execute().results[0];return column?r?.[column]??null:r??null}async all(){return this.execute()}async run(){return this.execute()}async raw(){return this.execute().results.map(Object.values)}}
 return {sqlite,prepare:sql=>new Statement(sql),async batch(statements){sqlite.exec('BEGIN IMMEDIATE');try{const r=statements.map(s=>s.execute());sqlite.exec('COMMIT');return r}catch(e){sqlite.exec('ROLLBACK');throw e}},async exec(sql){sqlite.exec(sql);return {count:1,duration:0}}};}
export function fileBucket(root=resolve(dataRoot,'files')){mkdirSync(root,{recursive:true,mode:0o700});const path=key=>{const hash=createHash('sha256').update(key).digest('hex');return resolve(root,hash)};return {async put(key,body,options={}){const target=path(key),temp=target+'.'+crypto.randomUUID()+'.tmp';try{if(body instanceof ArrayBuffer||ArrayBuffer.isView(body))writeFileSync(temp,new Uint8Array(body.buffer||body),{mode:0o600});else await pipeline(Readable.fromWeb(body),createWriteStream(temp,{mode:0o600}));renameSync(temp,target);writeFileSync(target+'.json',JSON.stringify({key,...options}),{mode:0o600})}catch(e){rmSync(temp,{force:true});throw e}},async get(key){const target=path(key);if(!existsSync(target))return null;return {body:Readable.toWeb(createReadStream(target)),size:statSync(target).size}},async delete(key){rmSync(path(key),{force:true});rmSync(path(key)+'.json',{force:true})}}}
