import {randomUUID} from 'node:crypto';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {businessFingerprint,transaction} from './inventory-baseline.mjs';
import {createBackup,verifyArchive} from './backup.mjs';
const filters={new_product_stage_records:"project_id IN (SELECT id FROM new_product_projects WHERE cycle_month<'2026-10')",new_product_projects:"cycle_month<'2026-10'",plan_changes:"month<'2026-10'",forecast_snapshots:"month<'2026-10'",monthly_submissions:"month<'2026-10'",approval_requests:"type='monthly_plan' AND month<'2026-10'"};
const fail=(m,s=409)=>{throw Object.assign(Error(m),{status:s});},dir=()=>resolve(process.env.LOONGJUMP_BACKUP_DIR||'backups','test-cleanup');
function admin(a){if(a?.role!=='管理员')fail('仅管理员可执行',403);}
function snapshot(db){return Object.fromEntries(Object.entries(filters).map(([t,w])=>[t,db.prepare(`SELECT * FROM ${t} WHERE ${w} ORDER BY rowid`).all()]));}
function audit(db,a,action,id,detail){db.prepare('INSERT INTO audit_logs(id,action,entity_type,entity_id,detail_json,actor_id,actor_name,created_at) VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),action,'test-cleanup',id,JSON.stringify(detail),a.id,a.name,new Date().toISOString());}
export function previewCleanup(db){
 const s=snapshot(db),ids=new Set(s.approval_requests.map(r=>r.id));
 if(s.approval_requests.some(r=>r.status==='approved')||s.new_product_projects.some(r=>r.production_batch_id)||db.prepare('SELECT month,approval_id FROM series_purchase_orders').all().some(r=>r.month<'2026-10'||ids.has(r.approval_id))||db.prepare('SELECT month FROM series_production_orders UNION ALL SELECT month FROM production_batches').all().some(r=>r.month<'2026-10'))fail('测试数据已关联批准或采购生产记录，需先核对，尚未清理');
 if(db.prepare('SELECT month,approval_id FROM plan_changes UNION ALL SELECT month,approval_id FROM forecast_snapshots').all().some(r=>r.month>='2026-10'&&ids.has(r.approval_id)))fail('测试审批关联正式月份，尚未清理');
 const lock=db.prepare("SELECT mode,expires_at FROM system_maintenance WHERE id='global'").get();if(lock?.mode!=='normal'&&lock?.expires_at>new Date().toISOString())fail('系统正在维护');
 return {counts:Object.fromEntries(Object.entries(s).map(([t,r])=>[t,r.length])),fingerprint:businessFingerprint(db),inventory:db.prepare('SELECT COALESCE(SUM(qty),0) n FROM inventory_balances').get().n};
}
export async function applyCleanup(env,a,expected){admin(a);const db=env.DB.sqlite,p=previewCleanup(db);if(p.fingerprint!==expected?.fingerprint)fail('数据已变化，请重新核对');if(!Object.values(p.counts).some(Boolean))fail('没有待清理的测试数据');const id=randomUUID();mkdirSync(dir(),{recursive:true,mode:0o700});const backup=join(dir(),id+'.tar');await createBackup(env,backup);await verifyArchive(backup);
 return transaction(db,()=>{if(previewCleanup(db).fingerprint!==p.fingerprint)fail('备份期间数据变化，请重新核对');writeFileSync(join(dir(),id+'.json'),JSON.stringify(snapshot(db)),{mode:0o600,flag:'wx'});for(const [t,w] of Object.entries(filters))db.exec(`DELETE FROM ${t} WHERE ${w}`);audit(db,a,'testCleanupApply',id,{cutoff:'2026-10-01',counts:p.counts,backup});const result={id,counts:p.counts,inventory:p.inventory};writeFileSync(join(dir(),id+'.result.json'),JSON.stringify({...result,fingerprint:businessFingerprint(db)}),{mode:0o600,flag:'wx'});return result;});
}
export function undoCleanup(env,a,id){admin(a);if(!/^[a-f0-9-]{36}$/.test(id))fail('编号无效',400);const result=JSON.parse(readFileSync(join(dir(),id+'.result.json'),'utf8')),saved=JSON.parse(readFileSync(join(dir(),id+'.json'),'utf8')),db=env.DB.sqlite;return transaction(db,()=>{if(businessFingerprint(db)!==result.fingerprint)fail('清理后已有业务变化，不能直接撤销，请核对备份恢复');for(const [t,rs] of Object.entries(saved).reverse())for(const r of rs){const cols=Object.keys(r);db.prepare(`INSERT INTO ${t}(${cols.join(',')}) VALUES(${cols.map(()=>'?').join(',')})`).run(...cols.map(c=>r[c]));}audit(db,a,'testCleanupUndo',id,{restored:true});return {restored:true};});}
export const cleanupPage=`<!doctype html><html lang="zh"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>清理上线前测试数据</title><style>body{font:16px system-ui;background:#f3f6fa;color:#18324b;padding:24px}main{max-width:850px;margin:auto;background:white;padding:28px;border-radius:16px}p{line-height:1.8;white-space:pre-wrap}button{padding:12px 18px;margin:8px;border:0;border-radius:8px;background:#215fe5;color:white;font:inherit}button:disabled{opacity:.4}</style><main><a href="/">返回后台</a><h1>清理上线前测试数据</h1><p>清理2026年10月之前的备货提交、预测快照、月度审批及变更，以及新品孵化项目和阶段记录。库存、销售、客户和10月起正式记录保留。有采购生产关联时停止。</p><p>执行前完整备份并校验，全程留痕。尚无后续业务变化时可以直接撤销。</p><button id="preview">核对测试数据</button><p id="summary"></p><button id="apply" disabled>备份并清空测试数据</button><button id="undo" hidden>撤销本次清理</button><p id="result" role="status"></p></main><script>
let expected,id;const el=x=>document.getElementById(x),msg=x=>el('result').textContent=x;async function call(action,extra={}){const r=await fetch('/api/test-cleanup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...extra})}),v=await r.json();if(!r.ok)throw Error(v.error);return v;}
el('preview').onclick=async()=>{expected=null;el('apply').disabled=true;try{expected=await call('preview');const c=expected.counts;el('summary').textContent='备货提交 '+c.monthly_submissions+'；审批 '+c.approval_requests+'；预测快照 '+c.forecast_snapshots+'；变更 '+c.plan_changes+'；新品项目 '+c.new_product_projects+'；新品阶段记录 '+c.new_product_stage_records+'。当前库存 '+expected.inventory+' 件。';el('apply').disabled=!Object.values(c).some(Boolean);msg('核对完成，尚未清理。');}catch(e){msg(e.message);}};
el('apply').onclick=async()=>{el('apply').disabled=true;el('preview').disabled=true;msg('正在备份、校验并清理…');try{const v=await call('apply',{expected});id=v.id;expected=null;el('undo').hidden=false;msg('测试备货计划和新品孵化已清空，完整备份已校验。库存保持 '+v.inventory+' 件。编号：'+id);}catch(e){msg(e.message);}finally{el('preview').disabled=false;}};
el('undo').onclick=async()=>{el('undo').disabled=true;try{await call('undo',{id});el('undo').hidden=true;msg('测试记录已恢复，操作记录保留。');}catch(e){msg(e.message);}finally{el('undo').disabled=false;}};
call('status').then(v=>{if(v.id){id=v.id;el('undo').hidden=false;msg('测试记录已清理。编号：'+id);}}).catch(e=>msg(e.message));</script></html>`;
export async function handleCleanup(req,res,env,a){try{admin(a);if(req.method==='GET'){res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(cleanupPage);return;}let size=0,bs=[];for await(const b of req){size+=b.length;if(size>4096)fail('请求过大',413);bs.push(b);}let p;try{p=JSON.parse(Buffer.concat(bs));}catch{fail('格式错误',400);}if(!p||typeof p!=='object')fail('格式错误',400);let v;if(p.action==='preview')v=previewCleanup(env.DB.sqlite);else if(p.action==='apply')v=await applyCleanup(env,a,p.expected);else if(p.action==='undo')v=undoCleanup(env,a,p.id);else if(p.action==='status'){const last=env.DB.sqlite.prepare("SELECT action,entity_id FROM audit_logs WHERE action IN ('testCleanupApply','testCleanupUndo') ORDER BY rowid DESC LIMIT 1").get();v={id:last?.action==='testCleanupApply'?last.entity_id:null};}else fail('无效操作',400);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(v));}catch(e){console.error('Test cleanup:',e.message);res.writeHead(e.status||500,{'content-type':'application/json'});res.end(JSON.stringify({error:e.status?e.message:'清理未完成，请查看服务器日志'}));}}
