export async function systemChecks(db){
 const tests=[
 ['采购负责人无效',"SELECT p.id FROM series_purchase_orders p LEFT JOIN users u ON u.id=p.assigned_supply_user_id WHERE p.status NOT IN ('completed','cancelled') AND (u.id IS NULL OR u.role<>'供应链' OR u.active<>1)"],
 ['审批结果与执行订单冲突',"SELECT a.id FROM approval_requests a WHERE a.status<>'approved' AND EXISTS(SELECT 1 FROM series_purchase_orders p WHERE p.approval_id=a.id AND p.status<>'cancelled')"],
 ['发运数量超过生产上限',"SELECT i.id FROM series_production_order_items i WHERE COALESCE((SELECT SUM(s.shipped_qty) FROM shipment_batch_items s WHERE s.production_order_item_id=i.id),0)+COALESCE((SELECT SUM(t.shipped_qty) FROM transport_batch_items t WHERE t.production_order_item_id=i.id),0)>MIN(i.planned_qty,i.produced_qty)"],
 ['样品确认版本已过期',"SELECT p.id FROM new_product_projects p JOIN new_product_stage_records s ON s.project_id=p.id AND s.stage_key='sample' WHERE p.stage='sample' AND EXISTS(SELECT 1 FROM new_product_stage_records c WHERE c.project_id=p.id AND c.stage_key IN ('sample_development','sample_operations') AND COALESCE(c.source_version,0)<>s.version)"],
 ['银行收款核销余额不一致',"SELECT b.id FROM wholesale_bank_receipts b WHERE b.allocated_amount<>COALESCE((SELECT SUM(CASE WHEN e.kind='receipt' THEN e.amount WHEN e.kind='receipt_unallocate' THEN -e.amount ELSE 0 END) FROM wholesale_finance_entries e WHERE e.bank_receipt_id=b.id),0) OR b.refunded_amount<>COALESCE((SELECT SUM(e.amount) FROM wholesale_bank_events e WHERE e.receipt_id=b.id AND e.kind='refund'),0) OR b.voided_amount<>COALESCE((SELECT SUM(e.amount) FROM wholesale_bank_events e WHERE e.receipt_id=b.id AND e.kind='receipt_void'),0)"],
 ['库存隔离来源无法对账',"SELECT b.site||'/'||b.channel||'/'||b.sku id FROM inventory_balances b WHERE b.quarantine_qty<>COALESCE((SELECT SUM(i.quarantine_qty) FROM transport_leg_items i JOIN transport_legs l ON l.id=i.leg_id WHERE l.site=b.site AND l.channel=b.channel AND i.sku=b.sku),0)+CASE WHEN b.site='印尼' THEN COALESCE((SELECT SUM(CAST(json_extract(a.value,'$.qty') AS INTEGER)) FROM wholesale_returns r JOIN wholesale_order_items i ON i.id=r.order_item_id,json_each(r.allocations_json) a WHERE r.resellable=0 AND i.sku=b.sku AND json_extract(a.value,'$.channel')=b.channel),0)-COALESCE((SELECT SUM(q.qty) FROM wholesale_return_resolutions q JOIN wholesale_returns r ON r.id=q.return_id JOIN wholesale_order_items i ON i.id=r.order_item_id WHERE i.sku=b.sku AND q.channel=b.channel),0) ELSE 0 END"],
 ['订单预留与平台库存预留不一致',"SELECT b.site||'/'||b.channel||'/'||b.sku id FROM inventory_balances b WHERE b.site='印尼' AND b.reserved_qty<>COALESCE((SELECT SUM(a.qty-a.shipped_qty-a.released_qty) FROM wholesale_allocations a JOIN wholesale_order_items i ON i.id=a.order_item_id WHERE i.sku=b.sku AND a.channel=b.channel),0)"],
 ['关账快照缺失',"SELECT month id FROM wholesale_finance_periods WHERE status='closed' AND (json_valid(snapshot_json)=0 OR json_extract(snapshot_json,'$.closedMonth')<>month)"],
 ['重复客户待合并核对',"SELECT MIN(id) id FROM wholesale_customers WHERE active=1 GROUP BY lower(trim(name)),replace(replace(phone,' ',''),'-','') HAVING COUNT(*)>1"],
 ['SKU渠道分配数量不守恒',"SELECT id FROM series_purchase_order_items WHERE ordered_qty<>COALESCE((SELECT SUM(CAST(json_extract(value,'$.qty') AS INTEGER)) FROM json_each(allocations_json)),0)"],
 ];
 const issues=[];for(const [type,sql] of tests){const result=await db.prepare(sql).all();if(result.success!==true)throw Error('全站逻辑检查读取失败');for(const r of result.results||[])issues.push({level:type==='样品确认版本已过期'?'warning':'critical',type,detail:String(r.id)});}return {checkedAt:new Date().toISOString(),checkCount:tests.length,issues};
}
