// Static Indonesian UI catalog. Business records and identifiers are never translated.
export const WHOLESALE_ID={
  "批发订单明细":"Rincian pesanan grosir",
  "发货明细":"Rincian pengiriman",
  "退货验收单":"Penerimaan retur",
  "{0}导入":"Impor {0}",
  "Excel / CSV 导入":"Impor Excel / CSV",
  "下载导入模板":"Unduh templat impor",
  "选择导入文件":"Pilih berkas impor",
  "工作表":"Lembar kerja",
  "正在解析文件…":"Membaca berkas…",
  "正在导入…":"Mengimpor…",
  "确认导入到表单":"Masukkan ke formulir",
  "下载模板填写，选择文件后预览；确认导入会替换当前表单明细，提交后才写入系统。":"Unduh dan isi templat, pilih berkas untuk pratinjau. Konfirmasi impor mengganti rincian formulir; data disimpan setelah pengajuan.",
  "每个文件对应当前客户的一张出库申请，最多20个SKU；导入数量及成交单价后，核对客户和账期再提交审批。":"Satu berkas untuk satu permohonan pengeluaran pelanggan ini, maksimal 20 SKU. Periksa pelanggan dan syarat pembayaran sebelum mengajukan persetujuan.",
  "导入当前订单的实际发货数量；未出现在文件中的SKU不会发货。核对仓库、物流及实际交付后再确认扣库。":"Impor jumlah pengiriman aktual untuk pesanan ini. SKU yang tidak tercantum tidak dikirim. Periksa gudang, logistik dan penyerahan fisik sebelum mengurangi stok.",
  "每份退货验收单导入一条SKU明细，包含数量、收回日期、验收单号和原因。导入后仍需确认仓库实收及质检结果。":"Impor satu SKU per penerimaan retur, termasuk jumlah, tanggal, nomor bukti dan alasan. Tetap konfirmasikan penerimaan fisik serta hasil pemeriksaan.",
  "发现 {0} 行错误，整份文件暂不导入。":"Ada kesalahan pada {0} baris. Seluruh berkas belum diimpor.",
  "第{0}行：{1}":"Baris {0}: {1}",
  "下载全部错误":"Unduh semua kesalahan",
  "预览 {0} 行（最多显示20行） · 尚未写入系统":"Pratinjau {0} baris (maksimal 20 ditampilkan) · Belum disimpan",
  "行号":"Baris",
  "清除文件":"Hapus pilihan berkas",
  "导入完成，请核对下方数据或单据状态。":"Impor selesai. Periksa data atau status dokumen di bawah.",
  "尚未确认保存，请查看页面错误提示后重试。":"Penyimpanan belum dikonfirmasi. Periksa pesan kesalahan sebelum mencoba lagi.",
  "明细编号":"ID rincian",
  "数量":"Jumlah",
  "验收单号":"Nomor bukti penerimaan",
  "选择照片或视频":"Pilih foto atau video",
  "未选择文件":"Belum ada berkas dipilih",
  "待审批": "Menunggu persetujuan",
  "待打包": "Menunggu pengemasan",
  "打包中": "Sedang dikemas",
  "部分发货": "Dikirim sebagian",
  "已完成发货": "Pengiriman selesai",
  "部分发货已结单": "Ditutup setelah kirim sebagian",
  "已驳回": "Ditolak",
  "已取消": "Dibatalkan",
  "确认回款": "Konfirmasi pembayaran masuk",
  "确认退款": "Konfirmasi pengembalian dana",
  "登记开票": "Catat faktur",
  "登记开票冲销": "Catat pembatalan faktur",
  "已回款": "Pembayaran lunas",
  "未回款": "Belum dibayar",
  "待退款": "Menunggu pengembalian dana",
  "操作失败": "Tindakan gagal",
  "导出失败": "Ekspor gagal",
  "全部权限内订单已导出，含客户、出库、结算及财务流水。": "Semua pesanan yang dapat Anda akses telah diekspor, termasuk pelanggan, pengiriman, pelunasan, dan transaksi keuangan.",
  "{0}月度对账已导出，含期初与期末余额。": "Rekonsiliasi {0} telah diekspor, termasuk saldo awal dan akhir.",
  "导出失败，请稍后重试": "Ekspor gagal. Silakan coba lagi.",
  "该操作此前已保存，未重复处理。": "Tindakan ini sudah tersimpan dan tidak diproses dua kali.",
  "已保存。库存、订单和结算状态已更新。": "Tersimpan. Stok, pesanan, dan status pembayaran telah diperbarui.",
  "操作已保存，列表刷新暂时失败，请点击刷新核对。": "Tindakan tersimpan, tetapi daftar belum diperbarui. Klik Muat ulang untuk memeriksa.",
  "保存失败，请保留填写内容后重试": "Gagal menyimpan. Pertahankan isian Anda, lalu coba lagi.",
  "印尼线下批发": "Grosir Offline Indonesia",
  "正在读取批发订单…": "Memuat pesanan grosir…",
  "重新读取": "Muat ulang data",
  "本月出库销售额": "Penjualan terkirim bulan ini",
  "本月出库件数": "Unit terkirim bulan ini",
  "本月客户 / SKU": "Pelanggan / SKU bulan ini",
  "本月回款": "Pembayaran masuk bulan ini",
  "当前合同待收款": "Sisa tagihan kontrak saat ini",
  "当前合同待退款": "Dana perlu dikembalikan saat ini",
  "序号": "No.",
  "订单号": "Nomor pesanan",
  "订单日期": "Tanggal pesanan",
  "完成发货时间（印尼西部）": "Waktu pengiriman selesai (WIB)",
  "客户编号": "Kode pelanggan",
  "客户": "Pelanggan",
  "联系人": "Nama kontak",
  "电话": "Telepon",
  "城市": "Kota",
  "收货地址": "Alamat pengiriman",
  "销售负责人": "Penanggung jawab penjualan",
  "SKU种类数": "Jumlah jenis SKU",
  "订单件数": "Jumlah unit pesanan",
  "已发件数": "Unit terkirim",
  "订单金额IDR": "Nilai pesanan IDR",
  "出库销售额IDR": "Penjualan terkirim IDR",
  "退货金额IDR": "Nilai retur IDR",
  "净销售额IDR": "Penjualan bersih IDR",
  "按已出库待收款IDR": "Piutang barang terkirim IDR",
  "按已出库结算状态": "Status pelunasan barang terkirim",
  "合同待收款IDR": "Sisa tagihan kontrak IDR",
  "净回款IDR": "Pembayaran masuk bersih IDR",
  "回款状态": "Status pembayaran",
  "是否需开票": "Perlu faktur",
  "有效开票金额IDR": "Nilai faktur berlaku IDR",
  "开票状态": "Status faktur",
  "履约状态": "Status pemenuhan",
  "是": "Ya",
  "否": "Tidak",
  "申请出库 → 独立审批 → 供应链发货 → 回款与开票跟进": "Ajukan pengeluaran → Persetujuan terpisah → Pengiriman → Pembayaran dan faktur",
  "统计月份": "Bulan laporan",
  "刷新": "Muat ulang",
  "正在生成Excel…": "Menyiapkan Excel…",
  "管理员": "Administrator",
  "财务": "Keuangan",
  "一键导出全部订单": "Ekspor semua pesanan",
  "导出负责订单": "Ekspor pesanan saya",
  "＋ 出库申请": "＋ Ajukan pengeluaran",
  "关闭提示": "Tutup pemberitahuan",
  "已实际出库即计入销售额，按成交单价 × 出库件数计算，币种为 IDR 印尼盾。未回款、未开票及部分出库均计入；退货另列并冲减净销售额。": "Barang yang sudah keluar gudang dihitung sebagai penjualan: harga satuan transaksi × unit terkirim, dalam IDR. Tetap dihitung meski belum dibayar, belum dibuatkan faktur, atau baru dikirim sebagian. Retur dicatat terpisah dan mengurangi penjualan bersih.",
  "线下批发视图": "Tampilan grosir offline",
  "全部订单": "Semua pesanan",
  "完成订单": "Pengiriman selesai",
  "客户档案": "Data pelanggan",
  "月度销售看板": "Dasbor penjualan bulanan",
  "财务月度对账": "Rekonsiliasi bulanan",
  "业务检查{0}": "Pemeriksaan bisnis{0}",
  "业务检查": "Pemeriksaan bisnis",
  "已完成发货的订单": "Pesanan yang selesai dikirim",
  "订单台账": "Daftar pesanan",
  "导出筛选列表CSV": "Ekspor hasil filter CSV",
  "搜索订单": "Cari pesanan",
  "订单号、客户、电话、销售或 SKU": "Nomor pesanan, pelanggan, telepon, staf penjualan, atau SKU",
  "全部履约状态": "Semua status pemenuhan",
  "笔 · 发货完成后继续跟进回款与开票": "pesanan · Setelah pengiriman selesai, lanjutkan penagihan dan pembuatan faktur",
  "序号 / 日期": "No. / Tanggal",
  "订单与客户": "Pesanan dan pelanggan",
  "销售 / SKU": "Penjualan / SKU",
  "发货件数": "Unit dikirim",
  "出库销售额 / 订单金额": "Penjualan terkirim / Nilai pesanan",
  "订单回款": "Pembayaran pesanan",
  "开票": "Faktur",
  "履约": "Pemenuhan",
  "操作": "Tindakan",
  "种 SKU": "jenis SKU",
  "已发 / 申请": "Terkirim / Diajukan",
  "订单": "Pesanan ",
  "已收": "Diterima ",
  "合同待收": "Sisa tagihan kontrak ",
  "待分配供应链": "Petugas rantai pasok belum ditugaskan",
  "查看 / 处理": "Lihat / Proses",
  "暂无符合条件的订单。销售建立客户档案后即可提出出库申请。": "Belum ada pesanan yang sesuai. Buat data pelanggan terlebih dahulu untuk mengajukan pengeluaran barang.",
  "印尼批发客户": "Pelanggan grosir Indonesia",
  "＋ 新增客户": "＋ Tambah pelanggan",
  "客户编号 / 名称": "Kode / Nama pelanggan",
  "联系人 / 电话": "Kontak / Telepon",
  "城市 / 收货地址": "Kota / Alamat pengiriman",
  "订单 / 合同待收款": "Pesanan / Sisa tagihan kontrak",
  "笔": "pesanan",
  "暂无客户，请先填写真实客户资料。": "Belum ada pelanggan. Silakan masukkan data pelanggan yang sebenarnya.",
  "自动业务检查": "Pemeriksaan bisnis otomatis",
  "重新检查": "Periksa lagi",
  "。系统核对订单合计、库存分配、发货明细、完成状态及逾期结算；管理员同时核对预留余额和实际扣库流水。": ". Sistem memeriksa total pesanan, alokasi stok, rincian pengiriman, status selesai, dan pembayaran terlambat. Administrator juga memeriksa stok yang dicadangkan dan mutasi pengeluaran aktual.",
  "订单 / SKU": "Pesanan / SKU",
  "待处理事项": "Hal yang perlu ditangani",
  "当前检查未发现异常。": "Tidak ditemukan masalah pada pemeriksaan saat ini.",
  "库存与结算规则": "Aturan stok dan pembayaran",
  "首期仅使用印尼 TikTok、Shopee 的独立账面库存份额。偶数均分；单数多出1件由可用库存较多的平台承担，持平时分给 TikTok。": "Tahap awal menggunakan porsi stok tercatat yang terpisah untuk TikTok dan Shopee Indonesia. Jumlah genap dibagi rata; satu unit tambahan pada jumlah ganjil diambil dari platform dengan stok tersedia lebih banyak, atau TikTok jika sama.",
  "单个平台不足时从另一平台补齐；合计不足则不批准。审批先锁定，实际发货才扣账面库存。待上架、隔离和在途货不能用于本次出库。": "Jika stok satu platform kurang, sisanya diambil dari platform lain. Jika total tidak cukup, permohonan tidak disetujui. Persetujuan mencadangkan stok; stok baru dikurangi saat benar-benar dikirim. Barang menunggu penempatan, karantina, dan dalam perjalanan tidak dapat digunakan.",
  "分批发货沿用审批时保存的分配，总扣减等于实际发货总数；单号、照片或视频用于证明实际出库。": "Pengiriman bertahap mengikuti alokasi yang disimpan saat persetujuan. Total pengurangan stok sama dengan jumlah aktual terkirim. Nomor resi, foto, atau video menjadi bukti pengeluaran barang.",
  "原有销售导入可能反映实际超卖，系统保留差异并提示预留不足。先核对差异，再安排线下发货。": "Impor penjualan dapat menunjukkan penjualan melebihi stok. Sistem mempertahankan selisih dan memberi peringatan kekurangan stok cadangan. Periksa selisih sebelum mengirim pesanan offline.",
  "线下销售按实际发货独立统计，不写成 TikTok 或 Shopee 平台订单，不再次导入扣库存。": "Penjualan offline dihitung terpisah berdasarkan pengiriman aktual. Jangan mencatatnya sebagai pesanan TikTok atau Shopee atau mengimpornya kembali, agar stok tidak dikurangi dua kali.",
  "当前分配规则版本为 average_v1。后续虚拟库位通过调拨转入，历史订单按原扣库来源追溯。": "Aturan alokasi saat ini: average_v1. Lokasi stok virtual akan diisi melalui transfer stok; pesanan lama tetap dilacak berdasarkan sumber pengurangan aslinya.",
  "金额单位 IDR；单价按最终商品成交价填写。月度归属按印尼西部时间及业务日期统计；销售额、银行收款和开票金额分别记录。": "Mata uang: IDR. Masukkan harga satuan transaksi akhir. Bulan laporan mengikuti tanggal bisnis dalam WIB. Penjualan, penerimaan bank, dan nilai faktur dicatat terpisah.",
  "客户 / 公司名称": "Nama pelanggan / perusahaan",
  "电话或 WhatsApp": "Telepon atau WhatsApp",
  "完整收货地址": "Alamat pengiriman lengkap",
  "销售": "Penjualan",
  "运营": "Operasional",
  "客户备注": "Catatan pelanggan",
  "保存客户": "Simpan pelanggan",
  "关闭": "Tutup",
  "销售出库申请": "Permohonan pengeluaran barang",
  "印尼": "Indonesia",
  "选择客户": "Pilih pelanggan",
  "新增客户": "Tambah pelanggan",
  "付款条件": "Ketentuan pembayaran",
  "先款后货": "Bayar sebelum pengiriman",
  "赊销账期（须管理员批准）": "Tempo pembayaran (persetujuan administrator)",
  "回款到期日": "Jatuh tempo pembayaran",
  "客户是否需要开票": "Apakah pelanggan memerlukan faktur?",
  "不需要": "Tidak perlu",
  "需要": "Perlu",
  "SKU / 商品": "SKU / Produk",
  "件数": "Jumlah unit",
  "成交单价 IDR": "Harga satuan transaksi IDR",
  "金额": "Nilai",
  "两平台当前可用": "Stok tersedia di kedua platform",
  "第{0}行SKU": "SKU baris {0}",
  "选择 SKU": "Pilih SKU",
  "第{0}行数量": "Jumlah baris {0}",
  "第{0}行单价": "Harga satuan baris {0}",
  "移除": "Hapus baris",
  "订单商品金额": "Nilai produk dalam pesanan ",
  "销售备注及开票抬头资料": "Catatan penjualan dan data penerima faktur",
  "收货要求、约定账期；需开票时填写抬头等资料": "Ketentuan penerimaan, tempo yang disepakati, dan data penerima faktur jika diperlukan",
  "提交后进入管理员审批；审批前不占库存。审批通过后锁定版本，修改商品或价格须取消原单再提交。": "Setelah diajukan, pesanan menunggu persetujuan administrator. Stok belum dicadangkan sebelum persetujuan. Setelah disetujui, versi dikunci. Untuk mengubah produk atau harga, batalkan pesanan lama lalu ajukan kembali.",
  "提交出库申请": "Kirim permohonan pengeluaran",
  "供应链": "Rantai pasok",
  "收起": "Tutup rincian",
  "销售：": "Penjualan: ",
  "供应链：": " Rantai pasok: ",
  "待分配": "Belum ditugaskan",
  "赊销，到期日 {0}": "Tempo pembayaran, jatuh tempo {0}",
  "净回款": "Pembayaran bersih ",
  "出库销售额": "Penjualan terkirim ",
  "· 已出库待收": " · Piutang barang terkirim ",
  "开票：": "Faktur: ",
  "有效金额": " Nilai berlaku ",
  "已取消未发商品金额": "Nilai barang belum dikirim yang dibatalkan ",
  "；剩余有效应收": "; sisa nilai kontrak yang berlaku ",
  "销售备注：": "Catatan penjualan: ",
  "审批 / 调整说明：": "Keterangan persetujuan / perubahan: ",
  "单价": "Harga satuan",
  "申请 / 已发 / 已退": "Diajukan / Terkirim / Diretur",
  "审批锁定来源": "Sumber stok yang dicadangkan",
  "：总分配": ": alokasi total ",
  "，已出": ", terkirim ",
  "，待出": ", belum dikirim ",
  "，已退": ", diretur ",
  "审批后锁定": "Dicadangkan setelah persetujuan",
  "管理员审批": "Persetujuan administrator",
  "调整供应链负责人": "Ubah petugas rantai pasok",
  "本单申请人或销售负责人不能自行审批，请另一位管理员处理。": "Pemohon atau penanggung jawab penjualan tidak dapat menyetujui pesanan sendiri. Minta administrator lain memprosesnya.",
  "供应链负责人": "Penanggung jawab rantai pasok",
  "请选择": "Silakan pilih",
  "审批 / 调整原因": "Alasan persetujuan / perubahan",
  "赊销、驳回、改派或取消时必填": "Wajib untuk tempo, penolakan, pengalihan, atau pembatalan",
  "已核对 TikTok、Shopee 为可分别扣减的独立库存份额，没有重复计算同一批实物": "Saya telah memeriksa bahwa TikTok dan Shopee memiliki porsi stok terpisah yang dapat dikurangi secara mandiri, tanpa menghitung barang fisik yang sama dua kali",
  "批准并锁库存": "Setujui dan cadangkan stok",
  "驳回": "Tolak",
  "保存改派": "Simpan pengalihan",
  "取消未发余量并结单": "Batalkan sisa dan tutup pesanan",
  "取消订单并释放预留": "Batalkan pesanan dan lepas cadangan",
  "请先由管理员在账号权限中配置已登录成员的供应链岗位。": "Minta administrator menetapkan peran rantai pasok kepada anggota yang sudah masuk melalui menu Hak akses akun.",
  "撤回申请原因": "Alasan penarikan permohonan",
  "填写撤回申请原因": "Masukkan alasan penarikan",
  "撤回申请": "Tarik permohonan",
  "供应链已接单，安排打包": "Terima tugas dan mulai pengemasan",
  "回款 / 开票登记": "Catat pembayaran / faktur",
  "退货实收登记": "Catat penerimaan retur",
  "发货记录": "Riwayat pengiriman",
  "尚未发货。": "Belum ada pengiriman.",
  "单号：": " Nomor resi: ",
  "凭照片 / 视频出库": "Bukti foto / video pengeluaran",
  "查看": "Lihat ",
  "结算与退货记录": "Riwayat pembayaran dan retur",
  "日期": "Tanggal",
  "类型": "Jenis",
  "金额 IDR": "Nilai IDR",
  "凭证": "Bukti",
  "说明": "Keterangan",
  "退货": "Retur ",
  "件 ·": " unit · ",
  "可售": "Layak jual",
  "隔离": "Karantina",
  "尚无回款、开票或退货记录。": "Belum ada catatan pembayaran, faktur, atau retur.",
  "凭证已上传，请核对实际出库数量后确认发货。": "Bukti telah diunggah. Periksa jumlah barang yang benar-benar keluar sebelum mengonfirmasi pengiriman.",
  "凭证上传失败": "Gagal mengunggah bukti",
  "仓库实际发货登记": "Catat pengiriman aktual gudang",
  "可分批发货；未发的 SKU 填 0。物流单号与出库照片／视频至少提供一种。上传凭证本身不会改变发货状态。": "Pengiriman dapat dilakukan bertahap. Isi 0 untuk SKU yang belum dikirim. Sertakan nomor resi atau foto/video pengeluaran. Mengunggah bukti saja tidak mengubah status pengiriman.",
  "先款后货订单仍待收": "Pesanan bayar di muka masih memiliki sisa tagihan ",
  "；财务确认前无法提交发货。": "; pengiriman belum dapat dicatat sebelum konfirmasi keuangan.",
  "{0} · 剩余 {1} 件": "{0} · Tersisa {1} unit",
  "实际发货仓库": "Gudang asal aktual",
  "承运商 / 自提方式": "Pengangkut / cara pengambilan",
  "物流单号（与出库影像二选一）": "Nomor resi (atau bukti foto/video)",
  "实际出库日期": "Tanggal keluar gudang aktual",
  "出库照片或视频 · 每份不超过20MB": "Foto / video pengeluaran · Maks. 20 MB per berkas",
  "上传中…": "Mengunggah…",
  "上传凭证": "Unggah bukti",
  "已与仓库核实，货物已实际交付承运人或客户，数量与本次登记一致": "Saya telah mengonfirmasi dengan gudang bahwa barang sudah diserahkan kepada pengangkut atau pelanggan, dengan jumlah sesuai catatan ini",
  "确认本次发货并扣库存": "Konfirmasi pengiriman dan kurangi stok",
  "财务核销": "Pencatatan keuangan",
  "核对销售公司对公账户实际到账后再确认回款。上传转账截图或订单发货不代表到账。金额和票据按实际记录，原记录不能直接删除。": "Konfirmasikan pembayaran setelah dana benar-benar masuk ke rekening perusahaan penjualan. Tangkapan layar transfer atau pengiriman bukan bukti dana telah diterima. Catat nilai dan bukti aktual; catatan asli tidak dapat langsung dihapus.",
  "登记类型": "Jenis pencatatan",
  "唯一银行流水号 / 票据编号": "Nomor unik transaksi bank / faktur",
  "实际业务日期": "Tanggal transaksi aktual",
  "核对说明及账户 / 票据依据": "Keterangan pemeriksaan dan bukti rekening / faktur",
  "确认财务记录": "Konfirmasi catatan keuangan",
  "退货验收入库": "Penerimaan dan pemeriksaan retur",
  "原订单 SKU": "SKU pesanan asal",
  "· 最多": " · Maks. ",
  "件": " unit",
  "实际收回件数": "Jumlah unit retur diterima",
  "收回日期": "Tanggal penerimaan retur",
  "验收单号 / 凭证引用": "Nomor penerimaan / referensi bukti",
  "退货原因": "Alasan retur",
  "仓库已经实际收回以上货品": "Gudang telah menerima kembali barang tersebut secara fisik",
  "已验收合格，可直接恢复可售库存；未勾选则进入隔离库存": "Lulus pemeriksaan dan dapat dikembalikan ke stok layak jual; jika tidak dicentang, masuk stok karantina",
  "按原扣库渠道归还库存；退货冲减销售，实际退款由财务另行登记。": "Stok dikembalikan ke kanal asal pengurangannya. Retur mengurangi penjualan; pengembalian dana dicatat terpisah oleh keuangan.",
  "确认退货入库": "Konfirmasi penerimaan retur",
  "{0} 财务月度对账": "Rekonsiliasi keuangan {0}",
  "生成中…": "Menyiapkan…",
  "导出本月对账Excel": "Ekspor rekonsiliasi bulan ini",
  "统计截至": "Data sampai ",
  "，共": ", total ",
  "笔订单。": " pesanan. ",
  "历史月份按期末业务日期重新计算，之后收到的款项归入之后月份。": "Bulan sebelumnya dihitung berdasarkan tanggal bisnis sampai akhir bulan. Pembayaran setelah itu masuk ke bulan berikutnya.",
  "本月为截至今日的累计对账，月末可再次导出。": "Rekonsiliasi bulan berjalan mencakup data sampai hari ini. Ekspor kembali saat akhir bulan.",
  "期初待收": "Piutang awal",
  "期初预收或待退": "Uang muka / dana retur awal",
  "本月退货金额": "Nilai retur bulan ini",
  "本月退款": "Pengembalian dana bulan ini",
  "期末待收": "Piutang akhir",
  "期末预收或待退": "Uang muka / dana retur akhir",
  "本月净销售额": "Penjualan bersih bulan ini",
  "期末余额 = 期初余额 + 出库销售额 − 退货金额 − 回款 + 退款。余额为正表示已出库待收，为负表示预收或待退款。各订单余额分别列示，避免不同客户互相抵消。": "Saldo akhir = saldo awal + penjualan terkirim − retur − pembayaran masuk + pengembalian dana. Saldo positif berarti piutang barang terkirim; saldo negatif berarti uang muka atau dana yang perlu dikembalikan. Saldo ditampilkan per pesanan agar tidak saling menghapus antar pelanggan.",
  "订单 / 客户": "Pesanan / Pelanggan",
  "期初余额": "Saldo awal",
  "退货金额": "Nilai retur ",
  "回款 / 退款": "Pembayaran / Pengembalian dana",
  "结算金额净回款": "Nilai pelunasan (pembayaran bersih)",
  "期末余额": "Saldo akhir",
  "期末结算状态": "Status pelunasan akhir",
  "退款": "Pengembalian dana ",
  "截至该月份暂无订单。": "Belum ada pesanan sampai bulan ini.",
  "Excel对账内容": "Isi Excel rekonsiliasi",
  "一份文件包含订单总表、月度对账、SKU出库明细、收款退款明细、开票明细、退货明细及对账说明与汇总。客户电话和订单编号按文本保存，印尼盾金额按数字保存，方便财务直接筛选、汇总和核对银行流水。": "Satu berkas berisi daftar pesanan, rekonsiliasi bulanan, rincian pengiriman SKU, pembayaran dan pengembalian dana, faktur, retur, serta panduan dan ringkasan. Telepon dan nomor pesanan disimpan sebagai teks; nilai IDR sebagai angka agar mudah difilter, dijumlahkan, dan dicocokkan dengan mutasi bank.",
  "{0} 客户销售贡献": "Kontribusi penjualan pelanggan {0}",
  "净销售额 = 当月实际发货金额 − 当月退货金额。客户贡献以全体可见客户净销售额为分母；净额不为正时不计算占比。SKU 数按编码去重，件数按数量累加；仅退货的客户也纳入本月明细。": "Penjualan bersih = nilai pengiriman aktual bulan ini − nilai retur bulan ini. Kontribusi pelanggan dihitung dari total penjualan bersih pelanggan yang dapat Anda akses; persentase tidak dihitung jika total tidak positif. SKU dihitung unik berdasarkan kode, sedangkan unit dijumlahkan. Pelanggan yang hanya melakukan retur juga disertakan.",
  "净销售额": "Penjualan bersih",
  "贡献占比": "Kontribusi",
  "净件数": "Unit bersih",
  "SKU 数": "Jumlah SKU",
  "相关订单数": "Jumlah pesanan terkait",
  "本月尚无发货或退货记录。": "Belum ada pengiriman atau retur bulan ini.",
  "SKU 月度销售": "Penjualan SKU bulanan",
  "客户数": "Jumlah pelanggan",
  "销售人员贡献": "Kontribusi staf penjualan",
  "月度统计口径": "Dasar perhitungan bulanan",
  "发货金额": "Nilai pengiriman ",
  "实际发货": "Terkirim aktual ",
  "件 实收退货": " unit; retur diterima ",
  "本月发生发货的订单": "Pesanan dengan pengiriman bulan ini ",
  "笔；分批跨月订单在各月按实际发货统计。": " pesanan. Pengiriman bertahap antar bulan dihitung sesuai pengiriman aktual tiap bulan.",
  "本月对公回款": "Pembayaran ke rekening perusahaan bulan ini ",
  "本月实际退款": "Pengembalian dana aktual bulan ini ",
  "当前合同待收款和待退款按全部有效订单计算，包含未出库约定款项。已出库应收及历史期末余额请查看财务月度对账。": "Sisa tagihan kontrak dan dana yang perlu dikembalikan dihitung dari semua pesanan yang berlaku, termasuk nilai barang belum dikirim. Lihat rekonsiliasi bulanan untuk piutang barang terkirim dan saldo akhir bulan sebelumnya.",
  "回款": "Pembayaran masuk",
  "开票冲销": "Pembatalan faktur",
  "请选择当前或过去的有效月份": "Pilih bulan berjalan atau bulan sebelumnya yang valid",
  "预收或待退款": "Uang muka / dana perlu dikembalikan",
  "未出库": "Belum dikirim",
  "已结清": "Lunas",
  "未结算": "Belum dilunasi",
  "部分结算": "Lunas sebagian",
  "客户名称": "Nama pelanggan",
  "电话或WhatsApp": "Telepon atau WhatsApp",
  "国家": "Negara",
  "币种": "Mata uang",
  "当前履约状态": "Status pemenuhan saat ekspor",
  "当前完成或结单时间UTC": "Waktu selesai / ditutup UTC",
  "申请件数": "Unit diajukan",
  "当前原订单金额IDR": "Nilai awal pesanan saat ekspor IDR",
  "当前取消未发金额IDR": "Nilai sisa dibatalkan saat ekspor IDR",
  "已出库件数": "Unit sudah keluar gudang",
  "退货件数": "Unit retur",
  "累计回款IDR": "Total pembayaran masuk IDR",
  "累计退款IDR": "Total pengembalian dana IDR",
  "结算金额净回款IDR": "Nilai pelunasan bersih IDR",
  "已出库待收款IDR": "Piutang barang terkirim IDR",
  "预收或待退余额IDR": "Saldo uang muka atau dana retur IDR",
  "结算状态按已出库": "Status pelunasan barang terkirim",
  "累计开票IDR": "Total faktur IDR",
  "累计开票冲销IDR": "Total pembatalan faktur IDR",
  "开票记录状态": "Status catatan faktur",
  "当前合同待收款IDR": "Sisa tagihan kontrak saat ekspor IDR",
  "当前合同回款状态": "Status pembayaran kontrak saat ekspor",
  "备注": "Catatan",
  "赊销账期": "Tempo pembayaran",
  "有有效开票记录": "Ada faktur berlaku",
  "未开票": "Belum dibuatkan faktur",
  "不需开票": "Tidak perlu faktur",
  "对账月份": "Bulan rekonsiliasi",
  "统计截止日": "Tanggal batas laporan",
  "期初余额IDR正为应收负为预收": "Saldo awal IDR (+piutang -uang muka)",
  "期初应收IDR": "Piutang awal IDR",
  "期初预收或待退IDR": "Uang muka atau dana retur awal IDR",
  "本月出库销售额IDR": "Penjualan terkirim bulan ini IDR",
  "本月退货件数": "Unit retur bulan ini",
  "本月退货金额IDR": "Nilai retur bulan ini IDR",
  "本月净销售额IDR": "Penjualan bersih bulan ini IDR",
  "本月回款IDR": "Pembayaran masuk bulan ini IDR",
  "本月退款IDR": "Pengembalian dana bulan ini IDR",
  "本月结算金额净回款IDR": "Nilai pelunasan bersih bulan ini IDR",
  "本月开票IDR": "Faktur bulan ini IDR",
  "本月开票冲销IDR": "Pembatalan faktur bulan ini IDR",
  "期末余额IDR正为应收负为预收": "Saldo akhir IDR (+piutang -uang muka)",
  "期末应收IDR": "Piutang akhir IDR",
  "期末预收或待退IDR": "Uang muka atau dana retur akhir IDR",
  "截至期末累计净销售IDR": "Total penjualan bersih s.d. akhir IDR",
  "截至期末累计净回款IDR": "Total pembayaran bersih s.d. akhir IDR",
  "截至期末有效开票IDR": "Faktur berlaku s.d. akhir IDR",
  "可售入库": "Kembali ke stok layak jual",
  "隔离入库": "Masuk stok karantina",
  "导出范围": "Cakupan ekspor",
  "{0}月度对账；含截至截止日的全部权限内订单和期初结转": "Rekonsiliasi {0}; semua pesanan yang dapat diakses sampai tanggal batas beserta saldo awal",
  "全部权限内订单，不受页面搜索、状态或月份筛选限制": "Semua pesanan yang dapat diakses, tanpa pembatasan pencarian, status, atau filter bulan di halaman",
  "导出时间UTC": "Waktu ekspor UTC",
  "导出人员": "Diekspor oleh",
  "导出角色": "Peran pengekspor",
  "IDR 印尼盾": "IDR Rupiah Indonesia",
  "订单总表行数": "Jumlah baris daftar pesanan",
  "出库销售口径": "Dasar penjualan terkirim",
  "实际出库数量乘订单成交单价即计入销售额，包括部分出库、未回款和未开票订单；未出库数量不计销售额": "Penjualan dihitung dari unit aktual keluar gudang dikali harga satuan transaksi, termasuk pengiriman sebagian, belum dibayar, atau belum dibuatkan faktur. Barang belum dikirim tidak dihitung sebagai penjualan.",
  "退货口径": "Dasar retur",
  "原出库销售额保留，实际退货单独列示并冲减净销售额；退款以实际财务记录另行统计": "Penjualan terkirim awal tetap disimpan. Retur aktual dicatat terpisah dan mengurangi penjualan bersih. Pengembalian dana dihitung terpisah berdasarkan catatan keuangan aktual.",
  "结算金额定义": "Definisi nilai pelunasan",
  "结算金额为已核销净回款，即确认回款减确认退款，不自动把销售额当成已收款": "Nilai pelunasan adalah pembayaran bersih yang dikonfirmasi: pembayaran masuk dikurangi pengembalian dana. Penjualan tidak otomatis dianggap sebagai uang diterima.",
  "月度余额公式": "Rumus saldo bulanan",
  "期末余额 = 期初余额 + 本月出库销售额 - 本月退货金额 - 本月回款 + 本月退款": "Saldo akhir = saldo awal + penjualan terkirim bulan ini - retur bulan ini - pembayaran masuk bulan ini + pengembalian dana bulan ini",
  "余额符号": "Arti tanda saldo",
  "正数为已出库待收款；负数为客户预收或待退款。各订单应收和预收分别汇总，不跨客户抵消": "Positif berarti piutang barang terkirim; negatif berarti uang muka pelanggan atau dana yang perlu dikembalikan. Piutang dan uang muka dijumlahkan terpisah per pesanan, tanpa saling menghapus antar pelanggan.",
  "月度取数": "Batas data bulanan",
  "月份按印尼西部时间业务日期；月度对账中的金额按截止日重算，不带入之后回款或之后退货": "Bulan mengikuti tanggal bisnis dalam WIB. Nilai rekonsiliasi dihitung sampai tanggal batas, tanpa memasukkan pembayaran atau retur setelahnya.",
  "状态说明": "Keterangan status",
  "订单总表的当前履约状态、取消金额、合同待收和合同回款状态为导出时状态；月度余额及期末结算状态为截止日口径": "Status pemenuhan, nilai dibatalkan, sisa tagihan, dan status pembayaran kontrak menggunakan keadaan saat ekspor. Saldo bulanan dan status pelunasan akhir menggunakan tanggal batas laporan.",
  "完整性": "Kelengkapan data",
  "每笔订单在订单总表只占一行，SKU出库、收款退款、开票和退货分表记录，不用订单与多个流水直接联表累加": "Satu pesanan menempati satu baris daftar utama. Pengiriman SKU, pembayaran dan pengembalian dana, faktur, serta retur berada di lembar terpisah agar transaksi tidak dihitung berulang.",
  "截至期末订单总表": "Pesanan s.d. Akhir Bulan",
  "全部订单总表": "Semua Pesanan",
  "月度对账": "Rekonsiliasi Bulanan",
  "SKU出库明细": "Rincian Pengiriman SKU",
  "出库单号": "Nomor pengeluaran barang",
  "出库日期": "Tanggal keluar gudang",
  "商品": "Produk",
  "出库件数": "Unit keluar gudang",
  "成交单价IDR": "Harga satuan transaksi IDR",
  "发货仓库": "Gudang asal",
  "承运商": "Pengangkut",
  "物流单号": "Nomor resi",
  "库存扣减来源": "Sumber pengurangan stok",
  "登记时间UTC": "Waktu pencatatan UTC",
  "收款退款明细": "Pembayaran dan Pengembalian",
  "业务日期": "Tanggal bisnis",
  "金额IDR": "Nilai IDR",
  "银行流水或凭证编号": "Nomor transaksi bank / bukti",
  "核销人": "Petugas konfirmasi",
  "开票明细": "Rincian Faktur",
  "票据或冲销编号": "Nomor faktur / pembatalan",
  "登记人": "Dicatat oleh",
  "退货明细": "Rincian Retur",
  "退货实收日期": "Tanggal retur diterima",
  "库存处理": "Penanganan stok",
  "验收凭证": "Bukti penerimaan",
  "对账说明与汇总": "Panduan dan Ringkasan",
  "项目": "Item",
  "内容或金额": "Keterangan atau nilai",
  "印尼线下批发财务对账": "Rekonsiliasi Keuangan Grosir Indonesia",
  "实际出库确认销售 IDR": "Penjualan berdasarkan pengeluaran aktual IDR",
  "业务日期无效或晚于印尼今天": "Tanggal bisnis tidak valid atau melewati hari ini di Indonesia",
  "当前岗位或站点无权处理印尼线下批发业务": "Peran atau negara akun ini tidak diizinkan mengelola grosir offline Indonesia",
  "出库数量": "Jumlah keluar gudang",
  "库存不足：需要{0}件，两个平台合计可用{1}件": "Stok tidak cukup: diperlukan {0} unit, total tersedia di kedua platform {1} unit",
  "无待收款": "Tidak ada sisa tagihan",
  "部分回款": "Dibayar sebagian",
  "待冲销": "Perlu pembatalan faktur",
  "待开票": "Menunggu faktur",
  "部分开票": "Faktur sebagian",
  "已开票": "Faktur lengkap",
  "订单不存在": "Pesanan tidak ditemukan",
  "该订单不在本人责任范围内": "Pesanan ini berada di luar tanggung jawab Anda",
  "订单或库存已变化，或凭证编号重复；请刷新核对后重试，本次未重复扣库": "Pesanan atau stok telah berubah, atau nomor bukti sudah digunakan. Muat ulang dan periksa sebelum mencoba lagi. Stok tidak dikurangi dua kali.",
  "当前账号无权使用印尼线下批发": "Akun ini tidak diizinkan mengakses grosir offline Indonesia",
  "缺少有效操作编号，请刷新后重试": "ID tindakan tidak valid. Muat ulang dan coba lagi.",
  "操作编号已用于其他请求": "ID tindakan sudah digunakan untuk permintaan lain",
  "请选择印尼销售负责人": "Pilih penanggung jawab penjualan Indonesia",
  "请完整填写客户名称、联系人、电话、城市和收货地址": "Lengkapi nama pelanggan, kontak, telepon, kota, dan alamat pengiriman",
  "线下批发首期仅开放印尼": "Grosir offline tahap awal hanya tersedia untuk Indonesia",
  "请选择本人负责的有效客户": "Pilih pelanggan aktif yang menjadi tanggung jawab Anda",
  "每单需要1至20个SKU": "Setiap pesanan harus berisi 1 hingga 20 SKU",
  "IDR成交单价": "Harga satuan transaksi IDR",
  "同一SKU请合并为一行": "Gabungkan SKU yang sama dalam satu baris",
  "{0}尚未建立SKU档案": "SKU {0} belum terdaftar",
  "订单金额超出允许范围": "Nilai pesanan melebihi batas yang diizinkan",
  "赊销订单需填写有效且不早于订单日期的到期日": "Pesanan tempo harus memiliki tanggal jatuh tempo yang valid dan tidak lebih awal dari tanggal pesanan",
  "订单已被其他人更新，请刷新后重试": "Pesanan telah diperbarui oleh orang lain. Muat ulang dan coba lagi.",
  "申请人或本单销售负责人不能审批自己的订单": "Pemohon atau penanggung jawab penjualan tidak dapat menyetujui pesanannya sendiri",
  "仅待审批订单可以处理": "Hanya pesanan yang menunggu persetujuan dapat diproses",
  "请填写驳回原因": "Masukkan alasan penolakan",
  "请选择系统中已启用的供应链负责人": "Pilih petugas rantai pasok yang aktif dalam sistem",
  "请先确认两个平台库存是可分别扣减的独立账面份额，未重复映射同一批实物": "Konfirmasikan bahwa kedua platform memiliki porsi stok terpisah yang dapat dikurangi, tanpa mencatat barang fisik yang sama dua kali",
  "赊销审批须记录放行原因和账期依据": "Persetujuan tempo memerlukan alasan pelepasan barang dan dasar tempo pembayaran",
  "仅部分发货订单可关闭未发余量，并需填写原因": "Hanya pesanan terkirim sebagian yang dapat ditutup sisa pengirimannya. Masukkan alasannya.",
  "无权取消该订单": "Anda tidak diizinkan membatalkan pesanan ini",
  "已发货订单应办理退货，不能直接取消": "Pesanan yang sudah dikirim harus diproses sebagai retur, bukan dibatalkan langsung",
  "审批后的订单由管理员取消并释放库存": "Pesanan yang sudah disetujui hanya dapat dibatalkan oleh administrator untuk melepas stok cadangan",
  "请填写取消原因": "Masukkan alasan pembatalan",
  "只能重新分配待履约订单，并需填写原因": "Hanya pesanan yang belum selesai dipenuhi dapat dialihkan. Masukkan alasannya.",
  "供应链负责人无效": "Petugas rantai pasok tidak valid",
  "仅指定供应链负责人可发货": "Hanya petugas rantai pasok yang ditugaskan dapat mencatat pengiriman",
  "订单尚未审批或已经结束": "Pesanan belum disetujui atau sudah berakhir",
  "该订单已进入打包或发货阶段": "Pesanan sudah masuk tahap pengemasan atau pengiriman",
  "该单为先款后货，请财务确认回款后发货": "Pesanan ini harus dibayar sebelum dikirim. Minta keuangan mengonfirmasi pembayaran terlebih dahulu.",
  "请确认货物已经实际交付承运人或客户": "Konfirmasikan bahwa barang telah diserahkan kepada pengangkut atau pelanggan",
  "发货日期不能早于订单日期": "Tanggal pengiriman tidak boleh lebih awal dari tanggal pesanan",
  "请填写承运方式和实际发货仓库": "Masukkan cara pengangkutan dan gudang asal aktual",
  "每次发货最多选择10个凭证": "Maksimal 10 bukti per pengiriman",
  "出库凭证不存在或不属于此订单": "Bukti pengeluaran tidak ditemukan atau bukan milik pesanan ini",
  "发货必须提供物流单号，或上传出库照片／视频": "Sertakan nomor resi atau unggah foto/video pengeluaran untuk pengiriman",
  "请选择本次实际发货SKU及数量": "Pilih SKU dan jumlah aktual untuk pengiriman ini",
  "发货SKU无效或重复": "SKU pengiriman tidak valid atau duplikat",
  "本次发货件数": "Unit pengiriman ini",
  "{0}发货超过剩余订单量": "Jumlah pengiriman SKU {0} melebihi sisa pesanan",
  "订单预留库存不足，请核对分配记录": "Stok cadangan pesanan tidak cukup. Periksa catatan alokasi.",
  "请选择结算类型，并填写唯一银行流水号／票号及核对说明": "Pilih jenis transaksi, lalu masukkan nomor unik transaksi bank/faktur dan keterangan pemeriksaan",
  "结算日期不能早于订单日期": "Tanggal pembayaran atau faktur tidak boleh lebih awal dari tanggal pesanan",
  "请先审批订单，收款金额不能超过待收金额": "Setujui pesanan terlebih dahulu. Pembayaran masuk tidak boleh melebihi sisa tagihan.",
  "退款不能超过取消或退货形成的待退款金额": "Pengembalian dana tidak boleh melebihi dana yang perlu dikembalikan akibat pembatalan atau retur",
  "该单未审批、不需开票或金额超过待开票金额": "Pesanan belum disetujui, tidak memerlukan faktur, atau nilainya melebihi sisa nilai yang perlu dibuatkan faktur",
  "冲销金额不能超过现有有效开票金额": "Nilai pembatalan tidak boleh melebihi nilai faktur yang masih berlaku",
  "退货数量超过实际已发且未退数量": "Jumlah retur melebihi unit yang sudah dikirim dan belum diretur",
  "须确认仓库实际收回，填写退货原因及验收凭证": "Konfirmasikan penerimaan fisik oleh gudang dan isi alasan retur beserta bukti penerimaan",
  "退货登记日期不能早于该SKU最近发货日期": "Tanggal retur tidak boleh lebih awal dari tanggal pengiriman terakhir SKU tersebut",
  "原始扣库分配不足，退货未入库": "Alokasi pengurangan stok asal tidak cukup. Retur belum dimasukkan ke stok.",
  "未知的线下批发操作": "Tindakan grosir offline tidak dikenal",
  "审批线下出库": "Setujui pengeluaran offline",
  "安排线下打包发货": "Atur pengemasan dan pengiriman offline",
  "运营主管": "Manajer operasional",
  "线下分销": "Distribusi offline",
  "国家隔离异常": "Masalah pemisahan data negara",
  "订单明细合计不一致": "Total rincian pesanan tidak sesuai",
  "{0}库存分配不守恒": "Total alokasi stok SKU {0} tidak sesuai",
  "{0}发货明细与累计不一致": "Rincian pengiriman SKU {0} tidak sesuai dengan total kumulatif",
  "未足量发货却已完成": "Ditandai selesai sebelum seluruh barang dikirim",
  "回款逾期": "Pembayaran melewati jatuh tempo",
  "存在待退款余额": "Ada saldo dana yang perlu dikembalikan",
  "{0}预留余额少于线下订单锁定量": "Stok cadangan {0} kurang dari jumlah yang dikunci untuk pesanan offline",
  "{0}可售账面少于预留，请先处理销售或盘点差异": "Stok layak jual tercatat di {0} kurang dari stok cadangan. Selesaikan selisih penjualan atau stok opname terlebih dahulu.",
  "发货数量与库存扣减流水不一致": "Jumlah pengiriman tidak sesuai dengan mutasi pengurangan stok",
  "全部印尼线下订单及库存流水": "Semua pesanan offline Indonesia dan mutasi stok",
  "本人可见订单": "Pesanan yang dapat Anda akses",
  "线下业务暂时无法保存，请保留填写内容后重试；请勿重复创建同一订单": "Data grosir sementara gagal disimpan. Pertahankan isian dan coba lagi; jangan membuat pesanan yang sama dua kali.",
  "请求来源无效": "Asal permintaan tidak valid",
  "订单内容过大": "Isi pesanan terlalu besar",
  "请选择有效的导出范围和月份": "Pilih cakupan ekspor dan bulan yang valid",
  "对账导出失败，请稍后重试；系统未生成不完整报表": "Ekspor rekonsiliasi gagal. Coba lagi; sistem tidak menghasilkan laporan yang tidak lengkap.",
  "凭证存储暂时不可用，请稍后重试": "Penyimpanan bukti sementara tidak tersedia. Coba lagi.",
  "凭证读取或上传失败，请稍后重试": "Gagal membaca atau mengunggah bukti. Coba lagi.",
  "每份照片或视频不超过20MB": "Setiap foto atau video maksimal 20 MB",
  "仅该订单供应链负责人或管理员可上传发货凭证": "Hanya petugas rantai pasok pesanan ini atau administrator yang dapat mengunggah bukti pengiriman",
  "请在订单审批后、发货完成前上传凭证": "Unggah bukti setelah persetujuan dan sebelum pengiriman selesai",
  "请选择不超过20MB的照片或视频": "Pilih foto atau video maksimal 20 MB",
  "支持 JPG、PNG、WebP、MP4、WebM、MOV": "Format yang didukung: JPG, PNG, WebP, MP4, WebM, MOV",
  "文件内容与照片／视频格式不符": "Isi berkas tidak sesuai dengan format foto/video",
  "凭证不存在": "Bukti tidak ditemukan",
  "无权查看该出库凭证": "Anda tidak diizinkan melihat bukti pengeluaran ini",
  "凭证暂时无法读取": "Bukti sementara tidak dapat dibaca",
  "无权导出印尼线下订单": "Anda tidak diizinkan mengekspor pesanan offline Indonesia",
  "订单数据读取不完整，请重新导出": "Data pesanan belum terbaca lengkap. Ekspor kembali.",
  "新品开发": "Pengembangan produk",
  "工厂": "Pabrik",
  "海运": "Pengiriman laut",
  "请先登录 ChatGPT": "Silakan masuk ke ChatGPT terlebih dahulu",
  "账号已停用，请联系管理员": "Akun dinonaktifkan. Hubungi administrator.",
  "当前账号没有执行此操作的权限": "Akun ini tidak diizinkan menjalankan tindakan tersebut",
  "运营账号只能操作本人负责的站点和渠道": "Akun operasional hanya dapat mengelola negara dan kanal yang ditugaskan",
  "总览": "Ringkasan",
  "补货驾驶舱": "Dasbor pengadaan stok",
  "新品孵化": "Inkubasi produk baru",
  "销售数据": "Data penjualan",
  "库存流水": "Mutasi stok",
  "历史到仓": "Riwayat penerimaan",
  "月度计划": "Rencana bulanan",
  "审批中心": "Pusat persetujuan",
  "系列采购生产": "Pembelian dan produksi seri",
  "海运批次": "Batch pengiriman laut",
  "主数据": "Data master",
  "审计日志": "Log audit",
  "账号权限": "Hak akses akun",
  "权限测试": "Pemeriksaan hak akses",
  "每日销售导入": "Impor penjualan harian",
  "销售监控": "Pemantauan penjualan",
  "销售导入": "Impor penjualan",
  "品牌出海供应链控制塔": "Pusat kendali rantai pasok global",
  "系统导航": "Navigasi sistem",
  "移动端导航": "Navigasi seluler",
  "全局管理": "Manajemen menyeluruh",
  "印尼线下销售": "Penjualan offline Indonesia",
  "站点运营": "Operasional negara",
  "运营统筹": "Koordinasi operasional",
  "财务测算": "Analisis keuangan",
  "供应链协同": "Koordinasi rantai pasok",
  "工厂生产": "Produksi pabrik",
  "跨境物流": "Logistik lintas negara",
  "马来西亚": "Malaysia",
  "泰国": "Thailand",
  "越南": "Vietnam",
  "菲律宾": "Filipina",
  "退出登录": "Keluar",
  "全链路可视化协同": "Koordinasi seluruh rantai pasok",
  "SKU需求 → 系列采购 → 系列生产 → 海运批次 → 到仓上架": "Kebutuhan SKU → Pembelian → Produksi → Pengiriman laut → Stok siap jual",
  "导出备份": "Ekspor cadangan",
  "● 数据库已连接": "● Basis data terhubung",
  "备份导出失败": "Ekspor cadangan gagal",
  "全量备份已导出": "Cadangan lengkap telah diekspor",
  "Failed to fetch": "Koneksi gagal. Periksa jaringan dan coba lagi.",
  "NetworkError when attempting to fetch resource.": "Koneksi gagal. Periksa jaringan dan coba lagi.",
  "出库数量必须是有效的正整数": "Jumlah keluar gudang harus berupa bilangan bulat positif yang valid",
  "件数必须是有效的正整数": "Jumlah unit harus berupa bilangan bulat positif yang valid",
  "IDR成交单价必须是有效的正整数": "Harga satuan transaksi IDR harus berupa bilangan bulat positif yang valid",
  "本次发货件数必须是有效的正整数": "Unit pengiriman ini harus berupa bilangan bulat positif yang valid",
  "金额必须是有效的正整数": "Nilai harus berupa bilangan bulat positif yang valid",
  "退货件数必须是有效的正整数": "Unit retur harus berupa bilangan bulat positif yang valid"
};

Object.assign(WHOLESALE_ID,{
  "客户资料与交接": "Data dan Serah Terima Pelanggan",
  "修改影响新订单，历史订单保留原资料；交接不改变历史销售贡献。": "Perubahan berlaku untuk pesanan baru. Pesanan lama menyimpan data dan kontribusi penjualan asal.",
  "启用": "Aktif",
  "停用": "Nonaktif",
  "保存客户资料": "Simpan Data Pelanggan",
  "确认客户交接": "Konfirmasi Serah Terima",
  "纠正回款或退款记录": "Koreksi Penerimaan atau Pengembalian Dana",
  "冲正保留原记录；银行收款核销撤销后，金额返回未分配余额。": "Catatan asli tetap disimpan. Pembatalan alokasi mengembalikan dana ke saldo belum dialokasikan.",
  "确认冲正或撤销核销": "Konfirmasi Koreksi / Pembatalan Alokasi",
  "银行收款与多订单核销": "Penerimaan Bank dan Alokasi ke Beberapa Pesanan",
  "银行流水登记一次，可分配至同一客户的多张订单；未分配余额保留为客户预收。": "Catat transaksi bank satu kali, lalu alokasikan ke beberapa pesanan pelanggan yang sama. Sisanya menjadi uang muka pelanggan.",
  "登记对公收款": "Catat Penerimaan Rekening Perusahaan",
  "确认实际到账": "Konfirmasi Dana Diterima",
  "分配或处理": "Alokasi / Proses",
  "未分配余额": "Saldo Belum Dialokasikan",
  "合同待收款": "Sisa Tagihan Kontrak",
  "本次核销金额": "Jumlah Alokasi Ini",
  "确认分配核销": "Konfirmasi Alokasi",
  "未分配余额退款或冲正": "Pengembalian / Koreksi Saldo Belum Dialokasikan",
  "实际退回未分配款": "Kembalikan Dana Belum Dialokasikan",
  "冲正错误收款": "Koreksi Penerimaan Keliru",
  "确认处理": "Konfirmasi Proses",
  "财务关账与历史快照": "Tutup Buku dan Arsip Bulanan",
  "关账冻结该月及以前的业务日期，历史导出使用关账快照；反关账由管理员从最近月份开始。": "Tutup buku mengunci bulan ini dan sebelumnya. Ekspor memakai arsip saat penutupan. Administrator membuka kembali mulai bulan terakhir.",
  "客户状态": "Status Pelanggan",
  "修改或交接原因": "Alasan Perubahan / Serah Terima",
  "接手销售": "Penanggung Jawab Baru",
  "原始记录": "Catatan Asli",
  "冲正日期": "Tanggal Koreksi",
  "冲正凭证编号": "Nomor Bukti Koreksi",
  "冲正原因": "Alasan Koreksi",
  "实际到账金额 IDR": "Dana Diterima IDR",
  "银行流水号": "Referensi Transaksi Bank",
  "公司收款账户": "Rekening Perusahaan",
  "实际到账日期": "Tanggal Dana Diterima",
  "核对说明": "Catatan Verifikasi",
  "收款金额": "Dana Diterima",
  "已核销金额": "Jumlah Dialokasikan",
  "核销或处理日期": "Tanggal Alokasi / Proses",
  "处理说明": "Catatan Proses",
  "处理类型": "Jenis Proses",
  "已关账": "Buku Ditutup",
  "未关账": "Buku Terbuka",
  "关账或反关账原因": "Alasan Penutupan / Pembukaan Buku",
  "反关账": "Buka Kembali Buku",
  "确认关账": "Konfirmasi Tutup Buku",
  "回款冲正": "Koreksi Penerimaan",
  "退款冲正": "Koreksi Pengembalian",
  "撤销收款核销": "Pembatalan Alokasi",
  "银行收款余额": "Saldo Penerimaan Bank",
  "原收款IDR": "Penerimaan Asli IDR",
  "已核销IDR": "Dialokasikan IDR",
  "已退预收IDR": "Uang Muka Dikembalikan IDR",
  "冲正IDR": "Koreksi IDR",
  "未分配余额IDR": "Belum Dialokasikan IDR",
  "银行收支流水": "Arus Kas Bank",
  "银行到账": "Dana Bank Diterima",
  "实际收款净额IDR": "Penerimaan Bersih IDR",
  "实际退款净额IDR": "Pengembalian Bersih IDR",
  "关联单据": "Dokumen Terkait",
  "收款与核销": "Penerimaan dan Alokasi",
  "关账状态": "Status Tutup Buku",
  "已关账快照": "Arsip Buku Ditutup",
  "未关账实时数据": "Data Buku Terbuka",
  "银行收款余额和银行收支流水记录实际资金；收款退款明细按订单记录核销。同一笔银行到账分配多订单时，不可重复累加为银行收款。": "Saldo dan arus kas bank mencatat dana nyata; rincian pesanan mencatat alokasi. Alokasi ke beberapa pesanan tidak dihitung sebagai penerimaan bank tambahan."
});

Object.assign(WHOLESALE_ID,{
  "金额或数量必须是有效正整数": "Jumlah harus berupa bilangan bulat positif yang valid",
  "数据读取失败": "Gagal membaca data",
  "业务日期无效": "Tanggal transaksi tidak valid",
  "当前岗位无权执行此操作": "Peran Anda tidak diizinkan melakukan tindakan ini",
  "记录已更新，请刷新后重试": "Data telah berubah; muat ulang dan coba lagi",
  "仅印尼业务可维护客户": "Hanya bisnis Indonesia yang dapat mengelola pelanggan",
  "无权维护该客户": "Tidak diizinkan mengelola pelanggan ini",
  "客户交接必须填写原因": "Alasan serah terima pelanggan wajib diisi",
  "请选择已启用的印尼销售负责人": "Pilih penanggung jawab penjualan Indonesia yang aktif",
  "客户名称、联系人、电话、城市和地址必须完整": "Lengkapi nama pelanggan, kontak, telepon, kota dan alamat",
  "修改客户资料需填写原因": "Alasan perubahan data pelanggan wajib diisi",
  "已有同名同电话客户，请管理员核对，避免重复建档": "Pelanggan dengan nama dan telepon sama sudah ada; minta administrator memeriksa",
  "请选择已结束月份并填写关账或反关账原因": "Pilih bulan yang telah berakhir dan isi alasan penutupan atau pembukaan buku",
  "该月尚未关账": "Bulan ini belum ditutup",
  "请从最近的已关账月份开始逐月反关账": "Buka kembali buku berurutan mulai bulan ditutup paling akhir",
  "该月已经关账": "Bulan ini sudah ditutup",
  "该月份已包含在后续关账截止日内": "Bulan ini sudah tercakup dalam periode penutupan berikutnya",
  "请选择有效客户": "Pilih pelanggan aktif",
  "请填写银行流水号、公司收款账户和核对说明": "Isi referensi bank, rekening perusahaan dan catatan verifikasi",
  "请选择原始回款或退款记录": "Pilih catatan asli penerimaan atau pengembalian dana",
  "该记录已经冲正": "Catatan ini sudah dikoreksi",
  "请先核对并冲正相关退款，再撤销原回款": "Periksa dan koreksi pengembalian terkait sebelum membatalkan penerimaan asli",
  "冲正日期不能早于原记录，必须填写凭证和原因": "Tanggal koreksi tidak boleh sebelum catatan asli; bukti dan alasan wajib diisi",
  "原收款分配余额异常": "Saldo alokasi penerimaan asli tidak sesuai",
  "收款单不存在": "Dokumen penerimaan tidak ditemukan",
  "业务日期不能早于银行收款日期": "Tanggal transaksi tidak boleh sebelum tanggal penerimaan bank",
  "请选择1至50张订单进行核销": "Pilih 1 hingga 50 pesanan untuk alokasi",
  "核销订单须属于同一客户，且不能重复": "Pesanan alokasi harus milik pelanggan yang sama dan tidak boleh duplikat",
  "订单尚未批准、已取消或核销日期早于订单": "Pesanan belum disetujui, dibatalkan, atau tanggal alokasi mendahului pesanan",
  "核销金额超过订单待收金额": "Alokasi melebihi sisa tagihan pesanan",
  "银行收款分配核销": "Alokasi Penerimaan Bank",
  "核销合计超过该银行收款的未分配余额": "Total alokasi melebihi saldo penerimaan bank yang belum dialokasikan",
  "金额不能超过未分配余额，且需填写凭证和原因；已核销金额请先撤销核销": "Jumlah tidak boleh melebihi saldo belum dialokasikan; bukti dan alasan wajib. Batalkan alokasi terlebih dahulu untuk dana yang sudah dialokasikan",
  "未知财务操作": "Tindakan keuangan tidak dikenal",
  "记录已被更新，请刷新后重试": "Data telah berubah; muat ulang dan coba lagi",
  "记录、库存或结算月份已变化，本次操作未生效，请刷新核对": "Data, stok atau periode buku telah berubah. Tindakan tidak disimpan; muat ulang dan periksa",
  "系统正在备份或迁移，暂时停止写入，请稍后重试": "Sistem sedang dicadangkan atau dimigrasikan. Penyimpanan ditunda; coba lagi nanti"
});
